// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agentevent"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentEventUpdate is the builder for updating AgentEvent entities.
type AgentEventUpdate struct {
	config
	hooks    []Hook
	mutation *AgentEventMutation
}

// Where appends a list predicates to the AgentEventUpdate builder.
func (aeu *AgentEventUpdate) Where(ps ...predicate.AgentEvent) *AgentEventUpdate {
	aeu.mutation.Where(ps...)
	return aeu
}

// SetEventType sets the "event_type" field.
func (aeu *AgentEventUpdate) SetEventType(s string) *AgentEventUpdate {
	aeu.mutation.SetEventType(s)
	return aeu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableEventType(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetEventType(*s)
	}
	return aeu
}

// SetEventCategory sets the "event_category" field.
func (aeu *AgentEventUpdate) SetEventCategory(s string) *AgentEventUpdate {
	aeu.mutation.SetEventCategory(s)
	return aeu
}

// SetNillableEventCategory sets the "event_category" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableEventCategory(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetEventCategory(*s)
	}
	return aeu
}

// SetWorkflowID sets the "workflow_id" field.
func (aeu *AgentEventUpdate) SetWorkflowID(s string) *AgentEventUpdate {
	aeu.mutation.SetWorkflowID(s)
	return aeu
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableWorkflowID(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetWorkflowID(*s)
	}
	return aeu
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (aeu *AgentEventUpdate) ClearWorkflowID() *AgentEventUpdate {
	aeu.mutation.ClearWorkflowID()
	return aeu
}

// SetTaskID sets the "task_id" field.
func (aeu *AgentEventUpdate) SetTaskID(s string) *AgentEventUpdate {
	aeu.mutation.SetTaskID(s)
	return aeu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableTaskID(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetTaskID(*s)
	}
	return aeu
}

// ClearTaskID clears the value of the "task_id" field.
func (aeu *AgentEventUpdate) ClearTaskID() *AgentEventUpdate {
	aeu.mutation.ClearTaskID()
	return aeu
}

// SetAgentID sets the "agent_id" field.
func (aeu *AgentEventUpdate) SetAgentID(s string) *AgentEventUpdate {
	aeu.mutation.SetAgentID(s)
	return aeu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableAgentID(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetAgentID(*s)
	}
	return aeu
}

// ClearAgentID clears the value of the "agent_id" field.
func (aeu *AgentEventUpdate) ClearAgentID() *AgentEventUpdate {
	aeu.mutation.ClearAgentID()
	return aeu
}

// SetTraceID sets the "trace_id" field.
func (aeu *AgentEventUpdate) SetTraceID(s string) *AgentEventUpdate {
	aeu.mutation.SetTraceID(s)
	return aeu
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableTraceID(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetTraceID(*s)
	}
	return aeu
}

// ClearTraceID clears the value of the "trace_id" field.
func (aeu *AgentEventUpdate) ClearTraceID() *AgentEventUpdate {
	aeu.mutation.ClearTraceID()
	return aeu
}

// SetSpanID sets the "span_id" field.
func (aeu *AgentEventUpdate) SetSpanID(s string) *AgentEventUpdate {
	aeu.mutation.SetSpanID(s)
	return aeu
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableSpanID(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetSpanID(*s)
	}
	return aeu
}

// ClearSpanID clears the value of the "span_id" field.
func (aeu *AgentEventUpdate) ClearSpanID() *AgentEventUpdate {
	aeu.mutation.ClearSpanID()
	return aeu
}

// SetSeverity sets the "severity" field.
func (aeu *AgentEventUpdate) SetSeverity(s string) *AgentEventUpdate {
	aeu.mutation.SetSeverity(s)
	return aeu
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableSeverity(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetSeverity(*s)
	}
	return aeu
}

// SetData sets the "data" field.
func (aeu *AgentEventUpdate) SetData(m map[string]interface{}) *AgentEventUpdate {
	aeu.mutation.SetData(m)
	return aeu
}

// ClearData clears the value of the "data" field.
func (aeu *AgentEventUpdate) ClearData() *AgentEventUpdate {
	aeu.mutation.ClearData()
	return aeu
}

// SetMetadata sets the "metadata" field.
func (aeu *AgentEventUpdate) SetMetadata(m map[string]interface{}) *AgentEventUpdate {
	aeu.mutation.SetMetadata(m)
	return aeu
}

// ClearMetadata clears the value of the "metadata" field.
func (aeu *AgentEventUpdate) ClearMetadata() *AgentEventUpdate {
	aeu.mutation.ClearMetadata()
	return aeu
}

// SetTags sets the "tags" field.
func (aeu *AgentEventUpdate) SetTags(s []string) *AgentEventUpdate {
	aeu.mutation.SetTags(s)
	return aeu
}

// AppendTags appends s to the "tags" field.
func (aeu *AgentEventUpdate) AppendTags(s []string) *AgentEventUpdate {
	aeu.mutation.AppendTags(s)
	return aeu
}

// ClearTags clears the value of the "tags" field.
func (aeu *AgentEventUpdate) ClearTags() *AgentEventUpdate {
	aeu.mutation.ClearTags()
	return aeu
}

// SetSource sets the "source" field.
func (aeu *AgentEventUpdate) SetSource(s string) *AgentEventUpdate {
	aeu.mutation.SetSource(s)
	return aeu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableSource(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetSource(*s)
	}
	return aeu
}

// ClearSource clears the value of the "source" field.
func (aeu *AgentEventUpdate) ClearSource() *AgentEventUpdate {
	aeu.mutation.ClearSource()
	return aeu
}

// SetVersion sets the "version" field.
func (aeu *AgentEventUpdate) SetVersion(s string) *AgentEventUpdate {
	aeu.mutation.SetVersion(s)
	return aeu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (aeu *AgentEventUpdate) SetNillableVersion(s *string) *AgentEventUpdate {
	if s != nil {
		aeu.SetVersion(*s)
	}
	return aeu
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (aeu *AgentEventUpdate) SetWorkflow(w *Workflow) *AgentEventUpdate {
	return aeu.SetWorkflowID(w.ID)
}

// SetTask sets the "task" edge to the AgentTask entity.
func (aeu *AgentEventUpdate) SetTask(a *AgentTask) *AgentEventUpdate {
	return aeu.SetTaskID(a.ID)
}

// Mutation returns the AgentEventMutation object of the builder.
func (aeu *AgentEventUpdate) Mutation() *AgentEventMutation {
	return aeu.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (aeu *AgentEventUpdate) ClearWorkflow() *AgentEventUpdate {
	aeu.mutation.ClearWorkflow()
	return aeu
}

// ClearTask clears the "task" edge to the AgentTask entity.
func (aeu *AgentEventUpdate) ClearTask() *AgentEventUpdate {
	aeu.mutation.ClearTask()
	return aeu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aeu *AgentEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, aeu.sqlSave, aeu.mutation, aeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeu *AgentEventUpdate) SaveX(ctx context.Context) int {
	affected, err := aeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aeu *AgentEventUpdate) Exec(ctx context.Context) error {
	_, err := aeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeu *AgentEventUpdate) ExecX(ctx context.Context) {
	if err := aeu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeu *AgentEventUpdate) check() error {
	if v, ok := aeu.mutation.EventType(); ok {
		if err := agentevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AgentEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (aeu *AgentEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aeu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentevent.Table, agentevent.Columns, sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString))
	if ps := aeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeu.mutation.EventType(); ok {
		_spec.SetField(agentevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := aeu.mutation.EventCategory(); ok {
		_spec.SetField(agentevent.FieldEventCategory, field.TypeString, value)
	}
	if value, ok := aeu.mutation.AgentID(); ok {
		_spec.SetField(agentevent.FieldAgentID, field.TypeString, value)
	}
	if aeu.mutation.AgentIDCleared() {
		_spec.ClearField(agentevent.FieldAgentID, field.TypeString)
	}
	if value, ok := aeu.mutation.TraceID(); ok {
		_spec.SetField(agentevent.FieldTraceID, field.TypeString, value)
	}
	if aeu.mutation.TraceIDCleared() {
		_spec.ClearField(agentevent.FieldTraceID, field.TypeString)
	}
	if value, ok := aeu.mutation.SpanID(); ok {
		_spec.SetField(agentevent.FieldSpanID, field.TypeString, value)
	}
	if aeu.mutation.SpanIDCleared() {
		_spec.ClearField(agentevent.FieldSpanID, field.TypeString)
	}
	if value, ok := aeu.mutation.Severity(); ok {
		_spec.SetField(agentevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := aeu.mutation.Data(); ok {
		_spec.SetField(agentevent.FieldData, field.TypeJSON, value)
	}
	if aeu.mutation.DataCleared() {
		_spec.ClearField(agentevent.FieldData, field.TypeJSON)
	}
	if value, ok := aeu.mutation.Metadata(); ok {
		_spec.SetField(agentevent.FieldMetadata, field.TypeJSON, value)
	}
	if aeu.mutation.MetadataCleared() {
		_spec.ClearField(agentevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := aeu.mutation.Tags(); ok {
		_spec.SetField(agentevent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := aeu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentevent.FieldTags, value)
		})
	}
	if aeu.mutation.TagsCleared() {
		_spec.ClearField(agentevent.FieldTags, field.TypeJSON)
	}
	if value, ok := aeu.mutation.Source(); ok {
		_spec.SetField(agentevent.FieldSource, field.TypeString, value)
	}
	if aeu.mutation.SourceCleared() {
		_spec.ClearField(agentevent.FieldSource, field.TypeString)
	}
	if value, ok := aeu.mutation.Version(); ok {
		_spec.SetField(agentevent.FieldVersion, field.TypeString, value)
	}
	if aeu.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.WorkflowTable,
			Columns: []string{agentevent.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeu.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.WorkflowTable,
			Columns: []string{agentevent.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aeu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.TaskTable,
			Columns: []string{agentevent.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.TaskTable,
			Columns: []string{agentevent.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aeu.mutation.done = true
	return n, nil
}

// AgentEventUpdateOne is the builder for updating a single AgentEvent entity.
type AgentEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentEventMutation
}

// SetEventType sets the "event_type" field.
func (aeuo *AgentEventUpdateOne) SetEventType(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetEventType(s)
	return aeuo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableEventType(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetEventType(*s)
	}
	return aeuo
}

// SetEventCategory sets the "event_category" field.
func (aeuo *AgentEventUpdateOne) SetEventCategory(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetEventCategory(s)
	return aeuo
}

// SetNillableEventCategory sets the "event_category" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableEventCategory(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetEventCategory(*s)
	}
	return aeuo
}

// SetWorkflowID sets the "workflow_id" field.
func (aeuo *AgentEventUpdateOne) SetWorkflowID(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetWorkflowID(s)
	return aeuo
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableWorkflowID(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetWorkflowID(*s)
	}
	return aeuo
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (aeuo *AgentEventUpdateOne) ClearWorkflowID() *AgentEventUpdateOne {
	aeuo.mutation.ClearWorkflowID()
	return aeuo
}

// SetTaskID sets the "task_id" field.
func (aeuo *AgentEventUpdateOne) SetTaskID(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetTaskID(s)
	return aeuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableTaskID(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetTaskID(*s)
	}
	return aeuo
}

// ClearTaskID clears the value of the "task_id" field.
func (aeuo *AgentEventUpdateOne) ClearTaskID() *AgentEventUpdateOne {
	aeuo.mutation.ClearTaskID()
	return aeuo
}

// SetAgentID sets the "agent_id" field.
func (aeuo *AgentEventUpdateOne) SetAgentID(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetAgentID(s)
	return aeuo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableAgentID(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetAgentID(*s)
	}
	return aeuo
}

// ClearAgentID clears the value of the "agent_id" field.
func (aeuo *AgentEventUpdateOne) ClearAgentID() *AgentEventUpdateOne {
	aeuo.mutation.ClearAgentID()
	return aeuo
}

// SetTraceID sets the "trace_id" field.
func (aeuo *AgentEventUpdateOne) SetTraceID(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetTraceID(s)
	return aeuo
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableTraceID(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetTraceID(*s)
	}
	return aeuo
}

// ClearTraceID clears the value of the "trace_id" field.
func (aeuo *AgentEventUpdateOne) ClearTraceID() *AgentEventUpdateOne {
	aeuo.mutation.ClearTraceID()
	return aeuo
}

// SetSpanID sets the "span_id" field.
func (aeuo *AgentEventUpdateOne) SetSpanID(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetSpanID(s)
	return aeuo
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableSpanID(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetSpanID(*s)
	}
	return aeuo
}

// ClearSpanID clears the value of the "span_id" field.
func (aeuo *AgentEventUpdateOne) ClearSpanID() *AgentEventUpdateOne {
	aeuo.mutation.ClearSpanID()
	return aeuo
}

// SetSeverity sets the "severity" field.
func (aeuo *AgentEventUpdateOne) SetSeverity(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetSeverity(s)
	return aeuo
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableSeverity(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetSeverity(*s)
	}
	return aeuo
}

// SetData sets the "data" field.
func (aeuo *AgentEventUpdateOne) SetData(m map[string]interface{}) *AgentEventUpdateOne {
	aeuo.mutation.SetData(m)
	return aeuo
}

// ClearData clears the value of the "data" field.
func (aeuo *AgentEventUpdateOne) ClearData() *AgentEventUpdateOne {
	aeuo.mutation.ClearData()
	return aeuo
}

// SetMetadata sets the "metadata" field.
func (aeuo *AgentEventUpdateOne) SetMetadata(m map[string]interface{}) *AgentEventUpdateOne {
	aeuo.mutation.SetMetadata(m)
	return aeuo
}

// ClearMetadata clears the value of the "metadata" field.
func (aeuo *AgentEventUpdateOne) ClearMetadata() *AgentEventUpdateOne {
	aeuo.mutation.ClearMetadata()
	return aeuo
}

// SetTags sets the "tags" field.
func (aeuo *AgentEventUpdateOne) SetTags(s []string) *AgentEventUpdateOne {
	aeuo.mutation.SetTags(s)
	return aeuo
}

// AppendTags appends s to the "tags" field.
func (aeuo *AgentEventUpdateOne) AppendTags(s []string) *AgentEventUpdateOne {
	aeuo.mutation.AppendTags(s)
	return aeuo
}

// ClearTags clears the value of the "tags" field.
func (aeuo *AgentEventUpdateOne) ClearTags() *AgentEventUpdateOne {
	aeuo.mutation.ClearTags()
	return aeuo
}

// SetSource sets the "source" field.
func (aeuo *AgentEventUpdateOne) SetSource(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetSource(s)
	return aeuo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableSource(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetSource(*s)
	}
	return aeuo
}

// ClearSource clears the value of the "source" field.
func (aeuo *AgentEventUpdateOne) ClearSource() *AgentEventUpdateOne {
	aeuo.mutation.ClearSource()
	return aeuo
}

// SetVersion sets the "version" field.
func (aeuo *AgentEventUpdateOne) SetVersion(s string) *AgentEventUpdateOne {
	aeuo.mutation.SetVersion(s)
	return aeuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (aeuo *AgentEventUpdateOne) SetNillableVersion(s *string) *AgentEventUpdateOne {
	if s != nil {
		aeuo.SetVersion(*s)
	}
	return aeuo
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (aeuo *AgentEventUpdateOne) SetWorkflow(w *Workflow) *AgentEventUpdateOne {
	return aeuo.SetWorkflowID(w.ID)
}

// SetTask sets the "task" edge to the AgentTask entity.
func (aeuo *AgentEventUpdateOne) SetTask(a *AgentTask) *AgentEventUpdateOne {
	return aeuo.SetTaskID(a.ID)
}

// Mutation returns the AgentEventMutation object of the builder.
func (aeuo *AgentEventUpdateOne) Mutation() *AgentEventMutation {
	return aeuo.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (aeuo *AgentEventUpdateOne) ClearWorkflow() *AgentEventUpdateOne {
	aeuo.mutation.ClearWorkflow()
	return aeuo
}

// ClearTask clears the "task" edge to the AgentTask entity.
func (aeuo *AgentEventUpdateOne) ClearTask() *AgentEventUpdateOne {
	aeuo.mutation.ClearTask()
	return aeuo
}

// Where appends a list predicates to the AgentEventUpdate builder.
func (aeuo *AgentEventUpdateOne) Where(ps ...predicate.AgentEvent) *AgentEventUpdateOne {
	aeuo.mutation.Where(ps...)
	return aeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aeuo *AgentEventUpdateOne) Select(field string, fields ...string) *AgentEventUpdateOne {
	aeuo.fields = append([]string{field}, fields...)
	return aeuo
}

// Save executes the query and returns the updated AgentEvent entity.
func (aeuo *AgentEventUpdateOne) Save(ctx context.Context) (*AgentEvent, error) {
	return withHooks(ctx, aeuo.sqlSave, aeuo.mutation, aeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeuo *AgentEventUpdateOne) SaveX(ctx context.Context) *AgentEvent {
	node, err := aeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aeuo *AgentEventUpdateOne) Exec(ctx context.Context) error {
	_, err := aeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeuo *AgentEventUpdateOne) ExecX(ctx context.Context) {
	if err := aeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeuo *AgentEventUpdateOne) check() error {
	if v, ok := aeuo.mutation.EventType(); ok {
		if err := agentevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "AgentEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (aeuo *AgentEventUpdateOne) sqlSave(ctx context.Context) (_node *AgentEvent, err error) {
	if err := aeuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentevent.Table, agentevent.Columns, sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString))
	id, ok := aeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentevent.FieldID)
		for _, f := range fields {
			if !agentevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeuo.mutation.EventType(); ok {
		_spec.SetField(agentevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.EventCategory(); ok {
		_spec.SetField(agentevent.FieldEventCategory, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.AgentID(); ok {
		_spec.SetField(agentevent.FieldAgentID, field.TypeString, value)
	}
	if aeuo.mutation.AgentIDCleared() {
		_spec.ClearField(agentevent.FieldAgentID, field.TypeString)
	}
	if value, ok := aeuo.mutation.TraceID(); ok {
		_spec.SetField(agentevent.FieldTraceID, field.TypeString, value)
	}
	if aeuo.mutation.TraceIDCleared() {
		_spec.ClearField(agentevent.FieldTraceID, field.TypeString)
	}
	if value, ok := aeuo.mutation.SpanID(); ok {
		_spec.SetField(agentevent.FieldSpanID, field.TypeString, value)
	}
	if aeuo.mutation.SpanIDCleared() {
		_spec.ClearField(agentevent.FieldSpanID, field.TypeString)
	}
	if value, ok := aeuo.mutation.Severity(); ok {
		_spec.SetField(agentevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.Data(); ok {
		_spec.SetField(agentevent.FieldData, field.TypeJSON, value)
	}
	if aeuo.mutation.DataCleared() {
		_spec.ClearField(agentevent.FieldData, field.TypeJSON)
	}
	if value, ok := aeuo.mutation.Metadata(); ok {
		_spec.SetField(agentevent.FieldMetadata, field.TypeJSON, value)
	}
	if aeuo.mutation.MetadataCleared() {
		_spec.ClearField(agentevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := aeuo.mutation.Tags(); ok {
		_spec.SetField(agentevent.FieldTags, field.TypeJSON, value)
	}
	if value, ok := aeuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agentevent.FieldTags, value)
		})
	}
	if aeuo.mutation.TagsCleared() {
		_spec.ClearField(agentevent.FieldTags, field.TypeJSON)
	}
	if value, ok := aeuo.mutation.Source(); ok {
		_spec.SetField(agentevent.FieldSource, field.TypeString, value)
	}
	if aeuo.mutation.SourceCleared() {
		_spec.ClearField(agentevent.FieldSource, field.TypeString)
	}
	if value, ok := aeuo.mutation.Version(); ok {
		_spec.SetField(agentevent.FieldVersion, field.TypeString, value)
	}
	if aeuo.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.WorkflowTable,
			Columns: []string{agentevent.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeuo.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.WorkflowTable,
			Columns: []string{agentevent.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aeuo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.TaskTable,
			Columns: []string{agentevent.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeuo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentevent.TaskTable,
			Columns: []string{agentevent.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentEvent{config: aeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aeuo.mutation.done = true
	return _node, nil
}
