// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agentevent"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentEventQuery is the builder for querying AgentEvent entities.
type AgentEventQuery struct {
	config
	ctx          *QueryContext
	order        []agentevent.OrderOption
	inters       []Interceptor
	predicates   []predicate.AgentEvent
	withWorkflow *WorkflowQuery
	withTask     *AgentTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentEventQuery builder.
func (aeq *AgentEventQuery) Where(ps ...predicate.AgentEvent) *AgentEventQuery {
	aeq.predicates = append(aeq.predicates, ps...)
	return aeq
}

// Limit the number of records to be returned by this query.
func (aeq *AgentEventQuery) Limit(limit int) *AgentEventQuery {
	aeq.ctx.Limit = &limit
	return aeq
}

// Offset to start from.
func (aeq *AgentEventQuery) Offset(offset int) *AgentEventQuery {
	aeq.ctx.Offset = &offset
	return aeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aeq *AgentEventQuery) Unique(unique bool) *AgentEventQuery {
	aeq.ctx.Unique = &unique
	return aeq
}

// Order specifies how the records should be ordered.
func (aeq *AgentEventQuery) Order(o ...agentevent.OrderOption) *AgentEventQuery {
	aeq.order = append(aeq.order, o...)
	return aeq
}

// QueryWorkflow chains the current query on the "workflow" edge.
func (aeq *AgentEventQuery) QueryWorkflow() *WorkflowQuery {
	query := (&WorkflowClient{config: aeq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aeq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentevent.Table, agentevent.FieldID, selector),
			sqlgraph.To(workflow.Table, workflow.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agentevent.WorkflowTable, agentevent.WorkflowColumn),
		)
		fromU = sqlgraph.SetNeighbors(aeq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTask chains the current query on the "task" edge.
func (aeq *AgentEventQuery) QueryTask() *AgentTaskQuery {
	query := (&AgentTaskClient{config: aeq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aeq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agentevent.Table, agentevent.FieldID, selector),
			sqlgraph.To(agenttask.Table, agenttask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agentevent.TaskTable, agentevent.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(aeq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentEvent entity from the query.
// Returns a *NotFoundError when no AgentEvent was found.
func (aeq *AgentEventQuery) First(ctx context.Context) (*AgentEvent, error) {
	nodes, err := aeq.Limit(1).All(setContextOp(ctx, aeq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agentevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aeq *AgentEventQuery) FirstX(ctx context.Context) *AgentEvent {
	node, err := aeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentEvent ID from the query.
// Returns a *NotFoundError when no AgentEvent ID was found.
func (aeq *AgentEventQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aeq.Limit(1).IDs(setContextOp(ctx, aeq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agentevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aeq *AgentEventQuery) FirstIDX(ctx context.Context) string {
	id, err := aeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentEvent entity is found.
// Returns a *NotFoundError when no AgentEvent entities are found.
func (aeq *AgentEventQuery) Only(ctx context.Context) (*AgentEvent, error) {
	nodes, err := aeq.Limit(2).All(setContextOp(ctx, aeq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agentevent.Label}
	default:
		return nil, &NotSingularError{agentevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aeq *AgentEventQuery) OnlyX(ctx context.Context) *AgentEvent {
	node, err := aeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentEvent ID in the query.
// Returns a *NotSingularError when more than one AgentEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (aeq *AgentEventQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aeq.Limit(2).IDs(setContextOp(ctx, aeq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agentevent.Label}
	default:
		err = &NotSingularError{agentevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aeq *AgentEventQuery) OnlyIDX(ctx context.Context) string {
	id, err := aeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentEvents.
func (aeq *AgentEventQuery) All(ctx context.Context) ([]*AgentEvent, error) {
	ctx = setContextOp(ctx, aeq.ctx, ent.OpQueryAll)
	if err := aeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentEvent, *AgentEventQuery]()
	return withInterceptors[[]*AgentEvent](ctx, aeq, qr, aeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aeq *AgentEventQuery) AllX(ctx context.Context) []*AgentEvent {
	nodes, err := aeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentEvent IDs.
func (aeq *AgentEventQuery) IDs(ctx context.Context) (ids []string, err error) {
	if aeq.ctx.Unique == nil && aeq.path != nil {
		aeq.Unique(true)
	}
	ctx = setContextOp(ctx, aeq.ctx, ent.OpQueryIDs)
	if err = aeq.Select(agentevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aeq *AgentEventQuery) IDsX(ctx context.Context) []string {
	ids, err := aeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aeq *AgentEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aeq.ctx, ent.OpQueryCount)
	if err := aeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aeq, querierCount[*AgentEventQuery](), aeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aeq *AgentEventQuery) CountX(ctx context.Context) int {
	count, err := aeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aeq *AgentEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aeq.ctx, ent.OpQueryExist)
	switch _, err := aeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aeq *AgentEventQuery) ExistX(ctx context.Context) bool {
	exist, err := aeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aeq *AgentEventQuery) Clone() *AgentEventQuery {
	if aeq == nil {
		return nil
	}
	return &AgentEventQuery{
		config:       aeq.config,
		ctx:          aeq.ctx.Clone(),
		order:        append([]agentevent.OrderOption{}, aeq.order...),
		inters:       append([]Interceptor{}, aeq.inters...),
		predicates:   append([]predicate.AgentEvent{}, aeq.predicates...),
		withWorkflow: aeq.withWorkflow.Clone(),
		withTask:     aeq.withTask.Clone(),
		// clone intermediate query.
		sql:  aeq.sql.Clone(),
		path: aeq.path,
	}
}

// WithWorkflow tells the query-builder to eager-load the nodes that are connected to
// the "workflow" edge. The optional arguments are used to configure the query builder of the edge.
func (aeq *AgentEventQuery) WithWorkflow(opts ...func(*WorkflowQuery)) *AgentEventQuery {
	query := (&WorkflowClient{config: aeq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aeq.withWorkflow = query
	return aeq
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (aeq *AgentEventQuery) WithTask(opts ...func(*AgentTaskQuery)) *AgentEventQuery {
	query := (&AgentTaskClient{config: aeq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aeq.withTask = query
	return aeq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EventType string `json:"event_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentEvent.Query().
//		GroupBy(agentevent.FieldEventType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aeq *AgentEventQuery) GroupBy(field string, fields ...string) *AgentEventGroupBy {
	aeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentEventGroupBy{build: aeq}
	grbuild.flds = &aeq.ctx.Fields
	grbuild.label = agentevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EventType string `json:"event_type,omitempty"`
//	}
//
//	client.AgentEvent.Query().
//		Select(agentevent.FieldEventType).
//		Scan(ctx, &v)
func (aeq *AgentEventQuery) Select(fields ...string) *AgentEventSelect {
	aeq.ctx.Fields = append(aeq.ctx.Fields, fields...)
	sbuild := &AgentEventSelect{AgentEventQuery: aeq}
	sbuild.label = agentevent.Label
	sbuild.flds, sbuild.scan = &aeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentEventSelect configured with the given aggregations.
func (aeq *AgentEventQuery) Aggregate(fns ...AggregateFunc) *AgentEventSelect {
	return aeq.Select().Aggregate(fns...)
}

func (aeq *AgentEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aeq); err != nil {
				return err
			}
		}
	}
	for _, f := range aeq.ctx.Fields {
		if !agentevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aeq.path != nil {
		prev, err := aeq.path(ctx)
		if err != nil {
			return err
		}
		aeq.sql = prev
	}
	return nil
}

func (aeq *AgentEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentEvent, error) {
	var (
		nodes       = []*AgentEvent{}
		_spec       = aeq.querySpec()
		loadedTypes = [2]bool{
			aeq.withWorkflow != nil,
			aeq.withTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentEvent{config: aeq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aeq.withWorkflow; query != nil {
		if err := aeq.loadWorkflow(ctx, query, nodes, nil,
			func(n *AgentEvent, e *Workflow) { n.Edges.Workflow = e }); err != nil {
			return nil, err
		}
	}
	if query := aeq.withTask; query != nil {
		if err := aeq.loadTask(ctx, query, nodes, nil,
			func(n *AgentEvent, e *AgentTask) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aeq *AgentEventQuery) loadWorkflow(ctx context.Context, query *WorkflowQuery, nodes []*AgentEvent, init func(*AgentEvent), assign func(*AgentEvent, *Workflow)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*AgentEvent)
	for i := range nodes {
		fk := nodes[i].WorkflowID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflow.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (aeq *AgentEventQuery) loadTask(ctx context.Context, query *AgentTaskQuery, nodes []*AgentEvent, init func(*AgentEvent), assign func(*AgentEvent, *AgentTask)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*AgentEvent)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agenttask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aeq *AgentEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aeq.querySpec()
	_spec.Node.Columns = aeq.ctx.Fields
	if len(aeq.ctx.Fields) > 0 {
		_spec.Unique = aeq.ctx.Unique != nil && *aeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aeq.driver, _spec)
}

func (aeq *AgentEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agentevent.Table, agentevent.Columns, sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString))
	_spec.From = aeq.sql
	if unique := aeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aeq.path != nil {
		_spec.Unique = true
	}
	if fields := aeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentevent.FieldID)
		for i := range fields {
			if fields[i] != agentevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if aeq.withWorkflow != nil {
			_spec.Node.AddColumnOnce(agentevent.FieldWorkflowID)
		}
		if aeq.withTask != nil {
			_spec.Node.AddColumnOnce(agentevent.FieldTaskID)
		}
	}
	if ps := aeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aeq *AgentEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aeq.driver.Dialect())
	t1 := builder.Table(agentevent.Table)
	columns := aeq.ctx.Fields
	if len(columns) == 0 {
		columns = agentevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aeq.sql != nil {
		selector = aeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aeq.ctx.Unique != nil && *aeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aeq.predicates {
		p(selector)
	}
	for _, p := range aeq.order {
		p(selector)
	}
	if offset := aeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgentEventGroupBy is the group-by builder for AgentEvent entities.
type AgentEventGroupBy struct {
	selector
	build *AgentEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aegb *AgentEventGroupBy) Aggregate(fns ...AggregateFunc) *AgentEventGroupBy {
	aegb.fns = append(aegb.fns, fns...)
	return aegb
}

// Scan applies the selector query and scans the result into the given value.
func (aegb *AgentEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aegb.build.ctx, ent.OpQueryGroupBy)
	if err := aegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentEventQuery, *AgentEventGroupBy](ctx, aegb.build, aegb, aegb.build.inters, v)
}

func (aegb *AgentEventGroupBy) sqlScan(ctx context.Context, root *AgentEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aegb.fns))
	for _, fn := range aegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aegb.flds)+len(aegb.fns))
		for _, f := range *aegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentEventSelect is the builder for selecting fields of AgentEvent entities.
type AgentEventSelect struct {
	*AgentEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aes *AgentEventSelect) Aggregate(fns ...AggregateFunc) *AgentEventSelect {
	aes.fns = append(aes.fns, fns...)
	return aes
}

// Scan applies the selector query and scans the result into the given value.
func (aes *AgentEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aes.ctx, ent.OpQuerySelect)
	if err := aes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentEventQuery, *AgentEventSelect](ctx, aes.AgentEventQuery, aes, aes.inters, v)
}

func (aes *AgentEventSelect) sqlScan(ctx context.Context, root *AgentEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aes.fns))
	for _, fn := range aes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
