// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentHandoff is the model entity for the AgentHandoff schema.
type AgentHandoff struct {
	config `json:"-"`
	// ID of the ent.
	// Unique handoff identifier (UUID)
	ID string `json:"id,omitempty"`
	// Parent workflow ID
	WorkflowID string `json:"workflow_id,omitempty"`
	// Agent initiating the handoff
	FromAgentID string `json:"from_agent_id,omitempty"`
	// Type of source agent
	FromAgentType string `json:"from_agent_type,omitempty"`
	// Agent receiving the handoff
	ToAgentID string `json:"to_agent_id,omitempty"`
	// Type of target agent
	ToAgentType string `json:"to_agent_type,omitempty"`
	// Type of handoff: request, response, broadcast, delegate
	HandoffType string `json:"handoff_type,omitempty"`
	// Handoff status: pending, accepted, rejected, completed, failed
	Status string `json:"status,omitempty"`
	// OpenTelemetry trace ID
	TraceID string `json:"trace_id,omitempty"`
	// Task ID in the source agent
	FromTaskID string `json:"from_task_id,omitempty"`
	// Task ID in the target agent
	ToTaskID string `json:"to_task_id,omitempty"`
	// Data being passed between agents
	Payload map[string]interface{} `json:"payload,omitempty"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Size of the payload in bytes
	PayloadSizeBytes int `json:"payload_size_bytes,omitempty"`
	// Time from handoff initiation to acceptance
	LatencyMs int64 `json:"latency_ms,omitempty"`
	// Error message if handoff failed
	ErrorMessage string `json:"error_message,omitempty"`
	// When the handoff was initiated
	InitiatedAt time.Time `json:"initiated_at,omitempty"`
	// When the handoff was accepted
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// When the handoff was completed
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentHandoffQuery when eager-loading is set.
	Edges        AgentHandoffEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentHandoffEdges holds the relations/edges for other nodes in the graph.
type AgentHandoffEdges struct {
	// Workflow holds the value of the workflow edge.
	Workflow *Workflow `json:"workflow,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkflowOrErr returns the Workflow value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentHandoffEdges) WorkflowOrErr() (*Workflow, error) {
	if e.Workflow != nil {
		return e.Workflow, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workflow.Label}
	}
	return nil, &NotLoadedError{edge: "workflow"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentHandoff) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agenthandoff.FieldPayload, agenthandoff.FieldMetadata:
			values[i] = new([]byte)
		case agenthandoff.FieldPayloadSizeBytes, agenthandoff.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case agenthandoff.FieldID, agenthandoff.FieldWorkflowID, agenthandoff.FieldFromAgentID, agenthandoff.FieldFromAgentType, agenthandoff.FieldToAgentID, agenthandoff.FieldToAgentType, agenthandoff.FieldHandoffType, agenthandoff.FieldStatus, agenthandoff.FieldTraceID, agenthandoff.FieldFromTaskID, agenthandoff.FieldToTaskID, agenthandoff.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case agenthandoff.FieldInitiatedAt, agenthandoff.FieldAcceptedAt, agenthandoff.FieldCompletedAt, agenthandoff.FieldCreatedAt, agenthandoff.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentHandoff fields.
func (ah *AgentHandoff) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agenthandoff.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ah.ID = value.String
			}
		case agenthandoff.FieldWorkflowID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workflow_id", values[i])
			} else if value.Valid {
				ah.WorkflowID = value.String
			}
		case agenthandoff.FieldFromAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_agent_id", values[i])
			} else if value.Valid {
				ah.FromAgentID = value.String
			}
		case agenthandoff.FieldFromAgentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_agent_type", values[i])
			} else if value.Valid {
				ah.FromAgentType = value.String
			}
		case agenthandoff.FieldToAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_agent_id", values[i])
			} else if value.Valid {
				ah.ToAgentID = value.String
			}
		case agenthandoff.FieldToAgentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_agent_type", values[i])
			} else if value.Valid {
				ah.ToAgentType = value.String
			}
		case agenthandoff.FieldHandoffType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field handoff_type", values[i])
			} else if value.Valid {
				ah.HandoffType = value.String
			}
		case agenthandoff.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ah.Status = value.String
			}
		case agenthandoff.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				ah.TraceID = value.String
			}
		case agenthandoff.FieldFromTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_task_id", values[i])
			} else if value.Valid {
				ah.FromTaskID = value.String
			}
		case agenthandoff.FieldToTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_task_id", values[i])
			} else if value.Valid {
				ah.ToTaskID = value.String
			}
		case agenthandoff.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ah.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case agenthandoff.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ah.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case agenthandoff.FieldPayloadSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payload_size_bytes", values[i])
			} else if value.Valid {
				ah.PayloadSizeBytes = int(value.Int64)
			}
		case agenthandoff.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				ah.LatencyMs = value.Int64
			}
		case agenthandoff.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				ah.ErrorMessage = value.String
			}
		case agenthandoff.FieldInitiatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field initiated_at", values[i])
			} else if value.Valid {
				ah.InitiatedAt = value.Time
			}
		case agenthandoff.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				ah.AcceptedAt = new(time.Time)
				*ah.AcceptedAt = value.Time
			}
		case agenthandoff.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				ah.CompletedAt = new(time.Time)
				*ah.CompletedAt = value.Time
			}
		case agenthandoff.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ah.CreatedAt = value.Time
			}
		case agenthandoff.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ah.UpdatedAt = value.Time
			}
		default:
			ah.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentHandoff.
// This includes values selected through modifiers, order, etc.
func (ah *AgentHandoff) Value(name string) (ent.Value, error) {
	return ah.selectValues.Get(name)
}

// QueryWorkflow queries the "workflow" edge of the AgentHandoff entity.
func (ah *AgentHandoff) QueryWorkflow() *WorkflowQuery {
	return NewAgentHandoffClient(ah.config).QueryWorkflow(ah)
}

// Update returns a builder for updating this AgentHandoff.
// Note that you need to call AgentHandoff.Unwrap() before calling this method if this AgentHandoff
// was returned from a transaction, and the transaction was committed or rolled back.
func (ah *AgentHandoff) Update() *AgentHandoffUpdateOne {
	return NewAgentHandoffClient(ah.config).UpdateOne(ah)
}

// Unwrap unwraps the AgentHandoff entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ah *AgentHandoff) Unwrap() *AgentHandoff {
	_tx, ok := ah.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentHandoff is not a transactional entity")
	}
	ah.config.driver = _tx.drv
	return ah
}

// String implements the fmt.Stringer.
func (ah *AgentHandoff) String() string {
	var builder strings.Builder
	builder.WriteString("AgentHandoff(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ah.ID))
	builder.WriteString("workflow_id=")
	builder.WriteString(ah.WorkflowID)
	builder.WriteString(", ")
	builder.WriteString("from_agent_id=")
	builder.WriteString(ah.FromAgentID)
	builder.WriteString(", ")
	builder.WriteString("from_agent_type=")
	builder.WriteString(ah.FromAgentType)
	builder.WriteString(", ")
	builder.WriteString("to_agent_id=")
	builder.WriteString(ah.ToAgentID)
	builder.WriteString(", ")
	builder.WriteString("to_agent_type=")
	builder.WriteString(ah.ToAgentType)
	builder.WriteString(", ")
	builder.WriteString("handoff_type=")
	builder.WriteString(ah.HandoffType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ah.Status)
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(ah.TraceID)
	builder.WriteString(", ")
	builder.WriteString("from_task_id=")
	builder.WriteString(ah.FromTaskID)
	builder.WriteString(", ")
	builder.WriteString("to_task_id=")
	builder.WriteString(ah.ToTaskID)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", ah.Payload))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", ah.Metadata))
	builder.WriteString(", ")
	builder.WriteString("payload_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", ah.PayloadSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", ah.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(ah.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("initiated_at=")
	builder.WriteString(ah.InitiatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ah.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ah.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ah.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ah.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AgentHandoffs is a parsable slice of AgentHandoff.
type AgentHandoffs []*AgentHandoff
