// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentHandoffQuery is the builder for querying AgentHandoff entities.
type AgentHandoffQuery struct {
	config
	ctx          *QueryContext
	order        []agenthandoff.OrderOption
	inters       []Interceptor
	predicates   []predicate.AgentHandoff
	withWorkflow *WorkflowQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentHandoffQuery builder.
func (ahq *AgentHandoffQuery) Where(ps ...predicate.AgentHandoff) *AgentHandoffQuery {
	ahq.predicates = append(ahq.predicates, ps...)
	return ahq
}

// Limit the number of records to be returned by this query.
func (ahq *AgentHandoffQuery) Limit(limit int) *AgentHandoffQuery {
	ahq.ctx.Limit = &limit
	return ahq
}

// Offset to start from.
func (ahq *AgentHandoffQuery) Offset(offset int) *AgentHandoffQuery {
	ahq.ctx.Offset = &offset
	return ahq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ahq *AgentHandoffQuery) Unique(unique bool) *AgentHandoffQuery {
	ahq.ctx.Unique = &unique
	return ahq
}

// Order specifies how the records should be ordered.
func (ahq *AgentHandoffQuery) Order(o ...agenthandoff.OrderOption) *AgentHandoffQuery {
	ahq.order = append(ahq.order, o...)
	return ahq
}

// QueryWorkflow chains the current query on the "workflow" edge.
func (ahq *AgentHandoffQuery) QueryWorkflow() *WorkflowQuery {
	query := (&WorkflowClient{config: ahq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ahq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ahq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agenthandoff.Table, agenthandoff.FieldID, selector),
			sqlgraph.To(workflow.Table, workflow.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agenthandoff.WorkflowTable, agenthandoff.WorkflowColumn),
		)
		fromU = sqlgraph.SetNeighbors(ahq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AgentHandoff entity from the query.
// Returns a *NotFoundError when no AgentHandoff was found.
func (ahq *AgentHandoffQuery) First(ctx context.Context) (*AgentHandoff, error) {
	nodes, err := ahq.Limit(1).All(setContextOp(ctx, ahq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agenthandoff.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ahq *AgentHandoffQuery) FirstX(ctx context.Context) *AgentHandoff {
	node, err := ahq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgentHandoff ID from the query.
// Returns a *NotFoundError when no AgentHandoff ID was found.
func (ahq *AgentHandoffQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ahq.Limit(1).IDs(setContextOp(ctx, ahq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agenthandoff.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ahq *AgentHandoffQuery) FirstIDX(ctx context.Context) string {
	id, err := ahq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgentHandoff entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgentHandoff entity is found.
// Returns a *NotFoundError when no AgentHandoff entities are found.
func (ahq *AgentHandoffQuery) Only(ctx context.Context) (*AgentHandoff, error) {
	nodes, err := ahq.Limit(2).All(setContextOp(ctx, ahq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agenthandoff.Label}
	default:
		return nil, &NotSingularError{agenthandoff.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ahq *AgentHandoffQuery) OnlyX(ctx context.Context) *AgentHandoff {
	node, err := ahq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgentHandoff ID in the query.
// Returns a *NotSingularError when more than one AgentHandoff ID is found.
// Returns a *NotFoundError when no entities are found.
func (ahq *AgentHandoffQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ahq.Limit(2).IDs(setContextOp(ctx, ahq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agenthandoff.Label}
	default:
		err = &NotSingularError{agenthandoff.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ahq *AgentHandoffQuery) OnlyIDX(ctx context.Context) string {
	id, err := ahq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgentHandoffs.
func (ahq *AgentHandoffQuery) All(ctx context.Context) ([]*AgentHandoff, error) {
	ctx = setContextOp(ctx, ahq.ctx, ent.OpQueryAll)
	if err := ahq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgentHandoff, *AgentHandoffQuery]()
	return withInterceptors[[]*AgentHandoff](ctx, ahq, qr, ahq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ahq *AgentHandoffQuery) AllX(ctx context.Context) []*AgentHandoff {
	nodes, err := ahq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgentHandoff IDs.
func (ahq *AgentHandoffQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ahq.ctx.Unique == nil && ahq.path != nil {
		ahq.Unique(true)
	}
	ctx = setContextOp(ctx, ahq.ctx, ent.OpQueryIDs)
	if err = ahq.Select(agenthandoff.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ahq *AgentHandoffQuery) IDsX(ctx context.Context) []string {
	ids, err := ahq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ahq *AgentHandoffQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ahq.ctx, ent.OpQueryCount)
	if err := ahq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ahq, querierCount[*AgentHandoffQuery](), ahq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ahq *AgentHandoffQuery) CountX(ctx context.Context) int {
	count, err := ahq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ahq *AgentHandoffQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ahq.ctx, ent.OpQueryExist)
	switch _, err := ahq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ahq *AgentHandoffQuery) ExistX(ctx context.Context) bool {
	exist, err := ahq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentHandoffQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ahq *AgentHandoffQuery) Clone() *AgentHandoffQuery {
	if ahq == nil {
		return nil
	}
	return &AgentHandoffQuery{
		config:       ahq.config,
		ctx:          ahq.ctx.Clone(),
		order:        append([]agenthandoff.OrderOption{}, ahq.order...),
		inters:       append([]Interceptor{}, ahq.inters...),
		predicates:   append([]predicate.AgentHandoff{}, ahq.predicates...),
		withWorkflow: ahq.withWorkflow.Clone(),
		// clone intermediate query.
		sql:  ahq.sql.Clone(),
		path: ahq.path,
	}
}

// WithWorkflow tells the query-builder to eager-load the nodes that are connected to
// the "workflow" edge. The optional arguments are used to configure the query builder of the edge.
func (ahq *AgentHandoffQuery) WithWorkflow(opts ...func(*WorkflowQuery)) *AgentHandoffQuery {
	query := (&WorkflowClient{config: ahq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ahq.withWorkflow = query
	return ahq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WorkflowID string `json:"workflow_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgentHandoff.Query().
//		GroupBy(agenthandoff.FieldWorkflowID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ahq *AgentHandoffQuery) GroupBy(field string, fields ...string) *AgentHandoffGroupBy {
	ahq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentHandoffGroupBy{build: ahq}
	grbuild.flds = &ahq.ctx.Fields
	grbuild.label = agenthandoff.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WorkflowID string `json:"workflow_id,omitempty"`
//	}
//
//	client.AgentHandoff.Query().
//		Select(agenthandoff.FieldWorkflowID).
//		Scan(ctx, &v)
func (ahq *AgentHandoffQuery) Select(fields ...string) *AgentHandoffSelect {
	ahq.ctx.Fields = append(ahq.ctx.Fields, fields...)
	sbuild := &AgentHandoffSelect{AgentHandoffQuery: ahq}
	sbuild.label = agenthandoff.Label
	sbuild.flds, sbuild.scan = &ahq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentHandoffSelect configured with the given aggregations.
func (ahq *AgentHandoffQuery) Aggregate(fns ...AggregateFunc) *AgentHandoffSelect {
	return ahq.Select().Aggregate(fns...)
}

func (ahq *AgentHandoffQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ahq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ahq); err != nil {
				return err
			}
		}
	}
	for _, f := range ahq.ctx.Fields {
		if !agenthandoff.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ahq.path != nil {
		prev, err := ahq.path(ctx)
		if err != nil {
			return err
		}
		ahq.sql = prev
	}
	return nil
}

func (ahq *AgentHandoffQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgentHandoff, error) {
	var (
		nodes       = []*AgentHandoff{}
		_spec       = ahq.querySpec()
		loadedTypes = [1]bool{
			ahq.withWorkflow != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgentHandoff).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgentHandoff{config: ahq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ahq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ahq.withWorkflow; query != nil {
		if err := ahq.loadWorkflow(ctx, query, nodes, nil,
			func(n *AgentHandoff, e *Workflow) { n.Edges.Workflow = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ahq *AgentHandoffQuery) loadWorkflow(ctx context.Context, query *WorkflowQuery, nodes []*AgentHandoff, init func(*AgentHandoff), assign func(*AgentHandoff, *Workflow)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*AgentHandoff)
	for i := range nodes {
		fk := nodes[i].WorkflowID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workflow.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workflow_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ahq *AgentHandoffQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ahq.querySpec()
	_spec.Node.Columns = ahq.ctx.Fields
	if len(ahq.ctx.Fields) > 0 {
		_spec.Unique = ahq.ctx.Unique != nil && *ahq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ahq.driver, _spec)
}

func (ahq *AgentHandoffQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agenthandoff.Table, agenthandoff.Columns, sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString))
	_spec.From = ahq.sql
	if unique := ahq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ahq.path != nil {
		_spec.Unique = true
	}
	if fields := ahq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenthandoff.FieldID)
		for i := range fields {
			if fields[i] != agenthandoff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ahq.withWorkflow != nil {
			_spec.Node.AddColumnOnce(agenthandoff.FieldWorkflowID)
		}
	}
	if ps := ahq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ahq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ahq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ahq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ahq *AgentHandoffQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ahq.driver.Dialect())
	t1 := builder.Table(agenthandoff.Table)
	columns := ahq.ctx.Fields
	if len(columns) == 0 {
		columns = agenthandoff.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ahq.sql != nil {
		selector = ahq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ahq.ctx.Unique != nil && *ahq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ahq.predicates {
		p(selector)
	}
	for _, p := range ahq.order {
		p(selector)
	}
	if offset := ahq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ahq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgentHandoffGroupBy is the group-by builder for AgentHandoff entities.
type AgentHandoffGroupBy struct {
	selector
	build *AgentHandoffQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ahgb *AgentHandoffGroupBy) Aggregate(fns ...AggregateFunc) *AgentHandoffGroupBy {
	ahgb.fns = append(ahgb.fns, fns...)
	return ahgb
}

// Scan applies the selector query and scans the result into the given value.
func (ahgb *AgentHandoffGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ahgb.build.ctx, ent.OpQueryGroupBy)
	if err := ahgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentHandoffQuery, *AgentHandoffGroupBy](ctx, ahgb.build, ahgb, ahgb.build.inters, v)
}

func (ahgb *AgentHandoffGroupBy) sqlScan(ctx context.Context, root *AgentHandoffQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ahgb.fns))
	for _, fn := range ahgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ahgb.flds)+len(ahgb.fns))
		for _, f := range *ahgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ahgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ahgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentHandoffSelect is the builder for selecting fields of AgentHandoff entities.
type AgentHandoffSelect struct {
	*AgentHandoffQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ahs *AgentHandoffSelect) Aggregate(fns ...AggregateFunc) *AgentHandoffSelect {
	ahs.fns = append(ahs.fns, fns...)
	return ahs
}

// Scan applies the selector query and scans the result into the given value.
func (ahs *AgentHandoffSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ahs.ctx, ent.OpQuerySelect)
	if err := ahs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentHandoffQuery, *AgentHandoffSelect](ctx, ahs.AgentHandoffQuery, ahs, ahs.inters, v)
}

func (ahs *AgentHandoffSelect) sqlScan(ctx context.Context, root *AgentHandoffQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ahs.fns))
	for _, fn := range ahs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ahs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ahs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
