// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
)

// AgentHandoffDelete is the builder for deleting a AgentHandoff entity.
type AgentHandoffDelete struct {
	config
	hooks    []Hook
	mutation *AgentHandoffMutation
}

// Where appends a list predicates to the AgentHandoffDelete builder.
func (ahd *AgentHandoffDelete) Where(ps ...predicate.AgentHandoff) *AgentHandoffDelete {
	ahd.mutation.Where(ps...)
	return ahd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ahd *AgentHandoffDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ahd.sqlExec, ahd.mutation, ahd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ahd *AgentHandoffDelete) ExecX(ctx context.Context) int {
	n, err := ahd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ahd *AgentHandoffDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(agenthandoff.Table, sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString))
	if ps := ahd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ahd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ahd.mutation.done = true
	return affected, err
}

// AgentHandoffDeleteOne is the builder for deleting a single AgentHandoff entity.
type AgentHandoffDeleteOne struct {
	ahd *AgentHandoffDelete
}

// Where appends a list predicates to the AgentHandoffDelete builder.
func (ahdo *AgentHandoffDeleteOne) Where(ps ...predicate.AgentHandoff) *AgentHandoffDeleteOne {
	ahdo.ahd.mutation.Where(ps...)
	return ahdo
}

// Exec executes the deletion query.
func (ahdo *AgentHandoffDeleteOne) Exec(ctx context.Context) error {
	n, err := ahdo.ahd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{agenthandoff.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ahdo *AgentHandoffDeleteOne) ExecX(ctx context.Context) {
	if err := ahdo.Exec(ctx); err != nil {
		panic(err)
	}
}
