// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentHandoffCreate is the builder for creating a AgentHandoff entity.
type AgentHandoffCreate struct {
	config
	mutation *AgentHandoffMutation
	hooks    []Hook
}

// SetWorkflowID sets the "workflow_id" field.
func (ahc *AgentHandoffCreate) SetWorkflowID(s string) *AgentHandoffCreate {
	ahc.mutation.SetWorkflowID(s)
	return ahc
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableWorkflowID(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetWorkflowID(*s)
	}
	return ahc
}

// SetFromAgentID sets the "from_agent_id" field.
func (ahc *AgentHandoffCreate) SetFromAgentID(s string) *AgentHandoffCreate {
	ahc.mutation.SetFromAgentID(s)
	return ahc
}

// SetFromAgentType sets the "from_agent_type" field.
func (ahc *AgentHandoffCreate) SetFromAgentType(s string) *AgentHandoffCreate {
	ahc.mutation.SetFromAgentType(s)
	return ahc
}

// SetNillableFromAgentType sets the "from_agent_type" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableFromAgentType(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetFromAgentType(*s)
	}
	return ahc
}

// SetToAgentID sets the "to_agent_id" field.
func (ahc *AgentHandoffCreate) SetToAgentID(s string) *AgentHandoffCreate {
	ahc.mutation.SetToAgentID(s)
	return ahc
}

// SetToAgentType sets the "to_agent_type" field.
func (ahc *AgentHandoffCreate) SetToAgentType(s string) *AgentHandoffCreate {
	ahc.mutation.SetToAgentType(s)
	return ahc
}

// SetNillableToAgentType sets the "to_agent_type" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableToAgentType(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetToAgentType(*s)
	}
	return ahc
}

// SetHandoffType sets the "handoff_type" field.
func (ahc *AgentHandoffCreate) SetHandoffType(s string) *AgentHandoffCreate {
	ahc.mutation.SetHandoffType(s)
	return ahc
}

// SetNillableHandoffType sets the "handoff_type" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableHandoffType(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetHandoffType(*s)
	}
	return ahc
}

// SetStatus sets the "status" field.
func (ahc *AgentHandoffCreate) SetStatus(s string) *AgentHandoffCreate {
	ahc.mutation.SetStatus(s)
	return ahc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableStatus(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetStatus(*s)
	}
	return ahc
}

// SetTraceID sets the "trace_id" field.
func (ahc *AgentHandoffCreate) SetTraceID(s string) *AgentHandoffCreate {
	ahc.mutation.SetTraceID(s)
	return ahc
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableTraceID(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetTraceID(*s)
	}
	return ahc
}

// SetFromTaskID sets the "from_task_id" field.
func (ahc *AgentHandoffCreate) SetFromTaskID(s string) *AgentHandoffCreate {
	ahc.mutation.SetFromTaskID(s)
	return ahc
}

// SetNillableFromTaskID sets the "from_task_id" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableFromTaskID(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetFromTaskID(*s)
	}
	return ahc
}

// SetToTaskID sets the "to_task_id" field.
func (ahc *AgentHandoffCreate) SetToTaskID(s string) *AgentHandoffCreate {
	ahc.mutation.SetToTaskID(s)
	return ahc
}

// SetNillableToTaskID sets the "to_task_id" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableToTaskID(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetToTaskID(*s)
	}
	return ahc
}

// SetPayload sets the "payload" field.
func (ahc *AgentHandoffCreate) SetPayload(m map[string]interface{}) *AgentHandoffCreate {
	ahc.mutation.SetPayload(m)
	return ahc
}

// SetMetadata sets the "metadata" field.
func (ahc *AgentHandoffCreate) SetMetadata(m map[string]interface{}) *AgentHandoffCreate {
	ahc.mutation.SetMetadata(m)
	return ahc
}

// SetPayloadSizeBytes sets the "payload_size_bytes" field.
func (ahc *AgentHandoffCreate) SetPayloadSizeBytes(i int) *AgentHandoffCreate {
	ahc.mutation.SetPayloadSizeBytes(i)
	return ahc
}

// SetNillablePayloadSizeBytes sets the "payload_size_bytes" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillablePayloadSizeBytes(i *int) *AgentHandoffCreate {
	if i != nil {
		ahc.SetPayloadSizeBytes(*i)
	}
	return ahc
}

// SetLatencyMs sets the "latency_ms" field.
func (ahc *AgentHandoffCreate) SetLatencyMs(i int64) *AgentHandoffCreate {
	ahc.mutation.SetLatencyMs(i)
	return ahc
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableLatencyMs(i *int64) *AgentHandoffCreate {
	if i != nil {
		ahc.SetLatencyMs(*i)
	}
	return ahc
}

// SetErrorMessage sets the "error_message" field.
func (ahc *AgentHandoffCreate) SetErrorMessage(s string) *AgentHandoffCreate {
	ahc.mutation.SetErrorMessage(s)
	return ahc
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableErrorMessage(s *string) *AgentHandoffCreate {
	if s != nil {
		ahc.SetErrorMessage(*s)
	}
	return ahc
}

// SetInitiatedAt sets the "initiated_at" field.
func (ahc *AgentHandoffCreate) SetInitiatedAt(t time.Time) *AgentHandoffCreate {
	ahc.mutation.SetInitiatedAt(t)
	return ahc
}

// SetNillableInitiatedAt sets the "initiated_at" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableInitiatedAt(t *time.Time) *AgentHandoffCreate {
	if t != nil {
		ahc.SetInitiatedAt(*t)
	}
	return ahc
}

// SetAcceptedAt sets the "accepted_at" field.
func (ahc *AgentHandoffCreate) SetAcceptedAt(t time.Time) *AgentHandoffCreate {
	ahc.mutation.SetAcceptedAt(t)
	return ahc
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableAcceptedAt(t *time.Time) *AgentHandoffCreate {
	if t != nil {
		ahc.SetAcceptedAt(*t)
	}
	return ahc
}

// SetCompletedAt sets the "completed_at" field.
func (ahc *AgentHandoffCreate) SetCompletedAt(t time.Time) *AgentHandoffCreate {
	ahc.mutation.SetCompletedAt(t)
	return ahc
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableCompletedAt(t *time.Time) *AgentHandoffCreate {
	if t != nil {
		ahc.SetCompletedAt(*t)
	}
	return ahc
}

// SetCreatedAt sets the "created_at" field.
func (ahc *AgentHandoffCreate) SetCreatedAt(t time.Time) *AgentHandoffCreate {
	ahc.mutation.SetCreatedAt(t)
	return ahc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableCreatedAt(t *time.Time) *AgentHandoffCreate {
	if t != nil {
		ahc.SetCreatedAt(*t)
	}
	return ahc
}

// SetUpdatedAt sets the "updated_at" field.
func (ahc *AgentHandoffCreate) SetUpdatedAt(t time.Time) *AgentHandoffCreate {
	ahc.mutation.SetUpdatedAt(t)
	return ahc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ahc *AgentHandoffCreate) SetNillableUpdatedAt(t *time.Time) *AgentHandoffCreate {
	if t != nil {
		ahc.SetUpdatedAt(*t)
	}
	return ahc
}

// SetID sets the "id" field.
func (ahc *AgentHandoffCreate) SetID(s string) *AgentHandoffCreate {
	ahc.mutation.SetID(s)
	return ahc
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (ahc *AgentHandoffCreate) SetWorkflow(w *Workflow) *AgentHandoffCreate {
	return ahc.SetWorkflowID(w.ID)
}

// Mutation returns the AgentHandoffMutation object of the builder.
func (ahc *AgentHandoffCreate) Mutation() *AgentHandoffMutation {
	return ahc.mutation
}

// Save creates the AgentHandoff in the database.
func (ahc *AgentHandoffCreate) Save(ctx context.Context) (*AgentHandoff, error) {
	ahc.defaults()
	return withHooks(ctx, ahc.sqlSave, ahc.mutation, ahc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ahc *AgentHandoffCreate) SaveX(ctx context.Context) *AgentHandoff {
	v, err := ahc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ahc *AgentHandoffCreate) Exec(ctx context.Context) error {
	_, err := ahc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahc *AgentHandoffCreate) ExecX(ctx context.Context) {
	if err := ahc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ahc *AgentHandoffCreate) defaults() {
	if _, ok := ahc.mutation.HandoffType(); !ok {
		v := agenthandoff.DefaultHandoffType
		ahc.mutation.SetHandoffType(v)
	}
	if _, ok := ahc.mutation.Status(); !ok {
		v := agenthandoff.DefaultStatus
		ahc.mutation.SetStatus(v)
	}
	if _, ok := ahc.mutation.PayloadSizeBytes(); !ok {
		v := agenthandoff.DefaultPayloadSizeBytes
		ahc.mutation.SetPayloadSizeBytes(v)
	}
	if _, ok := ahc.mutation.InitiatedAt(); !ok {
		v := agenthandoff.DefaultInitiatedAt()
		ahc.mutation.SetInitiatedAt(v)
	}
	if _, ok := ahc.mutation.CreatedAt(); !ok {
		v := agenthandoff.DefaultCreatedAt()
		ahc.mutation.SetCreatedAt(v)
	}
	if _, ok := ahc.mutation.UpdatedAt(); !ok {
		v := agenthandoff.DefaultUpdatedAt()
		ahc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ahc *AgentHandoffCreate) check() error {
	if _, ok := ahc.mutation.FromAgentID(); !ok {
		return &ValidationError{Name: "from_agent_id", err: errors.New(`ent: missing required field "AgentHandoff.from_agent_id"`)}
	}
	if v, ok := ahc.mutation.FromAgentID(); ok {
		if err := agenthandoff.FromAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "from_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.from_agent_id": %w`, err)}
		}
	}
	if _, ok := ahc.mutation.ToAgentID(); !ok {
		return &ValidationError{Name: "to_agent_id", err: errors.New(`ent: missing required field "AgentHandoff.to_agent_id"`)}
	}
	if v, ok := ahc.mutation.ToAgentID(); ok {
		if err := agenthandoff.ToAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "to_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.to_agent_id": %w`, err)}
		}
	}
	if _, ok := ahc.mutation.HandoffType(); !ok {
		return &ValidationError{Name: "handoff_type", err: errors.New(`ent: missing required field "AgentHandoff.handoff_type"`)}
	}
	if _, ok := ahc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentHandoff.status"`)}
	}
	if _, ok := ahc.mutation.PayloadSizeBytes(); !ok {
		return &ValidationError{Name: "payload_size_bytes", err: errors.New(`ent: missing required field "AgentHandoff.payload_size_bytes"`)}
	}
	if _, ok := ahc.mutation.InitiatedAt(); !ok {
		return &ValidationError{Name: "initiated_at", err: errors.New(`ent: missing required field "AgentHandoff.initiated_at"`)}
	}
	if _, ok := ahc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentHandoff.created_at"`)}
	}
	if _, ok := ahc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentHandoff.updated_at"`)}
	}
	return nil
}

func (ahc *AgentHandoffCreate) sqlSave(ctx context.Context) (*AgentHandoff, error) {
	if err := ahc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ahc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ahc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentHandoff.ID type: %T", _spec.ID.Value)
		}
	}
	ahc.mutation.id = &_node.ID
	ahc.mutation.done = true
	return _node, nil
}

func (ahc *AgentHandoffCreate) createSpec() (*AgentHandoff, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentHandoff{config: ahc.config}
		_spec = sqlgraph.NewCreateSpec(agenthandoff.Table, sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString))
	)
	if id, ok := ahc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ahc.mutation.FromAgentID(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentID, field.TypeString, value)
		_node.FromAgentID = value
	}
	if value, ok := ahc.mutation.FromAgentType(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentType, field.TypeString, value)
		_node.FromAgentType = value
	}
	if value, ok := ahc.mutation.ToAgentID(); ok {
		_spec.SetField(agenthandoff.FieldToAgentID, field.TypeString, value)
		_node.ToAgentID = value
	}
	if value, ok := ahc.mutation.ToAgentType(); ok {
		_spec.SetField(agenthandoff.FieldToAgentType, field.TypeString, value)
		_node.ToAgentType = value
	}
	if value, ok := ahc.mutation.HandoffType(); ok {
		_spec.SetField(agenthandoff.FieldHandoffType, field.TypeString, value)
		_node.HandoffType = value
	}
	if value, ok := ahc.mutation.Status(); ok {
		_spec.SetField(agenthandoff.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := ahc.mutation.TraceID(); ok {
		_spec.SetField(agenthandoff.FieldTraceID, field.TypeString, value)
		_node.TraceID = value
	}
	if value, ok := ahc.mutation.FromTaskID(); ok {
		_spec.SetField(agenthandoff.FieldFromTaskID, field.TypeString, value)
		_node.FromTaskID = value
	}
	if value, ok := ahc.mutation.ToTaskID(); ok {
		_spec.SetField(agenthandoff.FieldToTaskID, field.TypeString, value)
		_node.ToTaskID = value
	}
	if value, ok := ahc.mutation.Payload(); ok {
		_spec.SetField(agenthandoff.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := ahc.mutation.Metadata(); ok {
		_spec.SetField(agenthandoff.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := ahc.mutation.PayloadSizeBytes(); ok {
		_spec.SetField(agenthandoff.FieldPayloadSizeBytes, field.TypeInt, value)
		_node.PayloadSizeBytes = value
	}
	if value, ok := ahc.mutation.LatencyMs(); ok {
		_spec.SetField(agenthandoff.FieldLatencyMs, field.TypeInt64, value)
		_node.LatencyMs = value
	}
	if value, ok := ahc.mutation.ErrorMessage(); ok {
		_spec.SetField(agenthandoff.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := ahc.mutation.InitiatedAt(); ok {
		_spec.SetField(agenthandoff.FieldInitiatedAt, field.TypeTime, value)
		_node.InitiatedAt = value
	}
	if value, ok := ahc.mutation.AcceptedAt(); ok {
		_spec.SetField(agenthandoff.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := ahc.mutation.CompletedAt(); ok {
		_spec.SetField(agenthandoff.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := ahc.mutation.CreatedAt(); ok {
		_spec.SetField(agenthandoff.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ahc.mutation.UpdatedAt(); ok {
		_spec.SetField(agenthandoff.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := ahc.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenthandoff.WorkflowTable,
			Columns: []string{agenthandoff.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkflowID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentHandoffCreateBulk is the builder for creating many AgentHandoff entities in bulk.
type AgentHandoffCreateBulk struct {
	config
	err      error
	builders []*AgentHandoffCreate
}

// Save creates the AgentHandoff entities in the database.
func (ahcb *AgentHandoffCreateBulk) Save(ctx context.Context) ([]*AgentHandoff, error) {
	if ahcb.err != nil {
		return nil, ahcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ahcb.builders))
	nodes := make([]*AgentHandoff, len(ahcb.builders))
	mutators := make([]Mutator, len(ahcb.builders))
	for i := range ahcb.builders {
		func(i int, root context.Context) {
			builder := ahcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentHandoffMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ahcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ahcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ahcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ahcb *AgentHandoffCreateBulk) SaveX(ctx context.Context) []*AgentHandoff {
	v, err := ahcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ahcb *AgentHandoffCreateBulk) Exec(ctx context.Context) error {
	_, err := ahcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahcb *AgentHandoffCreateBulk) ExecX(ctx context.Context) {
	if err := ahcb.Exec(ctx); err != nil {
		panic(err)
	}
}
