// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// AgentHandoffUpdate is the builder for updating AgentHandoff entities.
type AgentHandoffUpdate struct {
	config
	hooks    []Hook
	mutation *AgentHandoffMutation
}

// Where appends a list predicates to the AgentHandoffUpdate builder.
func (ahu *AgentHandoffUpdate) Where(ps ...predicate.AgentHandoff) *AgentHandoffUpdate {
	ahu.mutation.Where(ps...)
	return ahu
}

// SetWorkflowID sets the "workflow_id" field.
func (ahu *AgentHandoffUpdate) SetWorkflowID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetWorkflowID(s)
	return ahu
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableWorkflowID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetWorkflowID(*s)
	}
	return ahu
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (ahu *AgentHandoffUpdate) ClearWorkflowID() *AgentHandoffUpdate {
	ahu.mutation.ClearWorkflowID()
	return ahu
}

// SetFromAgentID sets the "from_agent_id" field.
func (ahu *AgentHandoffUpdate) SetFromAgentID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetFromAgentID(s)
	return ahu
}

// SetNillableFromAgentID sets the "from_agent_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableFromAgentID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetFromAgentID(*s)
	}
	return ahu
}

// SetFromAgentType sets the "from_agent_type" field.
func (ahu *AgentHandoffUpdate) SetFromAgentType(s string) *AgentHandoffUpdate {
	ahu.mutation.SetFromAgentType(s)
	return ahu
}

// SetNillableFromAgentType sets the "from_agent_type" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableFromAgentType(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetFromAgentType(*s)
	}
	return ahu
}

// ClearFromAgentType clears the value of the "from_agent_type" field.
func (ahu *AgentHandoffUpdate) ClearFromAgentType() *AgentHandoffUpdate {
	ahu.mutation.ClearFromAgentType()
	return ahu
}

// SetToAgentID sets the "to_agent_id" field.
func (ahu *AgentHandoffUpdate) SetToAgentID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetToAgentID(s)
	return ahu
}

// SetNillableToAgentID sets the "to_agent_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableToAgentID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetToAgentID(*s)
	}
	return ahu
}

// SetToAgentType sets the "to_agent_type" field.
func (ahu *AgentHandoffUpdate) SetToAgentType(s string) *AgentHandoffUpdate {
	ahu.mutation.SetToAgentType(s)
	return ahu
}

// SetNillableToAgentType sets the "to_agent_type" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableToAgentType(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetToAgentType(*s)
	}
	return ahu
}

// ClearToAgentType clears the value of the "to_agent_type" field.
func (ahu *AgentHandoffUpdate) ClearToAgentType() *AgentHandoffUpdate {
	ahu.mutation.ClearToAgentType()
	return ahu
}

// SetHandoffType sets the "handoff_type" field.
func (ahu *AgentHandoffUpdate) SetHandoffType(s string) *AgentHandoffUpdate {
	ahu.mutation.SetHandoffType(s)
	return ahu
}

// SetNillableHandoffType sets the "handoff_type" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableHandoffType(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetHandoffType(*s)
	}
	return ahu
}

// SetStatus sets the "status" field.
func (ahu *AgentHandoffUpdate) SetStatus(s string) *AgentHandoffUpdate {
	ahu.mutation.SetStatus(s)
	return ahu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableStatus(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetStatus(*s)
	}
	return ahu
}

// SetTraceID sets the "trace_id" field.
func (ahu *AgentHandoffUpdate) SetTraceID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetTraceID(s)
	return ahu
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableTraceID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetTraceID(*s)
	}
	return ahu
}

// ClearTraceID clears the value of the "trace_id" field.
func (ahu *AgentHandoffUpdate) ClearTraceID() *AgentHandoffUpdate {
	ahu.mutation.ClearTraceID()
	return ahu
}

// SetFromTaskID sets the "from_task_id" field.
func (ahu *AgentHandoffUpdate) SetFromTaskID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetFromTaskID(s)
	return ahu
}

// SetNillableFromTaskID sets the "from_task_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableFromTaskID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetFromTaskID(*s)
	}
	return ahu
}

// ClearFromTaskID clears the value of the "from_task_id" field.
func (ahu *AgentHandoffUpdate) ClearFromTaskID() *AgentHandoffUpdate {
	ahu.mutation.ClearFromTaskID()
	return ahu
}

// SetToTaskID sets the "to_task_id" field.
func (ahu *AgentHandoffUpdate) SetToTaskID(s string) *AgentHandoffUpdate {
	ahu.mutation.SetToTaskID(s)
	return ahu
}

// SetNillableToTaskID sets the "to_task_id" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableToTaskID(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetToTaskID(*s)
	}
	return ahu
}

// ClearToTaskID clears the value of the "to_task_id" field.
func (ahu *AgentHandoffUpdate) ClearToTaskID() *AgentHandoffUpdate {
	ahu.mutation.ClearToTaskID()
	return ahu
}

// SetPayload sets the "payload" field.
func (ahu *AgentHandoffUpdate) SetPayload(m map[string]interface{}) *AgentHandoffUpdate {
	ahu.mutation.SetPayload(m)
	return ahu
}

// ClearPayload clears the value of the "payload" field.
func (ahu *AgentHandoffUpdate) ClearPayload() *AgentHandoffUpdate {
	ahu.mutation.ClearPayload()
	return ahu
}

// SetMetadata sets the "metadata" field.
func (ahu *AgentHandoffUpdate) SetMetadata(m map[string]interface{}) *AgentHandoffUpdate {
	ahu.mutation.SetMetadata(m)
	return ahu
}

// ClearMetadata clears the value of the "metadata" field.
func (ahu *AgentHandoffUpdate) ClearMetadata() *AgentHandoffUpdate {
	ahu.mutation.ClearMetadata()
	return ahu
}

// SetPayloadSizeBytes sets the "payload_size_bytes" field.
func (ahu *AgentHandoffUpdate) SetPayloadSizeBytes(i int) *AgentHandoffUpdate {
	ahu.mutation.ResetPayloadSizeBytes()
	ahu.mutation.SetPayloadSizeBytes(i)
	return ahu
}

// SetNillablePayloadSizeBytes sets the "payload_size_bytes" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillablePayloadSizeBytes(i *int) *AgentHandoffUpdate {
	if i != nil {
		ahu.SetPayloadSizeBytes(*i)
	}
	return ahu
}

// AddPayloadSizeBytes adds i to the "payload_size_bytes" field.
func (ahu *AgentHandoffUpdate) AddPayloadSizeBytes(i int) *AgentHandoffUpdate {
	ahu.mutation.AddPayloadSizeBytes(i)
	return ahu
}

// SetLatencyMs sets the "latency_ms" field.
func (ahu *AgentHandoffUpdate) SetLatencyMs(i int64) *AgentHandoffUpdate {
	ahu.mutation.ResetLatencyMs()
	ahu.mutation.SetLatencyMs(i)
	return ahu
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableLatencyMs(i *int64) *AgentHandoffUpdate {
	if i != nil {
		ahu.SetLatencyMs(*i)
	}
	return ahu
}

// AddLatencyMs adds i to the "latency_ms" field.
func (ahu *AgentHandoffUpdate) AddLatencyMs(i int64) *AgentHandoffUpdate {
	ahu.mutation.AddLatencyMs(i)
	return ahu
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (ahu *AgentHandoffUpdate) ClearLatencyMs() *AgentHandoffUpdate {
	ahu.mutation.ClearLatencyMs()
	return ahu
}

// SetErrorMessage sets the "error_message" field.
func (ahu *AgentHandoffUpdate) SetErrorMessage(s string) *AgentHandoffUpdate {
	ahu.mutation.SetErrorMessage(s)
	return ahu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableErrorMessage(s *string) *AgentHandoffUpdate {
	if s != nil {
		ahu.SetErrorMessage(*s)
	}
	return ahu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (ahu *AgentHandoffUpdate) ClearErrorMessage() *AgentHandoffUpdate {
	ahu.mutation.ClearErrorMessage()
	return ahu
}

// SetAcceptedAt sets the "accepted_at" field.
func (ahu *AgentHandoffUpdate) SetAcceptedAt(t time.Time) *AgentHandoffUpdate {
	ahu.mutation.SetAcceptedAt(t)
	return ahu
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableAcceptedAt(t *time.Time) *AgentHandoffUpdate {
	if t != nil {
		ahu.SetAcceptedAt(*t)
	}
	return ahu
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (ahu *AgentHandoffUpdate) ClearAcceptedAt() *AgentHandoffUpdate {
	ahu.mutation.ClearAcceptedAt()
	return ahu
}

// SetCompletedAt sets the "completed_at" field.
func (ahu *AgentHandoffUpdate) SetCompletedAt(t time.Time) *AgentHandoffUpdate {
	ahu.mutation.SetCompletedAt(t)
	return ahu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ahu *AgentHandoffUpdate) SetNillableCompletedAt(t *time.Time) *AgentHandoffUpdate {
	if t != nil {
		ahu.SetCompletedAt(*t)
	}
	return ahu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (ahu *AgentHandoffUpdate) ClearCompletedAt() *AgentHandoffUpdate {
	ahu.mutation.ClearCompletedAt()
	return ahu
}

// SetUpdatedAt sets the "updated_at" field.
func (ahu *AgentHandoffUpdate) SetUpdatedAt(t time.Time) *AgentHandoffUpdate {
	ahu.mutation.SetUpdatedAt(t)
	return ahu
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (ahu *AgentHandoffUpdate) SetWorkflow(w *Workflow) *AgentHandoffUpdate {
	return ahu.SetWorkflowID(w.ID)
}

// Mutation returns the AgentHandoffMutation object of the builder.
func (ahu *AgentHandoffUpdate) Mutation() *AgentHandoffMutation {
	return ahu.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (ahu *AgentHandoffUpdate) ClearWorkflow() *AgentHandoffUpdate {
	ahu.mutation.ClearWorkflow()
	return ahu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ahu *AgentHandoffUpdate) Save(ctx context.Context) (int, error) {
	ahu.defaults()
	return withHooks(ctx, ahu.sqlSave, ahu.mutation, ahu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ahu *AgentHandoffUpdate) SaveX(ctx context.Context) int {
	affected, err := ahu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ahu *AgentHandoffUpdate) Exec(ctx context.Context) error {
	_, err := ahu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahu *AgentHandoffUpdate) ExecX(ctx context.Context) {
	if err := ahu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ahu *AgentHandoffUpdate) defaults() {
	if _, ok := ahu.mutation.UpdatedAt(); !ok {
		v := agenthandoff.UpdateDefaultUpdatedAt()
		ahu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ahu *AgentHandoffUpdate) check() error {
	if v, ok := ahu.mutation.FromAgentID(); ok {
		if err := agenthandoff.FromAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "from_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.from_agent_id": %w`, err)}
		}
	}
	if v, ok := ahu.mutation.ToAgentID(); ok {
		if err := agenthandoff.ToAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "to_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.to_agent_id": %w`, err)}
		}
	}
	return nil
}

func (ahu *AgentHandoffUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ahu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenthandoff.Table, agenthandoff.Columns, sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString))
	if ps := ahu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ahu.mutation.FromAgentID(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentID, field.TypeString, value)
	}
	if value, ok := ahu.mutation.FromAgentType(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentType, field.TypeString, value)
	}
	if ahu.mutation.FromAgentTypeCleared() {
		_spec.ClearField(agenthandoff.FieldFromAgentType, field.TypeString)
	}
	if value, ok := ahu.mutation.ToAgentID(); ok {
		_spec.SetField(agenthandoff.FieldToAgentID, field.TypeString, value)
	}
	if value, ok := ahu.mutation.ToAgentType(); ok {
		_spec.SetField(agenthandoff.FieldToAgentType, field.TypeString, value)
	}
	if ahu.mutation.ToAgentTypeCleared() {
		_spec.ClearField(agenthandoff.FieldToAgentType, field.TypeString)
	}
	if value, ok := ahu.mutation.HandoffType(); ok {
		_spec.SetField(agenthandoff.FieldHandoffType, field.TypeString, value)
	}
	if value, ok := ahu.mutation.Status(); ok {
		_spec.SetField(agenthandoff.FieldStatus, field.TypeString, value)
	}
	if value, ok := ahu.mutation.TraceID(); ok {
		_spec.SetField(agenthandoff.FieldTraceID, field.TypeString, value)
	}
	if ahu.mutation.TraceIDCleared() {
		_spec.ClearField(agenthandoff.FieldTraceID, field.TypeString)
	}
	if value, ok := ahu.mutation.FromTaskID(); ok {
		_spec.SetField(agenthandoff.FieldFromTaskID, field.TypeString, value)
	}
	if ahu.mutation.FromTaskIDCleared() {
		_spec.ClearField(agenthandoff.FieldFromTaskID, field.TypeString)
	}
	if value, ok := ahu.mutation.ToTaskID(); ok {
		_spec.SetField(agenthandoff.FieldToTaskID, field.TypeString, value)
	}
	if ahu.mutation.ToTaskIDCleared() {
		_spec.ClearField(agenthandoff.FieldToTaskID, field.TypeString)
	}
	if value, ok := ahu.mutation.Payload(); ok {
		_spec.SetField(agenthandoff.FieldPayload, field.TypeJSON, value)
	}
	if ahu.mutation.PayloadCleared() {
		_spec.ClearField(agenthandoff.FieldPayload, field.TypeJSON)
	}
	if value, ok := ahu.mutation.Metadata(); ok {
		_spec.SetField(agenthandoff.FieldMetadata, field.TypeJSON, value)
	}
	if ahu.mutation.MetadataCleared() {
		_spec.ClearField(agenthandoff.FieldMetadata, field.TypeJSON)
	}
	if value, ok := ahu.mutation.PayloadSizeBytes(); ok {
		_spec.SetField(agenthandoff.FieldPayloadSizeBytes, field.TypeInt, value)
	}
	if value, ok := ahu.mutation.AddedPayloadSizeBytes(); ok {
		_spec.AddField(agenthandoff.FieldPayloadSizeBytes, field.TypeInt, value)
	}
	if value, ok := ahu.mutation.LatencyMs(); ok {
		_spec.SetField(agenthandoff.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := ahu.mutation.AddedLatencyMs(); ok {
		_spec.AddField(agenthandoff.FieldLatencyMs, field.TypeInt64, value)
	}
	if ahu.mutation.LatencyMsCleared() {
		_spec.ClearField(agenthandoff.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := ahu.mutation.ErrorMessage(); ok {
		_spec.SetField(agenthandoff.FieldErrorMessage, field.TypeString, value)
	}
	if ahu.mutation.ErrorMessageCleared() {
		_spec.ClearField(agenthandoff.FieldErrorMessage, field.TypeString)
	}
	if value, ok := ahu.mutation.AcceptedAt(); ok {
		_spec.SetField(agenthandoff.FieldAcceptedAt, field.TypeTime, value)
	}
	if ahu.mutation.AcceptedAtCleared() {
		_spec.ClearField(agenthandoff.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := ahu.mutation.CompletedAt(); ok {
		_spec.SetField(agenthandoff.FieldCompletedAt, field.TypeTime, value)
	}
	if ahu.mutation.CompletedAtCleared() {
		_spec.ClearField(agenthandoff.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := ahu.mutation.UpdatedAt(); ok {
		_spec.SetField(agenthandoff.FieldUpdatedAt, field.TypeTime, value)
	}
	if ahu.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenthandoff.WorkflowTable,
			Columns: []string{agenthandoff.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ahu.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenthandoff.WorkflowTable,
			Columns: []string{agenthandoff.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ahu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenthandoff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ahu.mutation.done = true
	return n, nil
}

// AgentHandoffUpdateOne is the builder for updating a single AgentHandoff entity.
type AgentHandoffUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentHandoffMutation
}

// SetWorkflowID sets the "workflow_id" field.
func (ahuo *AgentHandoffUpdateOne) SetWorkflowID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetWorkflowID(s)
	return ahuo
}

// SetNillableWorkflowID sets the "workflow_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableWorkflowID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetWorkflowID(*s)
	}
	return ahuo
}

// ClearWorkflowID clears the value of the "workflow_id" field.
func (ahuo *AgentHandoffUpdateOne) ClearWorkflowID() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearWorkflowID()
	return ahuo
}

// SetFromAgentID sets the "from_agent_id" field.
func (ahuo *AgentHandoffUpdateOne) SetFromAgentID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetFromAgentID(s)
	return ahuo
}

// SetNillableFromAgentID sets the "from_agent_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableFromAgentID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetFromAgentID(*s)
	}
	return ahuo
}

// SetFromAgentType sets the "from_agent_type" field.
func (ahuo *AgentHandoffUpdateOne) SetFromAgentType(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetFromAgentType(s)
	return ahuo
}

// SetNillableFromAgentType sets the "from_agent_type" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableFromAgentType(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetFromAgentType(*s)
	}
	return ahuo
}

// ClearFromAgentType clears the value of the "from_agent_type" field.
func (ahuo *AgentHandoffUpdateOne) ClearFromAgentType() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearFromAgentType()
	return ahuo
}

// SetToAgentID sets the "to_agent_id" field.
func (ahuo *AgentHandoffUpdateOne) SetToAgentID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetToAgentID(s)
	return ahuo
}

// SetNillableToAgentID sets the "to_agent_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableToAgentID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetToAgentID(*s)
	}
	return ahuo
}

// SetToAgentType sets the "to_agent_type" field.
func (ahuo *AgentHandoffUpdateOne) SetToAgentType(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetToAgentType(s)
	return ahuo
}

// SetNillableToAgentType sets the "to_agent_type" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableToAgentType(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetToAgentType(*s)
	}
	return ahuo
}

// ClearToAgentType clears the value of the "to_agent_type" field.
func (ahuo *AgentHandoffUpdateOne) ClearToAgentType() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearToAgentType()
	return ahuo
}

// SetHandoffType sets the "handoff_type" field.
func (ahuo *AgentHandoffUpdateOne) SetHandoffType(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetHandoffType(s)
	return ahuo
}

// SetNillableHandoffType sets the "handoff_type" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableHandoffType(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetHandoffType(*s)
	}
	return ahuo
}

// SetStatus sets the "status" field.
func (ahuo *AgentHandoffUpdateOne) SetStatus(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetStatus(s)
	return ahuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableStatus(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetStatus(*s)
	}
	return ahuo
}

// SetTraceID sets the "trace_id" field.
func (ahuo *AgentHandoffUpdateOne) SetTraceID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetTraceID(s)
	return ahuo
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableTraceID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetTraceID(*s)
	}
	return ahuo
}

// ClearTraceID clears the value of the "trace_id" field.
func (ahuo *AgentHandoffUpdateOne) ClearTraceID() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearTraceID()
	return ahuo
}

// SetFromTaskID sets the "from_task_id" field.
func (ahuo *AgentHandoffUpdateOne) SetFromTaskID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetFromTaskID(s)
	return ahuo
}

// SetNillableFromTaskID sets the "from_task_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableFromTaskID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetFromTaskID(*s)
	}
	return ahuo
}

// ClearFromTaskID clears the value of the "from_task_id" field.
func (ahuo *AgentHandoffUpdateOne) ClearFromTaskID() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearFromTaskID()
	return ahuo
}

// SetToTaskID sets the "to_task_id" field.
func (ahuo *AgentHandoffUpdateOne) SetToTaskID(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetToTaskID(s)
	return ahuo
}

// SetNillableToTaskID sets the "to_task_id" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableToTaskID(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetToTaskID(*s)
	}
	return ahuo
}

// ClearToTaskID clears the value of the "to_task_id" field.
func (ahuo *AgentHandoffUpdateOne) ClearToTaskID() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearToTaskID()
	return ahuo
}

// SetPayload sets the "payload" field.
func (ahuo *AgentHandoffUpdateOne) SetPayload(m map[string]interface{}) *AgentHandoffUpdateOne {
	ahuo.mutation.SetPayload(m)
	return ahuo
}

// ClearPayload clears the value of the "payload" field.
func (ahuo *AgentHandoffUpdateOne) ClearPayload() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearPayload()
	return ahuo
}

// SetMetadata sets the "metadata" field.
func (ahuo *AgentHandoffUpdateOne) SetMetadata(m map[string]interface{}) *AgentHandoffUpdateOne {
	ahuo.mutation.SetMetadata(m)
	return ahuo
}

// ClearMetadata clears the value of the "metadata" field.
func (ahuo *AgentHandoffUpdateOne) ClearMetadata() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearMetadata()
	return ahuo
}

// SetPayloadSizeBytes sets the "payload_size_bytes" field.
func (ahuo *AgentHandoffUpdateOne) SetPayloadSizeBytes(i int) *AgentHandoffUpdateOne {
	ahuo.mutation.ResetPayloadSizeBytes()
	ahuo.mutation.SetPayloadSizeBytes(i)
	return ahuo
}

// SetNillablePayloadSizeBytes sets the "payload_size_bytes" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillablePayloadSizeBytes(i *int) *AgentHandoffUpdateOne {
	if i != nil {
		ahuo.SetPayloadSizeBytes(*i)
	}
	return ahuo
}

// AddPayloadSizeBytes adds i to the "payload_size_bytes" field.
func (ahuo *AgentHandoffUpdateOne) AddPayloadSizeBytes(i int) *AgentHandoffUpdateOne {
	ahuo.mutation.AddPayloadSizeBytes(i)
	return ahuo
}

// SetLatencyMs sets the "latency_ms" field.
func (ahuo *AgentHandoffUpdateOne) SetLatencyMs(i int64) *AgentHandoffUpdateOne {
	ahuo.mutation.ResetLatencyMs()
	ahuo.mutation.SetLatencyMs(i)
	return ahuo
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableLatencyMs(i *int64) *AgentHandoffUpdateOne {
	if i != nil {
		ahuo.SetLatencyMs(*i)
	}
	return ahuo
}

// AddLatencyMs adds i to the "latency_ms" field.
func (ahuo *AgentHandoffUpdateOne) AddLatencyMs(i int64) *AgentHandoffUpdateOne {
	ahuo.mutation.AddLatencyMs(i)
	return ahuo
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (ahuo *AgentHandoffUpdateOne) ClearLatencyMs() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearLatencyMs()
	return ahuo
}

// SetErrorMessage sets the "error_message" field.
func (ahuo *AgentHandoffUpdateOne) SetErrorMessage(s string) *AgentHandoffUpdateOne {
	ahuo.mutation.SetErrorMessage(s)
	return ahuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableErrorMessage(s *string) *AgentHandoffUpdateOne {
	if s != nil {
		ahuo.SetErrorMessage(*s)
	}
	return ahuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (ahuo *AgentHandoffUpdateOne) ClearErrorMessage() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearErrorMessage()
	return ahuo
}

// SetAcceptedAt sets the "accepted_at" field.
func (ahuo *AgentHandoffUpdateOne) SetAcceptedAt(t time.Time) *AgentHandoffUpdateOne {
	ahuo.mutation.SetAcceptedAt(t)
	return ahuo
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableAcceptedAt(t *time.Time) *AgentHandoffUpdateOne {
	if t != nil {
		ahuo.SetAcceptedAt(*t)
	}
	return ahuo
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (ahuo *AgentHandoffUpdateOne) ClearAcceptedAt() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearAcceptedAt()
	return ahuo
}

// SetCompletedAt sets the "completed_at" field.
func (ahuo *AgentHandoffUpdateOne) SetCompletedAt(t time.Time) *AgentHandoffUpdateOne {
	ahuo.mutation.SetCompletedAt(t)
	return ahuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (ahuo *AgentHandoffUpdateOne) SetNillableCompletedAt(t *time.Time) *AgentHandoffUpdateOne {
	if t != nil {
		ahuo.SetCompletedAt(*t)
	}
	return ahuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (ahuo *AgentHandoffUpdateOne) ClearCompletedAt() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearCompletedAt()
	return ahuo
}

// SetUpdatedAt sets the "updated_at" field.
func (ahuo *AgentHandoffUpdateOne) SetUpdatedAt(t time.Time) *AgentHandoffUpdateOne {
	ahuo.mutation.SetUpdatedAt(t)
	return ahuo
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (ahuo *AgentHandoffUpdateOne) SetWorkflow(w *Workflow) *AgentHandoffUpdateOne {
	return ahuo.SetWorkflowID(w.ID)
}

// Mutation returns the AgentHandoffMutation object of the builder.
func (ahuo *AgentHandoffUpdateOne) Mutation() *AgentHandoffMutation {
	return ahuo.mutation
}

// ClearWorkflow clears the "workflow" edge to the Workflow entity.
func (ahuo *AgentHandoffUpdateOne) ClearWorkflow() *AgentHandoffUpdateOne {
	ahuo.mutation.ClearWorkflow()
	return ahuo
}

// Where appends a list predicates to the AgentHandoffUpdate builder.
func (ahuo *AgentHandoffUpdateOne) Where(ps ...predicate.AgentHandoff) *AgentHandoffUpdateOne {
	ahuo.mutation.Where(ps...)
	return ahuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ahuo *AgentHandoffUpdateOne) Select(field string, fields ...string) *AgentHandoffUpdateOne {
	ahuo.fields = append([]string{field}, fields...)
	return ahuo
}

// Save executes the query and returns the updated AgentHandoff entity.
func (ahuo *AgentHandoffUpdateOne) Save(ctx context.Context) (*AgentHandoff, error) {
	ahuo.defaults()
	return withHooks(ctx, ahuo.sqlSave, ahuo.mutation, ahuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ahuo *AgentHandoffUpdateOne) SaveX(ctx context.Context) *AgentHandoff {
	node, err := ahuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ahuo *AgentHandoffUpdateOne) Exec(ctx context.Context) error {
	_, err := ahuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ahuo *AgentHandoffUpdateOne) ExecX(ctx context.Context) {
	if err := ahuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ahuo *AgentHandoffUpdateOne) defaults() {
	if _, ok := ahuo.mutation.UpdatedAt(); !ok {
		v := agenthandoff.UpdateDefaultUpdatedAt()
		ahuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ahuo *AgentHandoffUpdateOne) check() error {
	if v, ok := ahuo.mutation.FromAgentID(); ok {
		if err := agenthandoff.FromAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "from_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.from_agent_id": %w`, err)}
		}
	}
	if v, ok := ahuo.mutation.ToAgentID(); ok {
		if err := agenthandoff.ToAgentIDValidator(v); err != nil {
			return &ValidationError{Name: "to_agent_id", err: fmt.Errorf(`ent: validator failed for field "AgentHandoff.to_agent_id": %w`, err)}
		}
	}
	return nil
}

func (ahuo *AgentHandoffUpdateOne) sqlSave(ctx context.Context) (_node *AgentHandoff, err error) {
	if err := ahuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenthandoff.Table, agenthandoff.Columns, sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString))
	id, ok := ahuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentHandoff.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ahuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenthandoff.FieldID)
		for _, f := range fields {
			if !agenthandoff.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenthandoff.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ahuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ahuo.mutation.FromAgentID(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentID, field.TypeString, value)
	}
	if value, ok := ahuo.mutation.FromAgentType(); ok {
		_spec.SetField(agenthandoff.FieldFromAgentType, field.TypeString, value)
	}
	if ahuo.mutation.FromAgentTypeCleared() {
		_spec.ClearField(agenthandoff.FieldFromAgentType, field.TypeString)
	}
	if value, ok := ahuo.mutation.ToAgentID(); ok {
		_spec.SetField(agenthandoff.FieldToAgentID, field.TypeString, value)
	}
	if value, ok := ahuo.mutation.ToAgentType(); ok {
		_spec.SetField(agenthandoff.FieldToAgentType, field.TypeString, value)
	}
	if ahuo.mutation.ToAgentTypeCleared() {
		_spec.ClearField(agenthandoff.FieldToAgentType, field.TypeString)
	}
	if value, ok := ahuo.mutation.HandoffType(); ok {
		_spec.SetField(agenthandoff.FieldHandoffType, field.TypeString, value)
	}
	if value, ok := ahuo.mutation.Status(); ok {
		_spec.SetField(agenthandoff.FieldStatus, field.TypeString, value)
	}
	if value, ok := ahuo.mutation.TraceID(); ok {
		_spec.SetField(agenthandoff.FieldTraceID, field.TypeString, value)
	}
	if ahuo.mutation.TraceIDCleared() {
		_spec.ClearField(agenthandoff.FieldTraceID, field.TypeString)
	}
	if value, ok := ahuo.mutation.FromTaskID(); ok {
		_spec.SetField(agenthandoff.FieldFromTaskID, field.TypeString, value)
	}
	if ahuo.mutation.FromTaskIDCleared() {
		_spec.ClearField(agenthandoff.FieldFromTaskID, field.TypeString)
	}
	if value, ok := ahuo.mutation.ToTaskID(); ok {
		_spec.SetField(agenthandoff.FieldToTaskID, field.TypeString, value)
	}
	if ahuo.mutation.ToTaskIDCleared() {
		_spec.ClearField(agenthandoff.FieldToTaskID, field.TypeString)
	}
	if value, ok := ahuo.mutation.Payload(); ok {
		_spec.SetField(agenthandoff.FieldPayload, field.TypeJSON, value)
	}
	if ahuo.mutation.PayloadCleared() {
		_spec.ClearField(agenthandoff.FieldPayload, field.TypeJSON)
	}
	if value, ok := ahuo.mutation.Metadata(); ok {
		_spec.SetField(agenthandoff.FieldMetadata, field.TypeJSON, value)
	}
	if ahuo.mutation.MetadataCleared() {
		_spec.ClearField(agenthandoff.FieldMetadata, field.TypeJSON)
	}
	if value, ok := ahuo.mutation.PayloadSizeBytes(); ok {
		_spec.SetField(agenthandoff.FieldPayloadSizeBytes, field.TypeInt, value)
	}
	if value, ok := ahuo.mutation.AddedPayloadSizeBytes(); ok {
		_spec.AddField(agenthandoff.FieldPayloadSizeBytes, field.TypeInt, value)
	}
	if value, ok := ahuo.mutation.LatencyMs(); ok {
		_spec.SetField(agenthandoff.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := ahuo.mutation.AddedLatencyMs(); ok {
		_spec.AddField(agenthandoff.FieldLatencyMs, field.TypeInt64, value)
	}
	if ahuo.mutation.LatencyMsCleared() {
		_spec.ClearField(agenthandoff.FieldLatencyMs, field.TypeInt64)
	}
	if value, ok := ahuo.mutation.ErrorMessage(); ok {
		_spec.SetField(agenthandoff.FieldErrorMessage, field.TypeString, value)
	}
	if ahuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(agenthandoff.FieldErrorMessage, field.TypeString)
	}
	if value, ok := ahuo.mutation.AcceptedAt(); ok {
		_spec.SetField(agenthandoff.FieldAcceptedAt, field.TypeTime, value)
	}
	if ahuo.mutation.AcceptedAtCleared() {
		_spec.ClearField(agenthandoff.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := ahuo.mutation.CompletedAt(); ok {
		_spec.SetField(agenthandoff.FieldCompletedAt, field.TypeTime, value)
	}
	if ahuo.mutation.CompletedAtCleared() {
		_spec.ClearField(agenthandoff.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := ahuo.mutation.UpdatedAt(); ok {
		_spec.SetField(agenthandoff.FieldUpdatedAt, field.TypeTime, value)
	}
	if ahuo.mutation.WorkflowCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenthandoff.WorkflowTable,
			Columns: []string{agenthandoff.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ahuo.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenthandoff.WorkflowTable,
			Columns: []string{agenthandoff.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentHandoff{config: ahuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ahuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenthandoff.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ahuo.mutation.done = true
	return _node, nil
}
