// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plexusone/omniobserve/agentops/ent/agentevent"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/schema"
	"github.com/plexusone/omniobserve/agentops/ent/toolinvocation"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agenteventFields := schema.AgentEvent{}.Fields()
	_ = agenteventFields
	// agenteventDescEventType is the schema descriptor for event_type field.
	agenteventDescEventType := agenteventFields[1].Descriptor()
	// agentevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	agentevent.EventTypeValidator = agenteventDescEventType.Validators[0].(func(string) error)
	// agenteventDescEventCategory is the schema descriptor for event_category field.
	agenteventDescEventCategory := agenteventFields[2].Descriptor()
	// agentevent.DefaultEventCategory holds the default value on creation for the event_category field.
	agentevent.DefaultEventCategory = agenteventDescEventCategory.Default.(string)
	// agenteventDescSeverity is the schema descriptor for severity field.
	agenteventDescSeverity := agenteventFields[8].Descriptor()
	// agentevent.DefaultSeverity holds the default value on creation for the severity field.
	agentevent.DefaultSeverity = agenteventDescSeverity.Default.(string)
	// agenteventDescVersion is the schema descriptor for version field.
	agenteventDescVersion := agenteventFields[13].Descriptor()
	// agentevent.DefaultVersion holds the default value on creation for the version field.
	agentevent.DefaultVersion = agenteventDescVersion.Default.(string)
	// agenteventDescTimestamp is the schema descriptor for timestamp field.
	agenteventDescTimestamp := agenteventFields[14].Descriptor()
	// agentevent.DefaultTimestamp holds the default value on creation for the timestamp field.
	agentevent.DefaultTimestamp = agenteventDescTimestamp.Default.(func() time.Time)
	// agenteventDescCreatedAt is the schema descriptor for created_at field.
	agenteventDescCreatedAt := agenteventFields[15].Descriptor()
	// agentevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agentevent.DefaultCreatedAt = agenteventDescCreatedAt.Default.(func() time.Time)
	agenthandoffFields := schema.AgentHandoff{}.Fields()
	_ = agenthandoffFields
	// agenthandoffDescFromAgentID is the schema descriptor for from_agent_id field.
	agenthandoffDescFromAgentID := agenthandoffFields[2].Descriptor()
	// agenthandoff.FromAgentIDValidator is a validator for the "from_agent_id" field. It is called by the builders before save.
	agenthandoff.FromAgentIDValidator = agenthandoffDescFromAgentID.Validators[0].(func(string) error)
	// agenthandoffDescToAgentID is the schema descriptor for to_agent_id field.
	agenthandoffDescToAgentID := agenthandoffFields[4].Descriptor()
	// agenthandoff.ToAgentIDValidator is a validator for the "to_agent_id" field. It is called by the builders before save.
	agenthandoff.ToAgentIDValidator = agenthandoffDescToAgentID.Validators[0].(func(string) error)
	// agenthandoffDescHandoffType is the schema descriptor for handoff_type field.
	agenthandoffDescHandoffType := agenthandoffFields[6].Descriptor()
	// agenthandoff.DefaultHandoffType holds the default value on creation for the handoff_type field.
	agenthandoff.DefaultHandoffType = agenthandoffDescHandoffType.Default.(string)
	// agenthandoffDescStatus is the schema descriptor for status field.
	agenthandoffDescStatus := agenthandoffFields[7].Descriptor()
	// agenthandoff.DefaultStatus holds the default value on creation for the status field.
	agenthandoff.DefaultStatus = agenthandoffDescStatus.Default.(string)
	// agenthandoffDescPayloadSizeBytes is the schema descriptor for payload_size_bytes field.
	agenthandoffDescPayloadSizeBytes := agenthandoffFields[13].Descriptor()
	// agenthandoff.DefaultPayloadSizeBytes holds the default value on creation for the payload_size_bytes field.
	agenthandoff.DefaultPayloadSizeBytes = agenthandoffDescPayloadSizeBytes.Default.(int)
	// agenthandoffDescInitiatedAt is the schema descriptor for initiated_at field.
	agenthandoffDescInitiatedAt := agenthandoffFields[16].Descriptor()
	// agenthandoff.DefaultInitiatedAt holds the default value on creation for the initiated_at field.
	agenthandoff.DefaultInitiatedAt = agenthandoffDescInitiatedAt.Default.(func() time.Time)
	// agenthandoffDescCreatedAt is the schema descriptor for created_at field.
	agenthandoffDescCreatedAt := agenthandoffFields[19].Descriptor()
	// agenthandoff.DefaultCreatedAt holds the default value on creation for the created_at field.
	agenthandoff.DefaultCreatedAt = agenthandoffDescCreatedAt.Default.(func() time.Time)
	// agenthandoffDescUpdatedAt is the schema descriptor for updated_at field.
	agenthandoffDescUpdatedAt := agenthandoffFields[20].Descriptor()
	// agenthandoff.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agenthandoff.DefaultUpdatedAt = agenthandoffDescUpdatedAt.Default.(func() time.Time)
	// agenthandoff.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agenthandoff.UpdateDefaultUpdatedAt = agenthandoffDescUpdatedAt.UpdateDefault.(func() time.Time)
	agenttaskFields := schema.AgentTask{}.Fields()
	_ = agenttaskFields
	// agenttaskDescAgentID is the schema descriptor for agent_id field.
	agenttaskDescAgentID := agenttaskFields[2].Descriptor()
	// agenttask.AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	agenttask.AgentIDValidator = agenttaskDescAgentID.Validators[0].(func(string) error)
	// agenttaskDescTaskType is the schema descriptor for task_type field.
	agenttaskDescTaskType := agenttaskFields[4].Descriptor()
	// agenttask.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	agenttask.TaskTypeValidator = agenttaskDescTaskType.Validators[0].(func(string) error)
	// agenttaskDescName is the schema descriptor for name field.
	agenttaskDescName := agenttaskFields[5].Descriptor()
	// agenttask.NameValidator is a validator for the "name" field. It is called by the builders before save.
	agenttask.NameValidator = agenttaskDescName.Validators[0].(func(string) error)
	// agenttaskDescStatus is the schema descriptor for status field.
	agenttaskDescStatus := agenttaskFields[6].Descriptor()
	// agenttask.DefaultStatus holds the default value on creation for the status field.
	agenttask.DefaultStatus = agenttaskDescStatus.Default.(string)
	// agenttaskDescLlmCallCount is the schema descriptor for llm_call_count field.
	agenttaskDescLlmCallCount := agenttaskFields[13].Descriptor()
	// agenttask.DefaultLlmCallCount holds the default value on creation for the llm_call_count field.
	agenttask.DefaultLlmCallCount = agenttaskDescLlmCallCount.Default.(int)
	// agenttaskDescToolCallCount is the schema descriptor for tool_call_count field.
	agenttaskDescToolCallCount := agenttaskFields[14].Descriptor()
	// agenttask.DefaultToolCallCount holds the default value on creation for the tool_call_count field.
	agenttask.DefaultToolCallCount = agenttaskDescToolCallCount.Default.(int)
	// agenttaskDescRetryCount is the schema descriptor for retry_count field.
	agenttaskDescRetryCount := agenttaskFields[15].Descriptor()
	// agenttask.DefaultRetryCount holds the default value on creation for the retry_count field.
	agenttask.DefaultRetryCount = agenttaskDescRetryCount.Default.(int)
	// agenttaskDescTokensPrompt is the schema descriptor for tokens_prompt field.
	agenttaskDescTokensPrompt := agenttaskFields[16].Descriptor()
	// agenttask.DefaultTokensPrompt holds the default value on creation for the tokens_prompt field.
	agenttask.DefaultTokensPrompt = agenttaskDescTokensPrompt.Default.(int)
	// agenttaskDescTokensCompletion is the schema descriptor for tokens_completion field.
	agenttaskDescTokensCompletion := agenttaskFields[17].Descriptor()
	// agenttask.DefaultTokensCompletion holds the default value on creation for the tokens_completion field.
	agenttask.DefaultTokensCompletion = agenttaskDescTokensCompletion.Default.(int)
	// agenttaskDescTokensTotal is the schema descriptor for tokens_total field.
	agenttaskDescTokensTotal := agenttaskFields[18].Descriptor()
	// agenttask.DefaultTokensTotal holds the default value on creation for the tokens_total field.
	agenttask.DefaultTokensTotal = agenttaskDescTokensTotal.Default.(int)
	// agenttaskDescCostUsd is the schema descriptor for cost_usd field.
	agenttaskDescCostUsd := agenttaskFields[19].Descriptor()
	// agenttask.DefaultCostUsd holds the default value on creation for the cost_usd field.
	agenttask.DefaultCostUsd = agenttaskDescCostUsd.Default.(float64)
	// agenttaskDescStartedAt is the schema descriptor for started_at field.
	agenttaskDescStartedAt := agenttaskFields[23].Descriptor()
	// agenttask.DefaultStartedAt holds the default value on creation for the started_at field.
	agenttask.DefaultStartedAt = agenttaskDescStartedAt.Default.(func() time.Time)
	// agenttaskDescCreatedAt is the schema descriptor for created_at field.
	agenttaskDescCreatedAt := agenttaskFields[25].Descriptor()
	// agenttask.DefaultCreatedAt holds the default value on creation for the created_at field.
	agenttask.DefaultCreatedAt = agenttaskDescCreatedAt.Default.(func() time.Time)
	// agenttaskDescUpdatedAt is the schema descriptor for updated_at field.
	agenttaskDescUpdatedAt := agenttaskFields[26].Descriptor()
	// agenttask.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agenttask.DefaultUpdatedAt = agenttaskDescUpdatedAt.Default.(func() time.Time)
	// agenttask.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agenttask.UpdateDefaultUpdatedAt = agenttaskDescUpdatedAt.UpdateDefault.(func() time.Time)
	toolinvocationFields := schema.ToolInvocation{}.Fields()
	_ = toolinvocationFields
	// toolinvocationDescAgentID is the schema descriptor for agent_id field.
	toolinvocationDescAgentID := toolinvocationFields[2].Descriptor()
	// toolinvocation.AgentIDValidator is a validator for the "agent_id" field. It is called by the builders before save.
	toolinvocation.AgentIDValidator = toolinvocationDescAgentID.Validators[0].(func(string) error)
	// toolinvocationDescToolName is the schema descriptor for tool_name field.
	toolinvocationDescToolName := toolinvocationFields[3].Descriptor()
	// toolinvocation.ToolNameValidator is a validator for the "tool_name" field. It is called by the builders before save.
	toolinvocation.ToolNameValidator = toolinvocationDescToolName.Validators[0].(func(string) error)
	// toolinvocationDescStatus is the schema descriptor for status field.
	toolinvocationDescStatus := toolinvocationFields[5].Descriptor()
	// toolinvocation.DefaultStatus holds the default value on creation for the status field.
	toolinvocation.DefaultStatus = toolinvocationDescStatus.Default.(string)
	// toolinvocationDescRequestSizeBytes is the schema descriptor for request_size_bytes field.
	toolinvocationDescRequestSizeBytes := toolinvocationFields[15].Descriptor()
	// toolinvocation.DefaultRequestSizeBytes holds the default value on creation for the request_size_bytes field.
	toolinvocation.DefaultRequestSizeBytes = toolinvocationDescRequestSizeBytes.Default.(int)
	// toolinvocationDescResponseSizeBytes is the schema descriptor for response_size_bytes field.
	toolinvocationDescResponseSizeBytes := toolinvocationFields[16].Descriptor()
	// toolinvocation.DefaultResponseSizeBytes holds the default value on creation for the response_size_bytes field.
	toolinvocation.DefaultResponseSizeBytes = toolinvocationDescResponseSizeBytes.Default.(int)
	// toolinvocationDescRetryCount is the schema descriptor for retry_count field.
	toolinvocationDescRetryCount := toolinvocationFields[17].Descriptor()
	// toolinvocation.DefaultRetryCount holds the default value on creation for the retry_count field.
	toolinvocation.DefaultRetryCount = toolinvocationDescRetryCount.Default.(int)
	// toolinvocationDescStartedAt is the schema descriptor for started_at field.
	toolinvocationDescStartedAt := toolinvocationFields[20].Descriptor()
	// toolinvocation.DefaultStartedAt holds the default value on creation for the started_at field.
	toolinvocation.DefaultStartedAt = toolinvocationDescStartedAt.Default.(func() time.Time)
	// toolinvocationDescCreatedAt is the schema descriptor for created_at field.
	toolinvocationDescCreatedAt := toolinvocationFields[22].Descriptor()
	// toolinvocation.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolinvocation.DefaultCreatedAt = toolinvocationDescCreatedAt.Default.(func() time.Time)
	// toolinvocationDescUpdatedAt is the schema descriptor for updated_at field.
	toolinvocationDescUpdatedAt := toolinvocationFields[23].Descriptor()
	// toolinvocation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	toolinvocation.DefaultUpdatedAt = toolinvocationDescUpdatedAt.Default.(func() time.Time)
	// toolinvocation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	toolinvocation.UpdateDefaultUpdatedAt = toolinvocationDescUpdatedAt.UpdateDefault.(func() time.Time)
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescName is the schema descriptor for name field.
	workflowDescName := workflowFields[1].Descriptor()
	// workflow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workflow.NameValidator = workflowDescName.Validators[0].(func(string) error)
	// workflowDescStatus is the schema descriptor for status field.
	workflowDescStatus := workflowFields[2].Descriptor()
	// workflow.DefaultStatus holds the default value on creation for the status field.
	workflow.DefaultStatus = workflowDescStatus.Default.(string)
	// workflowDescTaskCount is the schema descriptor for task_count field.
	workflowDescTaskCount := workflowFields[9].Descriptor()
	// workflow.DefaultTaskCount holds the default value on creation for the task_count field.
	workflow.DefaultTaskCount = workflowDescTaskCount.Default.(int)
	// workflowDescCompletedTaskCount is the schema descriptor for completed_task_count field.
	workflowDescCompletedTaskCount := workflowFields[10].Descriptor()
	// workflow.DefaultCompletedTaskCount holds the default value on creation for the completed_task_count field.
	workflow.DefaultCompletedTaskCount = workflowDescCompletedTaskCount.Default.(int)
	// workflowDescFailedTaskCount is the schema descriptor for failed_task_count field.
	workflowDescFailedTaskCount := workflowFields[11].Descriptor()
	// workflow.DefaultFailedTaskCount holds the default value on creation for the failed_task_count field.
	workflow.DefaultFailedTaskCount = workflowDescFailedTaskCount.Default.(int)
	// workflowDescTotalCostUsd is the schema descriptor for total_cost_usd field.
	workflowDescTotalCostUsd := workflowFields[12].Descriptor()
	// workflow.DefaultTotalCostUsd holds the default value on creation for the total_cost_usd field.
	workflow.DefaultTotalCostUsd = workflowDescTotalCostUsd.Default.(float64)
	// workflowDescTotalTokens is the schema descriptor for total_tokens field.
	workflowDescTotalTokens := workflowFields[13].Descriptor()
	// workflow.DefaultTotalTokens holds the default value on creation for the total_tokens field.
	workflow.DefaultTotalTokens = workflowDescTotalTokens.Default.(int)
	// workflowDescStartedAt is the schema descriptor for started_at field.
	workflowDescStartedAt := workflowFields[16].Descriptor()
	// workflow.DefaultStartedAt holds the default value on creation for the started_at field.
	workflow.DefaultStartedAt = workflowDescStartedAt.Default.(func() time.Time)
	// workflowDescCreatedAt is the schema descriptor for created_at field.
	workflowDescCreatedAt := workflowFields[18].Descriptor()
	// workflow.DefaultCreatedAt holds the default value on creation for the created_at field.
	workflow.DefaultCreatedAt = workflowDescCreatedAt.Default.(func() time.Time)
	// workflowDescUpdatedAt is the schema descriptor for updated_at field.
	workflowDescUpdatedAt := workflowFields[19].Descriptor()
	// workflow.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	workflow.DefaultUpdatedAt = workflowDescUpdatedAt.Default.(func() time.Time)
	// workflow.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	workflow.UpdateDefaultUpdatedAt = workflowDescUpdatedAt.UpdateDefault.(func() time.Time)
}
