// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/toolinvocation"
)

// ToolInvocationCreate is the builder for creating a ToolInvocation entity.
type ToolInvocationCreate struct {
	config
	mutation *ToolInvocationMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (tic *ToolInvocationCreate) SetTaskID(s string) *ToolInvocationCreate {
	tic.mutation.SetTaskID(s)
	return tic
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableTaskID(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetTaskID(*s)
	}
	return tic
}

// SetAgentID sets the "agent_id" field.
func (tic *ToolInvocationCreate) SetAgentID(s string) *ToolInvocationCreate {
	tic.mutation.SetAgentID(s)
	return tic
}

// SetToolName sets the "tool_name" field.
func (tic *ToolInvocationCreate) SetToolName(s string) *ToolInvocationCreate {
	tic.mutation.SetToolName(s)
	return tic
}

// SetToolType sets the "tool_type" field.
func (tic *ToolInvocationCreate) SetToolType(s string) *ToolInvocationCreate {
	tic.mutation.SetToolType(s)
	return tic
}

// SetNillableToolType sets the "tool_type" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableToolType(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetToolType(*s)
	}
	return tic
}

// SetStatus sets the "status" field.
func (tic *ToolInvocationCreate) SetStatus(s string) *ToolInvocationCreate {
	tic.mutation.SetStatus(s)
	return tic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableStatus(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetStatus(*s)
	}
	return tic
}

// SetTraceID sets the "trace_id" field.
func (tic *ToolInvocationCreate) SetTraceID(s string) *ToolInvocationCreate {
	tic.mutation.SetTraceID(s)
	return tic
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableTraceID(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetTraceID(*s)
	}
	return tic
}

// SetSpanID sets the "span_id" field.
func (tic *ToolInvocationCreate) SetSpanID(s string) *ToolInvocationCreate {
	tic.mutation.SetSpanID(s)
	return tic
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableSpanID(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetSpanID(*s)
	}
	return tic
}

// SetInput sets the "input" field.
func (tic *ToolInvocationCreate) SetInput(m map[string]interface{}) *ToolInvocationCreate {
	tic.mutation.SetInput(m)
	return tic
}

// SetOutput sets the "output" field.
func (tic *ToolInvocationCreate) SetOutput(m map[string]interface{}) *ToolInvocationCreate {
	tic.mutation.SetOutput(m)
	return tic
}

// SetMetadata sets the "metadata" field.
func (tic *ToolInvocationCreate) SetMetadata(m map[string]interface{}) *ToolInvocationCreate {
	tic.mutation.SetMetadata(m)
	return tic
}

// SetHTTPMethod sets the "http_method" field.
func (tic *ToolInvocationCreate) SetHTTPMethod(s string) *ToolInvocationCreate {
	tic.mutation.SetHTTPMethod(s)
	return tic
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableHTTPMethod(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetHTTPMethod(*s)
	}
	return tic
}

// SetHTTPURL sets the "http_url" field.
func (tic *ToolInvocationCreate) SetHTTPURL(s string) *ToolInvocationCreate {
	tic.mutation.SetHTTPURL(s)
	return tic
}

// SetNillableHTTPURL sets the "http_url" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableHTTPURL(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetHTTPURL(*s)
	}
	return tic
}

// SetHTTPStatusCode sets the "http_status_code" field.
func (tic *ToolInvocationCreate) SetHTTPStatusCode(i int) *ToolInvocationCreate {
	tic.mutation.SetHTTPStatusCode(i)
	return tic
}

// SetNillableHTTPStatusCode sets the "http_status_code" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableHTTPStatusCode(i *int) *ToolInvocationCreate {
	if i != nil {
		tic.SetHTTPStatusCode(*i)
	}
	return tic
}

// SetDurationMs sets the "duration_ms" field.
func (tic *ToolInvocationCreate) SetDurationMs(i int64) *ToolInvocationCreate {
	tic.mutation.SetDurationMs(i)
	return tic
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableDurationMs(i *int64) *ToolInvocationCreate {
	if i != nil {
		tic.SetDurationMs(*i)
	}
	return tic
}

// SetRequestSizeBytes sets the "request_size_bytes" field.
func (tic *ToolInvocationCreate) SetRequestSizeBytes(i int) *ToolInvocationCreate {
	tic.mutation.SetRequestSizeBytes(i)
	return tic
}

// SetNillableRequestSizeBytes sets the "request_size_bytes" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableRequestSizeBytes(i *int) *ToolInvocationCreate {
	if i != nil {
		tic.SetRequestSizeBytes(*i)
	}
	return tic
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (tic *ToolInvocationCreate) SetResponseSizeBytes(i int) *ToolInvocationCreate {
	tic.mutation.SetResponseSizeBytes(i)
	return tic
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableResponseSizeBytes(i *int) *ToolInvocationCreate {
	if i != nil {
		tic.SetResponseSizeBytes(*i)
	}
	return tic
}

// SetRetryCount sets the "retry_count" field.
func (tic *ToolInvocationCreate) SetRetryCount(i int) *ToolInvocationCreate {
	tic.mutation.SetRetryCount(i)
	return tic
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableRetryCount(i *int) *ToolInvocationCreate {
	if i != nil {
		tic.SetRetryCount(*i)
	}
	return tic
}

// SetErrorType sets the "error_type" field.
func (tic *ToolInvocationCreate) SetErrorType(s string) *ToolInvocationCreate {
	tic.mutation.SetErrorType(s)
	return tic
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableErrorType(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetErrorType(*s)
	}
	return tic
}

// SetErrorMessage sets the "error_message" field.
func (tic *ToolInvocationCreate) SetErrorMessage(s string) *ToolInvocationCreate {
	tic.mutation.SetErrorMessage(s)
	return tic
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableErrorMessage(s *string) *ToolInvocationCreate {
	if s != nil {
		tic.SetErrorMessage(*s)
	}
	return tic
}

// SetStartedAt sets the "started_at" field.
func (tic *ToolInvocationCreate) SetStartedAt(t time.Time) *ToolInvocationCreate {
	tic.mutation.SetStartedAt(t)
	return tic
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableStartedAt(t *time.Time) *ToolInvocationCreate {
	if t != nil {
		tic.SetStartedAt(*t)
	}
	return tic
}

// SetEndedAt sets the "ended_at" field.
func (tic *ToolInvocationCreate) SetEndedAt(t time.Time) *ToolInvocationCreate {
	tic.mutation.SetEndedAt(t)
	return tic
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableEndedAt(t *time.Time) *ToolInvocationCreate {
	if t != nil {
		tic.SetEndedAt(*t)
	}
	return tic
}

// SetCreatedAt sets the "created_at" field.
func (tic *ToolInvocationCreate) SetCreatedAt(t time.Time) *ToolInvocationCreate {
	tic.mutation.SetCreatedAt(t)
	return tic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableCreatedAt(t *time.Time) *ToolInvocationCreate {
	if t != nil {
		tic.SetCreatedAt(*t)
	}
	return tic
}

// SetUpdatedAt sets the "updated_at" field.
func (tic *ToolInvocationCreate) SetUpdatedAt(t time.Time) *ToolInvocationCreate {
	tic.mutation.SetUpdatedAt(t)
	return tic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tic *ToolInvocationCreate) SetNillableUpdatedAt(t *time.Time) *ToolInvocationCreate {
	if t != nil {
		tic.SetUpdatedAt(*t)
	}
	return tic
}

// SetID sets the "id" field.
func (tic *ToolInvocationCreate) SetID(s string) *ToolInvocationCreate {
	tic.mutation.SetID(s)
	return tic
}

// SetTask sets the "task" edge to the AgentTask entity.
func (tic *ToolInvocationCreate) SetTask(a *AgentTask) *ToolInvocationCreate {
	return tic.SetTaskID(a.ID)
}

// Mutation returns the ToolInvocationMutation object of the builder.
func (tic *ToolInvocationCreate) Mutation() *ToolInvocationMutation {
	return tic.mutation
}

// Save creates the ToolInvocation in the database.
func (tic *ToolInvocationCreate) Save(ctx context.Context) (*ToolInvocation, error) {
	tic.defaults()
	return withHooks(ctx, tic.sqlSave, tic.mutation, tic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tic *ToolInvocationCreate) SaveX(ctx context.Context) *ToolInvocation {
	v, err := tic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tic *ToolInvocationCreate) Exec(ctx context.Context) error {
	_, err := tic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tic *ToolInvocationCreate) ExecX(ctx context.Context) {
	if err := tic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tic *ToolInvocationCreate) defaults() {
	if _, ok := tic.mutation.Status(); !ok {
		v := toolinvocation.DefaultStatus
		tic.mutation.SetStatus(v)
	}
	if _, ok := tic.mutation.RequestSizeBytes(); !ok {
		v := toolinvocation.DefaultRequestSizeBytes
		tic.mutation.SetRequestSizeBytes(v)
	}
	if _, ok := tic.mutation.ResponseSizeBytes(); !ok {
		v := toolinvocation.DefaultResponseSizeBytes
		tic.mutation.SetResponseSizeBytes(v)
	}
	if _, ok := tic.mutation.RetryCount(); !ok {
		v := toolinvocation.DefaultRetryCount
		tic.mutation.SetRetryCount(v)
	}
	if _, ok := tic.mutation.StartedAt(); !ok {
		v := toolinvocation.DefaultStartedAt()
		tic.mutation.SetStartedAt(v)
	}
	if _, ok := tic.mutation.CreatedAt(); !ok {
		v := toolinvocation.DefaultCreatedAt()
		tic.mutation.SetCreatedAt(v)
	}
	if _, ok := tic.mutation.UpdatedAt(); !ok {
		v := toolinvocation.DefaultUpdatedAt()
		tic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tic *ToolInvocationCreate) check() error {
	if _, ok := tic.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "ToolInvocation.agent_id"`)}
	}
	if v, ok := tic.mutation.AgentID(); ok {
		if err := toolinvocation.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.agent_id": %w`, err)}
		}
	}
	if _, ok := tic.mutation.ToolName(); !ok {
		return &ValidationError{Name: "tool_name", err: errors.New(`ent: missing required field "ToolInvocation.tool_name"`)}
	}
	if v, ok := tic.mutation.ToolName(); ok {
		if err := toolinvocation.ToolNameValidator(v); err != nil {
			return &ValidationError{Name: "tool_name", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.tool_name": %w`, err)}
		}
	}
	if _, ok := tic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ToolInvocation.status"`)}
	}
	if _, ok := tic.mutation.RequestSizeBytes(); !ok {
		return &ValidationError{Name: "request_size_bytes", err: errors.New(`ent: missing required field "ToolInvocation.request_size_bytes"`)}
	}
	if _, ok := tic.mutation.ResponseSizeBytes(); !ok {
		return &ValidationError{Name: "response_size_bytes", err: errors.New(`ent: missing required field "ToolInvocation.response_size_bytes"`)}
	}
	if _, ok := tic.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "ToolInvocation.retry_count"`)}
	}
	if _, ok := tic.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "ToolInvocation.started_at"`)}
	}
	if _, ok := tic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ToolInvocation.created_at"`)}
	}
	if _, ok := tic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ToolInvocation.updated_at"`)}
	}
	return nil
}

func (tic *ToolInvocationCreate) sqlSave(ctx context.Context) (*ToolInvocation, error) {
	if err := tic.check(); err != nil {
		return nil, err
	}
	_node, _spec := tic.createSpec()
	if err := sqlgraph.CreateNode(ctx, tic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ToolInvocation.ID type: %T", _spec.ID.Value)
		}
	}
	tic.mutation.id = &_node.ID
	tic.mutation.done = true
	return _node, nil
}

func (tic *ToolInvocationCreate) createSpec() (*ToolInvocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ToolInvocation{config: tic.config}
		_spec = sqlgraph.NewCreateSpec(toolinvocation.Table, sqlgraph.NewFieldSpec(toolinvocation.FieldID, field.TypeString))
	)
	if id, ok := tic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tic.mutation.AgentID(); ok {
		_spec.SetField(toolinvocation.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := tic.mutation.ToolName(); ok {
		_spec.SetField(toolinvocation.FieldToolName, field.TypeString, value)
		_node.ToolName = value
	}
	if value, ok := tic.mutation.ToolType(); ok {
		_spec.SetField(toolinvocation.FieldToolType, field.TypeString, value)
		_node.ToolType = value
	}
	if value, ok := tic.mutation.Status(); ok {
		_spec.SetField(toolinvocation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := tic.mutation.TraceID(); ok {
		_spec.SetField(toolinvocation.FieldTraceID, field.TypeString, value)
		_node.TraceID = value
	}
	if value, ok := tic.mutation.SpanID(); ok {
		_spec.SetField(toolinvocation.FieldSpanID, field.TypeString, value)
		_node.SpanID = value
	}
	if value, ok := tic.mutation.Input(); ok {
		_spec.SetField(toolinvocation.FieldInput, field.TypeJSON, value)
		_node.Input = value
	}
	if value, ok := tic.mutation.Output(); ok {
		_spec.SetField(toolinvocation.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := tic.mutation.Metadata(); ok {
		_spec.SetField(toolinvocation.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := tic.mutation.HTTPMethod(); ok {
		_spec.SetField(toolinvocation.FieldHTTPMethod, field.TypeString, value)
		_node.HTTPMethod = value
	}
	if value, ok := tic.mutation.HTTPURL(); ok {
		_spec.SetField(toolinvocation.FieldHTTPURL, field.TypeString, value)
		_node.HTTPURL = value
	}
	if value, ok := tic.mutation.HTTPStatusCode(); ok {
		_spec.SetField(toolinvocation.FieldHTTPStatusCode, field.TypeInt, value)
		_node.HTTPStatusCode = value
	}
	if value, ok := tic.mutation.DurationMs(); ok {
		_spec.SetField(toolinvocation.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := tic.mutation.RequestSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldRequestSizeBytes, field.TypeInt, value)
		_node.RequestSizeBytes = value
	}
	if value, ok := tic.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldResponseSizeBytes, field.TypeInt, value)
		_node.ResponseSizeBytes = value
	}
	if value, ok := tic.mutation.RetryCount(); ok {
		_spec.SetField(toolinvocation.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := tic.mutation.ErrorType(); ok {
		_spec.SetField(toolinvocation.FieldErrorType, field.TypeString, value)
		_node.ErrorType = value
	}
	if value, ok := tic.mutation.ErrorMessage(); ok {
		_spec.SetField(toolinvocation.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := tic.mutation.StartedAt(); ok {
		_spec.SetField(toolinvocation.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := tic.mutation.EndedAt(); ok {
		_spec.SetField(toolinvocation.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := tic.mutation.CreatedAt(); ok {
		_spec.SetField(toolinvocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tic.mutation.UpdatedAt(); ok {
		_spec.SetField(toolinvocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tic.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.TaskTable,
			Columns: []string{toolinvocation.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ToolInvocationCreateBulk is the builder for creating many ToolInvocation entities in bulk.
type ToolInvocationCreateBulk struct {
	config
	err      error
	builders []*ToolInvocationCreate
}

// Save creates the ToolInvocation entities in the database.
func (ticb *ToolInvocationCreateBulk) Save(ctx context.Context) ([]*ToolInvocation, error) {
	if ticb.err != nil {
		return nil, ticb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ticb.builders))
	nodes := make([]*ToolInvocation, len(ticb.builders))
	mutators := make([]Mutator, len(ticb.builders))
	for i := range ticb.builders {
		func(i int, root context.Context) {
			builder := ticb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolInvocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ticb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ticb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ticb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ticb *ToolInvocationCreateBulk) SaveX(ctx context.Context) []*ToolInvocation {
	v, err := ticb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ticb *ToolInvocationCreateBulk) Exec(ctx context.Context) error {
	_, err := ticb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ticb *ToolInvocationCreateBulk) ExecX(ctx context.Context) {
	if err := ticb.Exec(ctx); err != nil {
		panic(err)
	}
}
