// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/toolinvocation"
)

// ToolInvocationUpdate is the builder for updating ToolInvocation entities.
type ToolInvocationUpdate struct {
	config
	hooks    []Hook
	mutation *ToolInvocationMutation
}

// Where appends a list predicates to the ToolInvocationUpdate builder.
func (tiu *ToolInvocationUpdate) Where(ps ...predicate.ToolInvocation) *ToolInvocationUpdate {
	tiu.mutation.Where(ps...)
	return tiu
}

// SetTaskID sets the "task_id" field.
func (tiu *ToolInvocationUpdate) SetTaskID(s string) *ToolInvocationUpdate {
	tiu.mutation.SetTaskID(s)
	return tiu
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableTaskID(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetTaskID(*s)
	}
	return tiu
}

// ClearTaskID clears the value of the "task_id" field.
func (tiu *ToolInvocationUpdate) ClearTaskID() *ToolInvocationUpdate {
	tiu.mutation.ClearTaskID()
	return tiu
}

// SetAgentID sets the "agent_id" field.
func (tiu *ToolInvocationUpdate) SetAgentID(s string) *ToolInvocationUpdate {
	tiu.mutation.SetAgentID(s)
	return tiu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableAgentID(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetAgentID(*s)
	}
	return tiu
}

// SetToolName sets the "tool_name" field.
func (tiu *ToolInvocationUpdate) SetToolName(s string) *ToolInvocationUpdate {
	tiu.mutation.SetToolName(s)
	return tiu
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableToolName(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetToolName(*s)
	}
	return tiu
}

// SetToolType sets the "tool_type" field.
func (tiu *ToolInvocationUpdate) SetToolType(s string) *ToolInvocationUpdate {
	tiu.mutation.SetToolType(s)
	return tiu
}

// SetNillableToolType sets the "tool_type" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableToolType(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetToolType(*s)
	}
	return tiu
}

// ClearToolType clears the value of the "tool_type" field.
func (tiu *ToolInvocationUpdate) ClearToolType() *ToolInvocationUpdate {
	tiu.mutation.ClearToolType()
	return tiu
}

// SetStatus sets the "status" field.
func (tiu *ToolInvocationUpdate) SetStatus(s string) *ToolInvocationUpdate {
	tiu.mutation.SetStatus(s)
	return tiu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableStatus(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetStatus(*s)
	}
	return tiu
}

// SetTraceID sets the "trace_id" field.
func (tiu *ToolInvocationUpdate) SetTraceID(s string) *ToolInvocationUpdate {
	tiu.mutation.SetTraceID(s)
	return tiu
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableTraceID(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetTraceID(*s)
	}
	return tiu
}

// ClearTraceID clears the value of the "trace_id" field.
func (tiu *ToolInvocationUpdate) ClearTraceID() *ToolInvocationUpdate {
	tiu.mutation.ClearTraceID()
	return tiu
}

// SetSpanID sets the "span_id" field.
func (tiu *ToolInvocationUpdate) SetSpanID(s string) *ToolInvocationUpdate {
	tiu.mutation.SetSpanID(s)
	return tiu
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableSpanID(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetSpanID(*s)
	}
	return tiu
}

// ClearSpanID clears the value of the "span_id" field.
func (tiu *ToolInvocationUpdate) ClearSpanID() *ToolInvocationUpdate {
	tiu.mutation.ClearSpanID()
	return tiu
}

// SetInput sets the "input" field.
func (tiu *ToolInvocationUpdate) SetInput(m map[string]interface{}) *ToolInvocationUpdate {
	tiu.mutation.SetInput(m)
	return tiu
}

// ClearInput clears the value of the "input" field.
func (tiu *ToolInvocationUpdate) ClearInput() *ToolInvocationUpdate {
	tiu.mutation.ClearInput()
	return tiu
}

// SetOutput sets the "output" field.
func (tiu *ToolInvocationUpdate) SetOutput(m map[string]interface{}) *ToolInvocationUpdate {
	tiu.mutation.SetOutput(m)
	return tiu
}

// ClearOutput clears the value of the "output" field.
func (tiu *ToolInvocationUpdate) ClearOutput() *ToolInvocationUpdate {
	tiu.mutation.ClearOutput()
	return tiu
}

// SetMetadata sets the "metadata" field.
func (tiu *ToolInvocationUpdate) SetMetadata(m map[string]interface{}) *ToolInvocationUpdate {
	tiu.mutation.SetMetadata(m)
	return tiu
}

// ClearMetadata clears the value of the "metadata" field.
func (tiu *ToolInvocationUpdate) ClearMetadata() *ToolInvocationUpdate {
	tiu.mutation.ClearMetadata()
	return tiu
}

// SetHTTPMethod sets the "http_method" field.
func (tiu *ToolInvocationUpdate) SetHTTPMethod(s string) *ToolInvocationUpdate {
	tiu.mutation.SetHTTPMethod(s)
	return tiu
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableHTTPMethod(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetHTTPMethod(*s)
	}
	return tiu
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (tiu *ToolInvocationUpdate) ClearHTTPMethod() *ToolInvocationUpdate {
	tiu.mutation.ClearHTTPMethod()
	return tiu
}

// SetHTTPURL sets the "http_url" field.
func (tiu *ToolInvocationUpdate) SetHTTPURL(s string) *ToolInvocationUpdate {
	tiu.mutation.SetHTTPURL(s)
	return tiu
}

// SetNillableHTTPURL sets the "http_url" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableHTTPURL(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetHTTPURL(*s)
	}
	return tiu
}

// ClearHTTPURL clears the value of the "http_url" field.
func (tiu *ToolInvocationUpdate) ClearHTTPURL() *ToolInvocationUpdate {
	tiu.mutation.ClearHTTPURL()
	return tiu
}

// SetHTTPStatusCode sets the "http_status_code" field.
func (tiu *ToolInvocationUpdate) SetHTTPStatusCode(i int) *ToolInvocationUpdate {
	tiu.mutation.ResetHTTPStatusCode()
	tiu.mutation.SetHTTPStatusCode(i)
	return tiu
}

// SetNillableHTTPStatusCode sets the "http_status_code" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableHTTPStatusCode(i *int) *ToolInvocationUpdate {
	if i != nil {
		tiu.SetHTTPStatusCode(*i)
	}
	return tiu
}

// AddHTTPStatusCode adds i to the "http_status_code" field.
func (tiu *ToolInvocationUpdate) AddHTTPStatusCode(i int) *ToolInvocationUpdate {
	tiu.mutation.AddHTTPStatusCode(i)
	return tiu
}

// ClearHTTPStatusCode clears the value of the "http_status_code" field.
func (tiu *ToolInvocationUpdate) ClearHTTPStatusCode() *ToolInvocationUpdate {
	tiu.mutation.ClearHTTPStatusCode()
	return tiu
}

// SetDurationMs sets the "duration_ms" field.
func (tiu *ToolInvocationUpdate) SetDurationMs(i int64) *ToolInvocationUpdate {
	tiu.mutation.ResetDurationMs()
	tiu.mutation.SetDurationMs(i)
	return tiu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableDurationMs(i *int64) *ToolInvocationUpdate {
	if i != nil {
		tiu.SetDurationMs(*i)
	}
	return tiu
}

// AddDurationMs adds i to the "duration_ms" field.
func (tiu *ToolInvocationUpdate) AddDurationMs(i int64) *ToolInvocationUpdate {
	tiu.mutation.AddDurationMs(i)
	return tiu
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (tiu *ToolInvocationUpdate) ClearDurationMs() *ToolInvocationUpdate {
	tiu.mutation.ClearDurationMs()
	return tiu
}

// SetRequestSizeBytes sets the "request_size_bytes" field.
func (tiu *ToolInvocationUpdate) SetRequestSizeBytes(i int) *ToolInvocationUpdate {
	tiu.mutation.ResetRequestSizeBytes()
	tiu.mutation.SetRequestSizeBytes(i)
	return tiu
}

// SetNillableRequestSizeBytes sets the "request_size_bytes" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableRequestSizeBytes(i *int) *ToolInvocationUpdate {
	if i != nil {
		tiu.SetRequestSizeBytes(*i)
	}
	return tiu
}

// AddRequestSizeBytes adds i to the "request_size_bytes" field.
func (tiu *ToolInvocationUpdate) AddRequestSizeBytes(i int) *ToolInvocationUpdate {
	tiu.mutation.AddRequestSizeBytes(i)
	return tiu
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (tiu *ToolInvocationUpdate) SetResponseSizeBytes(i int) *ToolInvocationUpdate {
	tiu.mutation.ResetResponseSizeBytes()
	tiu.mutation.SetResponseSizeBytes(i)
	return tiu
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableResponseSizeBytes(i *int) *ToolInvocationUpdate {
	if i != nil {
		tiu.SetResponseSizeBytes(*i)
	}
	return tiu
}

// AddResponseSizeBytes adds i to the "response_size_bytes" field.
func (tiu *ToolInvocationUpdate) AddResponseSizeBytes(i int) *ToolInvocationUpdate {
	tiu.mutation.AddResponseSizeBytes(i)
	return tiu
}

// SetRetryCount sets the "retry_count" field.
func (tiu *ToolInvocationUpdate) SetRetryCount(i int) *ToolInvocationUpdate {
	tiu.mutation.ResetRetryCount()
	tiu.mutation.SetRetryCount(i)
	return tiu
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableRetryCount(i *int) *ToolInvocationUpdate {
	if i != nil {
		tiu.SetRetryCount(*i)
	}
	return tiu
}

// AddRetryCount adds i to the "retry_count" field.
func (tiu *ToolInvocationUpdate) AddRetryCount(i int) *ToolInvocationUpdate {
	tiu.mutation.AddRetryCount(i)
	return tiu
}

// SetErrorType sets the "error_type" field.
func (tiu *ToolInvocationUpdate) SetErrorType(s string) *ToolInvocationUpdate {
	tiu.mutation.SetErrorType(s)
	return tiu
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableErrorType(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetErrorType(*s)
	}
	return tiu
}

// ClearErrorType clears the value of the "error_type" field.
func (tiu *ToolInvocationUpdate) ClearErrorType() *ToolInvocationUpdate {
	tiu.mutation.ClearErrorType()
	return tiu
}

// SetErrorMessage sets the "error_message" field.
func (tiu *ToolInvocationUpdate) SetErrorMessage(s string) *ToolInvocationUpdate {
	tiu.mutation.SetErrorMessage(s)
	return tiu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableErrorMessage(s *string) *ToolInvocationUpdate {
	if s != nil {
		tiu.SetErrorMessage(*s)
	}
	return tiu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (tiu *ToolInvocationUpdate) ClearErrorMessage() *ToolInvocationUpdate {
	tiu.mutation.ClearErrorMessage()
	return tiu
}

// SetEndedAt sets the "ended_at" field.
func (tiu *ToolInvocationUpdate) SetEndedAt(t time.Time) *ToolInvocationUpdate {
	tiu.mutation.SetEndedAt(t)
	return tiu
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (tiu *ToolInvocationUpdate) SetNillableEndedAt(t *time.Time) *ToolInvocationUpdate {
	if t != nil {
		tiu.SetEndedAt(*t)
	}
	return tiu
}

// ClearEndedAt clears the value of the "ended_at" field.
func (tiu *ToolInvocationUpdate) ClearEndedAt() *ToolInvocationUpdate {
	tiu.mutation.ClearEndedAt()
	return tiu
}

// SetUpdatedAt sets the "updated_at" field.
func (tiu *ToolInvocationUpdate) SetUpdatedAt(t time.Time) *ToolInvocationUpdate {
	tiu.mutation.SetUpdatedAt(t)
	return tiu
}

// SetTask sets the "task" edge to the AgentTask entity.
func (tiu *ToolInvocationUpdate) SetTask(a *AgentTask) *ToolInvocationUpdate {
	return tiu.SetTaskID(a.ID)
}

// Mutation returns the ToolInvocationMutation object of the builder.
func (tiu *ToolInvocationUpdate) Mutation() *ToolInvocationMutation {
	return tiu.mutation
}

// ClearTask clears the "task" edge to the AgentTask entity.
func (tiu *ToolInvocationUpdate) ClearTask() *ToolInvocationUpdate {
	tiu.mutation.ClearTask()
	return tiu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tiu *ToolInvocationUpdate) Save(ctx context.Context) (int, error) {
	tiu.defaults()
	return withHooks(ctx, tiu.sqlSave, tiu.mutation, tiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tiu *ToolInvocationUpdate) SaveX(ctx context.Context) int {
	affected, err := tiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tiu *ToolInvocationUpdate) Exec(ctx context.Context) error {
	_, err := tiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tiu *ToolInvocationUpdate) ExecX(ctx context.Context) {
	if err := tiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tiu *ToolInvocationUpdate) defaults() {
	if _, ok := tiu.mutation.UpdatedAt(); !ok {
		v := toolinvocation.UpdateDefaultUpdatedAt()
		tiu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tiu *ToolInvocationUpdate) check() error {
	if v, ok := tiu.mutation.AgentID(); ok {
		if err := toolinvocation.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.agent_id": %w`, err)}
		}
	}
	if v, ok := tiu.mutation.ToolName(); ok {
		if err := toolinvocation.ToolNameValidator(v); err != nil {
			return &ValidationError{Name: "tool_name", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.tool_name": %w`, err)}
		}
	}
	return nil
}

func (tiu *ToolInvocationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(toolinvocation.Table, toolinvocation.Columns, sqlgraph.NewFieldSpec(toolinvocation.FieldID, field.TypeString))
	if ps := tiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tiu.mutation.AgentID(); ok {
		_spec.SetField(toolinvocation.FieldAgentID, field.TypeString, value)
	}
	if value, ok := tiu.mutation.ToolName(); ok {
		_spec.SetField(toolinvocation.FieldToolName, field.TypeString, value)
	}
	if value, ok := tiu.mutation.ToolType(); ok {
		_spec.SetField(toolinvocation.FieldToolType, field.TypeString, value)
	}
	if tiu.mutation.ToolTypeCleared() {
		_spec.ClearField(toolinvocation.FieldToolType, field.TypeString)
	}
	if value, ok := tiu.mutation.Status(); ok {
		_spec.SetField(toolinvocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := tiu.mutation.TraceID(); ok {
		_spec.SetField(toolinvocation.FieldTraceID, field.TypeString, value)
	}
	if tiu.mutation.TraceIDCleared() {
		_spec.ClearField(toolinvocation.FieldTraceID, field.TypeString)
	}
	if value, ok := tiu.mutation.SpanID(); ok {
		_spec.SetField(toolinvocation.FieldSpanID, field.TypeString, value)
	}
	if tiu.mutation.SpanIDCleared() {
		_spec.ClearField(toolinvocation.FieldSpanID, field.TypeString)
	}
	if value, ok := tiu.mutation.Input(); ok {
		_spec.SetField(toolinvocation.FieldInput, field.TypeJSON, value)
	}
	if tiu.mutation.InputCleared() {
		_spec.ClearField(toolinvocation.FieldInput, field.TypeJSON)
	}
	if value, ok := tiu.mutation.Output(); ok {
		_spec.SetField(toolinvocation.FieldOutput, field.TypeJSON, value)
	}
	if tiu.mutation.OutputCleared() {
		_spec.ClearField(toolinvocation.FieldOutput, field.TypeJSON)
	}
	if value, ok := tiu.mutation.Metadata(); ok {
		_spec.SetField(toolinvocation.FieldMetadata, field.TypeJSON, value)
	}
	if tiu.mutation.MetadataCleared() {
		_spec.ClearField(toolinvocation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := tiu.mutation.HTTPMethod(); ok {
		_spec.SetField(toolinvocation.FieldHTTPMethod, field.TypeString, value)
	}
	if tiu.mutation.HTTPMethodCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPMethod, field.TypeString)
	}
	if value, ok := tiu.mutation.HTTPURL(); ok {
		_spec.SetField(toolinvocation.FieldHTTPURL, field.TypeString, value)
	}
	if tiu.mutation.HTTPURLCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPURL, field.TypeString)
	}
	if value, ok := tiu.mutation.HTTPStatusCode(); ok {
		_spec.SetField(toolinvocation.FieldHTTPStatusCode, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.AddedHTTPStatusCode(); ok {
		_spec.AddField(toolinvocation.FieldHTTPStatusCode, field.TypeInt, value)
	}
	if tiu.mutation.HTTPStatusCodeCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPStatusCode, field.TypeInt)
	}
	if value, ok := tiu.mutation.DurationMs(); ok {
		_spec.SetField(toolinvocation.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := tiu.mutation.AddedDurationMs(); ok {
		_spec.AddField(toolinvocation.FieldDurationMs, field.TypeInt64, value)
	}
	if tiu.mutation.DurationMsCleared() {
		_spec.ClearField(toolinvocation.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := tiu.mutation.RequestSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldRequestSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.AddedRequestSizeBytes(); ok {
		_spec.AddField(toolinvocation.FieldRequestSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(toolinvocation.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.RetryCount(); ok {
		_spec.SetField(toolinvocation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.AddedRetryCount(); ok {
		_spec.AddField(toolinvocation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := tiu.mutation.ErrorType(); ok {
		_spec.SetField(toolinvocation.FieldErrorType, field.TypeString, value)
	}
	if tiu.mutation.ErrorTypeCleared() {
		_spec.ClearField(toolinvocation.FieldErrorType, field.TypeString)
	}
	if value, ok := tiu.mutation.ErrorMessage(); ok {
		_spec.SetField(toolinvocation.FieldErrorMessage, field.TypeString, value)
	}
	if tiu.mutation.ErrorMessageCleared() {
		_spec.ClearField(toolinvocation.FieldErrorMessage, field.TypeString)
	}
	if value, ok := tiu.mutation.EndedAt(); ok {
		_spec.SetField(toolinvocation.FieldEndedAt, field.TypeTime, value)
	}
	if tiu.mutation.EndedAtCleared() {
		_spec.ClearField(toolinvocation.FieldEndedAt, field.TypeTime)
	}
	if value, ok := tiu.mutation.UpdatedAt(); ok {
		_spec.SetField(toolinvocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if tiu.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.TaskTable,
			Columns: []string{toolinvocation.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tiu.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.TaskTable,
			Columns: []string{toolinvocation.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolinvocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tiu.mutation.done = true
	return n, nil
}

// ToolInvocationUpdateOne is the builder for updating a single ToolInvocation entity.
type ToolInvocationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToolInvocationMutation
}

// SetTaskID sets the "task_id" field.
func (tiuo *ToolInvocationUpdateOne) SetTaskID(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetTaskID(s)
	return tiuo
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableTaskID(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetTaskID(*s)
	}
	return tiuo
}

// ClearTaskID clears the value of the "task_id" field.
func (tiuo *ToolInvocationUpdateOne) ClearTaskID() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearTaskID()
	return tiuo
}

// SetAgentID sets the "agent_id" field.
func (tiuo *ToolInvocationUpdateOne) SetAgentID(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetAgentID(s)
	return tiuo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableAgentID(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetAgentID(*s)
	}
	return tiuo
}

// SetToolName sets the "tool_name" field.
func (tiuo *ToolInvocationUpdateOne) SetToolName(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetToolName(s)
	return tiuo
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableToolName(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetToolName(*s)
	}
	return tiuo
}

// SetToolType sets the "tool_type" field.
func (tiuo *ToolInvocationUpdateOne) SetToolType(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetToolType(s)
	return tiuo
}

// SetNillableToolType sets the "tool_type" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableToolType(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetToolType(*s)
	}
	return tiuo
}

// ClearToolType clears the value of the "tool_type" field.
func (tiuo *ToolInvocationUpdateOne) ClearToolType() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearToolType()
	return tiuo
}

// SetStatus sets the "status" field.
func (tiuo *ToolInvocationUpdateOne) SetStatus(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetStatus(s)
	return tiuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableStatus(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetStatus(*s)
	}
	return tiuo
}

// SetTraceID sets the "trace_id" field.
func (tiuo *ToolInvocationUpdateOne) SetTraceID(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetTraceID(s)
	return tiuo
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableTraceID(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetTraceID(*s)
	}
	return tiuo
}

// ClearTraceID clears the value of the "trace_id" field.
func (tiuo *ToolInvocationUpdateOne) ClearTraceID() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearTraceID()
	return tiuo
}

// SetSpanID sets the "span_id" field.
func (tiuo *ToolInvocationUpdateOne) SetSpanID(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetSpanID(s)
	return tiuo
}

// SetNillableSpanID sets the "span_id" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableSpanID(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetSpanID(*s)
	}
	return tiuo
}

// ClearSpanID clears the value of the "span_id" field.
func (tiuo *ToolInvocationUpdateOne) ClearSpanID() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearSpanID()
	return tiuo
}

// SetInput sets the "input" field.
func (tiuo *ToolInvocationUpdateOne) SetInput(m map[string]interface{}) *ToolInvocationUpdateOne {
	tiuo.mutation.SetInput(m)
	return tiuo
}

// ClearInput clears the value of the "input" field.
func (tiuo *ToolInvocationUpdateOne) ClearInput() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearInput()
	return tiuo
}

// SetOutput sets the "output" field.
func (tiuo *ToolInvocationUpdateOne) SetOutput(m map[string]interface{}) *ToolInvocationUpdateOne {
	tiuo.mutation.SetOutput(m)
	return tiuo
}

// ClearOutput clears the value of the "output" field.
func (tiuo *ToolInvocationUpdateOne) ClearOutput() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearOutput()
	return tiuo
}

// SetMetadata sets the "metadata" field.
func (tiuo *ToolInvocationUpdateOne) SetMetadata(m map[string]interface{}) *ToolInvocationUpdateOne {
	tiuo.mutation.SetMetadata(m)
	return tiuo
}

// ClearMetadata clears the value of the "metadata" field.
func (tiuo *ToolInvocationUpdateOne) ClearMetadata() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearMetadata()
	return tiuo
}

// SetHTTPMethod sets the "http_method" field.
func (tiuo *ToolInvocationUpdateOne) SetHTTPMethod(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetHTTPMethod(s)
	return tiuo
}

// SetNillableHTTPMethod sets the "http_method" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableHTTPMethod(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetHTTPMethod(*s)
	}
	return tiuo
}

// ClearHTTPMethod clears the value of the "http_method" field.
func (tiuo *ToolInvocationUpdateOne) ClearHTTPMethod() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearHTTPMethod()
	return tiuo
}

// SetHTTPURL sets the "http_url" field.
func (tiuo *ToolInvocationUpdateOne) SetHTTPURL(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetHTTPURL(s)
	return tiuo
}

// SetNillableHTTPURL sets the "http_url" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableHTTPURL(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetHTTPURL(*s)
	}
	return tiuo
}

// ClearHTTPURL clears the value of the "http_url" field.
func (tiuo *ToolInvocationUpdateOne) ClearHTTPURL() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearHTTPURL()
	return tiuo
}

// SetHTTPStatusCode sets the "http_status_code" field.
func (tiuo *ToolInvocationUpdateOne) SetHTTPStatusCode(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.ResetHTTPStatusCode()
	tiuo.mutation.SetHTTPStatusCode(i)
	return tiuo
}

// SetNillableHTTPStatusCode sets the "http_status_code" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableHTTPStatusCode(i *int) *ToolInvocationUpdateOne {
	if i != nil {
		tiuo.SetHTTPStatusCode(*i)
	}
	return tiuo
}

// AddHTTPStatusCode adds i to the "http_status_code" field.
func (tiuo *ToolInvocationUpdateOne) AddHTTPStatusCode(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.AddHTTPStatusCode(i)
	return tiuo
}

// ClearHTTPStatusCode clears the value of the "http_status_code" field.
func (tiuo *ToolInvocationUpdateOne) ClearHTTPStatusCode() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearHTTPStatusCode()
	return tiuo
}

// SetDurationMs sets the "duration_ms" field.
func (tiuo *ToolInvocationUpdateOne) SetDurationMs(i int64) *ToolInvocationUpdateOne {
	tiuo.mutation.ResetDurationMs()
	tiuo.mutation.SetDurationMs(i)
	return tiuo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableDurationMs(i *int64) *ToolInvocationUpdateOne {
	if i != nil {
		tiuo.SetDurationMs(*i)
	}
	return tiuo
}

// AddDurationMs adds i to the "duration_ms" field.
func (tiuo *ToolInvocationUpdateOne) AddDurationMs(i int64) *ToolInvocationUpdateOne {
	tiuo.mutation.AddDurationMs(i)
	return tiuo
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (tiuo *ToolInvocationUpdateOne) ClearDurationMs() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearDurationMs()
	return tiuo
}

// SetRequestSizeBytes sets the "request_size_bytes" field.
func (tiuo *ToolInvocationUpdateOne) SetRequestSizeBytes(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.ResetRequestSizeBytes()
	tiuo.mutation.SetRequestSizeBytes(i)
	return tiuo
}

// SetNillableRequestSizeBytes sets the "request_size_bytes" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableRequestSizeBytes(i *int) *ToolInvocationUpdateOne {
	if i != nil {
		tiuo.SetRequestSizeBytes(*i)
	}
	return tiuo
}

// AddRequestSizeBytes adds i to the "request_size_bytes" field.
func (tiuo *ToolInvocationUpdateOne) AddRequestSizeBytes(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.AddRequestSizeBytes(i)
	return tiuo
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (tiuo *ToolInvocationUpdateOne) SetResponseSizeBytes(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.ResetResponseSizeBytes()
	tiuo.mutation.SetResponseSizeBytes(i)
	return tiuo
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableResponseSizeBytes(i *int) *ToolInvocationUpdateOne {
	if i != nil {
		tiuo.SetResponseSizeBytes(*i)
	}
	return tiuo
}

// AddResponseSizeBytes adds i to the "response_size_bytes" field.
func (tiuo *ToolInvocationUpdateOne) AddResponseSizeBytes(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.AddResponseSizeBytes(i)
	return tiuo
}

// SetRetryCount sets the "retry_count" field.
func (tiuo *ToolInvocationUpdateOne) SetRetryCount(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.ResetRetryCount()
	tiuo.mutation.SetRetryCount(i)
	return tiuo
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableRetryCount(i *int) *ToolInvocationUpdateOne {
	if i != nil {
		tiuo.SetRetryCount(*i)
	}
	return tiuo
}

// AddRetryCount adds i to the "retry_count" field.
func (tiuo *ToolInvocationUpdateOne) AddRetryCount(i int) *ToolInvocationUpdateOne {
	tiuo.mutation.AddRetryCount(i)
	return tiuo
}

// SetErrorType sets the "error_type" field.
func (tiuo *ToolInvocationUpdateOne) SetErrorType(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetErrorType(s)
	return tiuo
}

// SetNillableErrorType sets the "error_type" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableErrorType(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetErrorType(*s)
	}
	return tiuo
}

// ClearErrorType clears the value of the "error_type" field.
func (tiuo *ToolInvocationUpdateOne) ClearErrorType() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearErrorType()
	return tiuo
}

// SetErrorMessage sets the "error_message" field.
func (tiuo *ToolInvocationUpdateOne) SetErrorMessage(s string) *ToolInvocationUpdateOne {
	tiuo.mutation.SetErrorMessage(s)
	return tiuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableErrorMessage(s *string) *ToolInvocationUpdateOne {
	if s != nil {
		tiuo.SetErrorMessage(*s)
	}
	return tiuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (tiuo *ToolInvocationUpdateOne) ClearErrorMessage() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearErrorMessage()
	return tiuo
}

// SetEndedAt sets the "ended_at" field.
func (tiuo *ToolInvocationUpdateOne) SetEndedAt(t time.Time) *ToolInvocationUpdateOne {
	tiuo.mutation.SetEndedAt(t)
	return tiuo
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (tiuo *ToolInvocationUpdateOne) SetNillableEndedAt(t *time.Time) *ToolInvocationUpdateOne {
	if t != nil {
		tiuo.SetEndedAt(*t)
	}
	return tiuo
}

// ClearEndedAt clears the value of the "ended_at" field.
func (tiuo *ToolInvocationUpdateOne) ClearEndedAt() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearEndedAt()
	return tiuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tiuo *ToolInvocationUpdateOne) SetUpdatedAt(t time.Time) *ToolInvocationUpdateOne {
	tiuo.mutation.SetUpdatedAt(t)
	return tiuo
}

// SetTask sets the "task" edge to the AgentTask entity.
func (tiuo *ToolInvocationUpdateOne) SetTask(a *AgentTask) *ToolInvocationUpdateOne {
	return tiuo.SetTaskID(a.ID)
}

// Mutation returns the ToolInvocationMutation object of the builder.
func (tiuo *ToolInvocationUpdateOne) Mutation() *ToolInvocationMutation {
	return tiuo.mutation
}

// ClearTask clears the "task" edge to the AgentTask entity.
func (tiuo *ToolInvocationUpdateOne) ClearTask() *ToolInvocationUpdateOne {
	tiuo.mutation.ClearTask()
	return tiuo
}

// Where appends a list predicates to the ToolInvocationUpdate builder.
func (tiuo *ToolInvocationUpdateOne) Where(ps ...predicate.ToolInvocation) *ToolInvocationUpdateOne {
	tiuo.mutation.Where(ps...)
	return tiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tiuo *ToolInvocationUpdateOne) Select(field string, fields ...string) *ToolInvocationUpdateOne {
	tiuo.fields = append([]string{field}, fields...)
	return tiuo
}

// Save executes the query and returns the updated ToolInvocation entity.
func (tiuo *ToolInvocationUpdateOne) Save(ctx context.Context) (*ToolInvocation, error) {
	tiuo.defaults()
	return withHooks(ctx, tiuo.sqlSave, tiuo.mutation, tiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tiuo *ToolInvocationUpdateOne) SaveX(ctx context.Context) *ToolInvocation {
	node, err := tiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tiuo *ToolInvocationUpdateOne) Exec(ctx context.Context) error {
	_, err := tiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tiuo *ToolInvocationUpdateOne) ExecX(ctx context.Context) {
	if err := tiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tiuo *ToolInvocationUpdateOne) defaults() {
	if _, ok := tiuo.mutation.UpdatedAt(); !ok {
		v := toolinvocation.UpdateDefaultUpdatedAt()
		tiuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tiuo *ToolInvocationUpdateOne) check() error {
	if v, ok := tiuo.mutation.AgentID(); ok {
		if err := toolinvocation.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.agent_id": %w`, err)}
		}
	}
	if v, ok := tiuo.mutation.ToolName(); ok {
		if err := toolinvocation.ToolNameValidator(v); err != nil {
			return &ValidationError{Name: "tool_name", err: fmt.Errorf(`ent: validator failed for field "ToolInvocation.tool_name": %w`, err)}
		}
	}
	return nil
}

func (tiuo *ToolInvocationUpdateOne) sqlSave(ctx context.Context) (_node *ToolInvocation, err error) {
	if err := tiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(toolinvocation.Table, toolinvocation.Columns, sqlgraph.NewFieldSpec(toolinvocation.FieldID, field.TypeString))
	id, ok := tiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ToolInvocation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, toolinvocation.FieldID)
		for _, f := range fields {
			if !toolinvocation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != toolinvocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tiuo.mutation.AgentID(); ok {
		_spec.SetField(toolinvocation.FieldAgentID, field.TypeString, value)
	}
	if value, ok := tiuo.mutation.ToolName(); ok {
		_spec.SetField(toolinvocation.FieldToolName, field.TypeString, value)
	}
	if value, ok := tiuo.mutation.ToolType(); ok {
		_spec.SetField(toolinvocation.FieldToolType, field.TypeString, value)
	}
	if tiuo.mutation.ToolTypeCleared() {
		_spec.ClearField(toolinvocation.FieldToolType, field.TypeString)
	}
	if value, ok := tiuo.mutation.Status(); ok {
		_spec.SetField(toolinvocation.FieldStatus, field.TypeString, value)
	}
	if value, ok := tiuo.mutation.TraceID(); ok {
		_spec.SetField(toolinvocation.FieldTraceID, field.TypeString, value)
	}
	if tiuo.mutation.TraceIDCleared() {
		_spec.ClearField(toolinvocation.FieldTraceID, field.TypeString)
	}
	if value, ok := tiuo.mutation.SpanID(); ok {
		_spec.SetField(toolinvocation.FieldSpanID, field.TypeString, value)
	}
	if tiuo.mutation.SpanIDCleared() {
		_spec.ClearField(toolinvocation.FieldSpanID, field.TypeString)
	}
	if value, ok := tiuo.mutation.Input(); ok {
		_spec.SetField(toolinvocation.FieldInput, field.TypeJSON, value)
	}
	if tiuo.mutation.InputCleared() {
		_spec.ClearField(toolinvocation.FieldInput, field.TypeJSON)
	}
	if value, ok := tiuo.mutation.Output(); ok {
		_spec.SetField(toolinvocation.FieldOutput, field.TypeJSON, value)
	}
	if tiuo.mutation.OutputCleared() {
		_spec.ClearField(toolinvocation.FieldOutput, field.TypeJSON)
	}
	if value, ok := tiuo.mutation.Metadata(); ok {
		_spec.SetField(toolinvocation.FieldMetadata, field.TypeJSON, value)
	}
	if tiuo.mutation.MetadataCleared() {
		_spec.ClearField(toolinvocation.FieldMetadata, field.TypeJSON)
	}
	if value, ok := tiuo.mutation.HTTPMethod(); ok {
		_spec.SetField(toolinvocation.FieldHTTPMethod, field.TypeString, value)
	}
	if tiuo.mutation.HTTPMethodCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPMethod, field.TypeString)
	}
	if value, ok := tiuo.mutation.HTTPURL(); ok {
		_spec.SetField(toolinvocation.FieldHTTPURL, field.TypeString, value)
	}
	if tiuo.mutation.HTTPURLCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPURL, field.TypeString)
	}
	if value, ok := tiuo.mutation.HTTPStatusCode(); ok {
		_spec.SetField(toolinvocation.FieldHTTPStatusCode, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.AddedHTTPStatusCode(); ok {
		_spec.AddField(toolinvocation.FieldHTTPStatusCode, field.TypeInt, value)
	}
	if tiuo.mutation.HTTPStatusCodeCleared() {
		_spec.ClearField(toolinvocation.FieldHTTPStatusCode, field.TypeInt)
	}
	if value, ok := tiuo.mutation.DurationMs(); ok {
		_spec.SetField(toolinvocation.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := tiuo.mutation.AddedDurationMs(); ok {
		_spec.AddField(toolinvocation.FieldDurationMs, field.TypeInt64, value)
	}
	if tiuo.mutation.DurationMsCleared() {
		_spec.ClearField(toolinvocation.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := tiuo.mutation.RequestSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldRequestSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.AddedRequestSizeBytes(); ok {
		_spec.AddField(toolinvocation.FieldRequestSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(toolinvocation.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(toolinvocation.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.RetryCount(); ok {
		_spec.SetField(toolinvocation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.AddedRetryCount(); ok {
		_spec.AddField(toolinvocation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := tiuo.mutation.ErrorType(); ok {
		_spec.SetField(toolinvocation.FieldErrorType, field.TypeString, value)
	}
	if tiuo.mutation.ErrorTypeCleared() {
		_spec.ClearField(toolinvocation.FieldErrorType, field.TypeString)
	}
	if value, ok := tiuo.mutation.ErrorMessage(); ok {
		_spec.SetField(toolinvocation.FieldErrorMessage, field.TypeString, value)
	}
	if tiuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(toolinvocation.FieldErrorMessage, field.TypeString)
	}
	if value, ok := tiuo.mutation.EndedAt(); ok {
		_spec.SetField(toolinvocation.FieldEndedAt, field.TypeTime, value)
	}
	if tiuo.mutation.EndedAtCleared() {
		_spec.ClearField(toolinvocation.FieldEndedAt, field.TypeTime)
	}
	if value, ok := tiuo.mutation.UpdatedAt(); ok {
		_spec.SetField(toolinvocation.FieldUpdatedAt, field.TypeTime, value)
	}
	if tiuo.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.TaskTable,
			Columns: []string{toolinvocation.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tiuo.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.TaskTable,
			Columns: []string{toolinvocation.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ToolInvocation{config: tiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolinvocation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tiuo.mutation.done = true
	return _node, nil
}
