// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/toolinvocation"
)

// ToolInvocation is the model entity for the ToolInvocation schema.
type ToolInvocation struct {
	config `json:"-"`
	// ID of the ent.
	// Unique invocation identifier (UUID)
	ID string `json:"id,omitempty"`
	// Parent task ID
	TaskID string `json:"task_id,omitempty"`
	// Agent that invoked the tool
	AgentID string `json:"agent_id,omitempty"`
	// Name of the tool (e.g., 'web_fetch', 'database_query', 'calculator')
	ToolName string `json:"tool_name,omitempty"`
	// Category of tool: http, database, file, function, external_api
	ToolType string `json:"tool_type,omitempty"`
	// Invocation status: running, success, failed, timeout
	Status string `json:"status,omitempty"`
	// OpenTelemetry trace ID
	TraceID string `json:"trace_id,omitempty"`
	// OpenTelemetry span ID
	SpanID string `json:"span_id,omitempty"`
	// Tool input/arguments
	Input map[string]interface{} `json:"input,omitempty"`
	// Tool output/result
	Output map[string]interface{} `json:"output,omitempty"`
	// Additional metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// HTTP method if applicable
	HTTPMethod string `json:"http_method,omitempty"`
	// HTTP URL if applicable
	HTTPURL string `json:"http_url,omitempty"`
	// HTTP status code if applicable
	HTTPStatusCode int `json:"http_status_code,omitempty"`
	// Invocation duration in milliseconds
	DurationMs int64 `json:"duration_ms,omitempty"`
	// Size of the request in bytes
	RequestSizeBytes int `json:"request_size_bytes,omitempty"`
	// Size of the response in bytes
	ResponseSizeBytes int `json:"response_size_bytes,omitempty"`
	// Number of retries
	RetryCount int `json:"retry_count,omitempty"`
	// Error type if invocation failed
	ErrorType string `json:"error_type,omitempty"`
	// Error message if invocation failed
	ErrorMessage string `json:"error_message,omitempty"`
	// When the invocation started
	StartedAt time.Time `json:"started_at,omitempty"`
	// When the invocation ended
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ToolInvocationQuery when eager-loading is set.
	Edges        ToolInvocationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ToolInvocationEdges holds the relations/edges for other nodes in the graph.
type ToolInvocationEdges struct {
	// Task holds the value of the task edge.
	Task *AgentTask `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ToolInvocationEdges) TaskOrErr() (*AgentTask, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: agenttask.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ToolInvocation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case toolinvocation.FieldInput, toolinvocation.FieldOutput, toolinvocation.FieldMetadata:
			values[i] = new([]byte)
		case toolinvocation.FieldHTTPStatusCode, toolinvocation.FieldDurationMs, toolinvocation.FieldRequestSizeBytes, toolinvocation.FieldResponseSizeBytes, toolinvocation.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case toolinvocation.FieldID, toolinvocation.FieldTaskID, toolinvocation.FieldAgentID, toolinvocation.FieldToolName, toolinvocation.FieldToolType, toolinvocation.FieldStatus, toolinvocation.FieldTraceID, toolinvocation.FieldSpanID, toolinvocation.FieldHTTPMethod, toolinvocation.FieldHTTPURL, toolinvocation.FieldErrorType, toolinvocation.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case toolinvocation.FieldStartedAt, toolinvocation.FieldEndedAt, toolinvocation.FieldCreatedAt, toolinvocation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ToolInvocation fields.
func (ti *ToolInvocation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case toolinvocation.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				ti.ID = value.String
			}
		case toolinvocation.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				ti.TaskID = value.String
			}
		case toolinvocation.FieldAgentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				ti.AgentID = value.String
			}
		case toolinvocation.FieldToolName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_name", values[i])
			} else if value.Valid {
				ti.ToolName = value.String
			}
		case toolinvocation.FieldToolType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_type", values[i])
			} else if value.Valid {
				ti.ToolType = value.String
			}
		case toolinvocation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ti.Status = value.String
			}
		case toolinvocation.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				ti.TraceID = value.String
			}
		case toolinvocation.FieldSpanID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field span_id", values[i])
			} else if value.Valid {
				ti.SpanID = value.String
			}
		case toolinvocation.FieldInput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field input", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ti.Input); err != nil {
					return fmt.Errorf("unmarshal field input: %w", err)
				}
			}
		case toolinvocation.FieldOutput:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ti.Output); err != nil {
					return fmt.Errorf("unmarshal field output: %w", err)
				}
			}
		case toolinvocation.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ti.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case toolinvocation.FieldHTTPMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field http_method", values[i])
			} else if value.Valid {
				ti.HTTPMethod = value.String
			}
		case toolinvocation.FieldHTTPURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field http_url", values[i])
			} else if value.Valid {
				ti.HTTPURL = value.String
			}
		case toolinvocation.FieldHTTPStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field http_status_code", values[i])
			} else if value.Valid {
				ti.HTTPStatusCode = int(value.Int64)
			}
		case toolinvocation.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				ti.DurationMs = value.Int64
			}
		case toolinvocation.FieldRequestSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_size_bytes", values[i])
			} else if value.Valid {
				ti.RequestSizeBytes = int(value.Int64)
			}
		case toolinvocation.FieldResponseSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_size_bytes", values[i])
			} else if value.Valid {
				ti.ResponseSizeBytes = int(value.Int64)
			}
		case toolinvocation.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				ti.RetryCount = int(value.Int64)
			}
		case toolinvocation.FieldErrorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_type", values[i])
			} else if value.Valid {
				ti.ErrorType = value.String
			}
		case toolinvocation.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				ti.ErrorMessage = value.String
			}
		case toolinvocation.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				ti.StartedAt = value.Time
			}
		case toolinvocation.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				ti.EndedAt = new(time.Time)
				*ti.EndedAt = value.Time
			}
		case toolinvocation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ti.CreatedAt = value.Time
			}
		case toolinvocation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ti.UpdatedAt = value.Time
			}
		default:
			ti.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ToolInvocation.
// This includes values selected through modifiers, order, etc.
func (ti *ToolInvocation) Value(name string) (ent.Value, error) {
	return ti.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the ToolInvocation entity.
func (ti *ToolInvocation) QueryTask() *AgentTaskQuery {
	return NewToolInvocationClient(ti.config).QueryTask(ti)
}

// Update returns a builder for updating this ToolInvocation.
// Note that you need to call ToolInvocation.Unwrap() before calling this method if this ToolInvocation
// was returned from a transaction, and the transaction was committed or rolled back.
func (ti *ToolInvocation) Update() *ToolInvocationUpdateOne {
	return NewToolInvocationClient(ti.config).UpdateOne(ti)
}

// Unwrap unwraps the ToolInvocation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ti *ToolInvocation) Unwrap() *ToolInvocation {
	_tx, ok := ti.config.driver.(*txDriver)
	if !ok {
		panic("ent: ToolInvocation is not a transactional entity")
	}
	ti.config.driver = _tx.drv
	return ti
}

// String implements the fmt.Stringer.
func (ti *ToolInvocation) String() string {
	var builder strings.Builder
	builder.WriteString("ToolInvocation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ti.ID))
	builder.WriteString("task_id=")
	builder.WriteString(ti.TaskID)
	builder.WriteString(", ")
	builder.WriteString("agent_id=")
	builder.WriteString(ti.AgentID)
	builder.WriteString(", ")
	builder.WriteString("tool_name=")
	builder.WriteString(ti.ToolName)
	builder.WriteString(", ")
	builder.WriteString("tool_type=")
	builder.WriteString(ti.ToolType)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ti.Status)
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(ti.TraceID)
	builder.WriteString(", ")
	builder.WriteString("span_id=")
	builder.WriteString(ti.SpanID)
	builder.WriteString(", ")
	builder.WriteString("input=")
	builder.WriteString(fmt.Sprintf("%v", ti.Input))
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(fmt.Sprintf("%v", ti.Output))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", ti.Metadata))
	builder.WriteString(", ")
	builder.WriteString("http_method=")
	builder.WriteString(ti.HTTPMethod)
	builder.WriteString(", ")
	builder.WriteString("http_url=")
	builder.WriteString(ti.HTTPURL)
	builder.WriteString(", ")
	builder.WriteString("http_status_code=")
	builder.WriteString(fmt.Sprintf("%v", ti.HTTPStatusCode))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", ti.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("request_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", ti.RequestSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("response_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", ti.ResponseSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", ti.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("error_type=")
	builder.WriteString(ti.ErrorType)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(ti.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(ti.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ti.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ti.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ti.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ToolInvocations is a parsable slice of ToolInvocation.
type ToolInvocations []*ToolInvocation
