// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/toolinvocation"
)

// ToolInvocationQuery is the builder for querying ToolInvocation entities.
type ToolInvocationQuery struct {
	config
	ctx        *QueryContext
	order      []toolinvocation.OrderOption
	inters     []Interceptor
	predicates []predicate.ToolInvocation
	withTask   *AgentTaskQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ToolInvocationQuery builder.
func (tiq *ToolInvocationQuery) Where(ps ...predicate.ToolInvocation) *ToolInvocationQuery {
	tiq.predicates = append(tiq.predicates, ps...)
	return tiq
}

// Limit the number of records to be returned by this query.
func (tiq *ToolInvocationQuery) Limit(limit int) *ToolInvocationQuery {
	tiq.ctx.Limit = &limit
	return tiq
}

// Offset to start from.
func (tiq *ToolInvocationQuery) Offset(offset int) *ToolInvocationQuery {
	tiq.ctx.Offset = &offset
	return tiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tiq *ToolInvocationQuery) Unique(unique bool) *ToolInvocationQuery {
	tiq.ctx.Unique = &unique
	return tiq
}

// Order specifies how the records should be ordered.
func (tiq *ToolInvocationQuery) Order(o ...toolinvocation.OrderOption) *ToolInvocationQuery {
	tiq.order = append(tiq.order, o...)
	return tiq
}

// QueryTask chains the current query on the "task" edge.
func (tiq *ToolInvocationQuery) QueryTask() *AgentTaskQuery {
	query := (&AgentTaskClient{config: tiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(toolinvocation.Table, toolinvocation.FieldID, selector),
			sqlgraph.To(agenttask.Table, agenttask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, toolinvocation.TaskTable, toolinvocation.TaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(tiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ToolInvocation entity from the query.
// Returns a *NotFoundError when no ToolInvocation was found.
func (tiq *ToolInvocationQuery) First(ctx context.Context) (*ToolInvocation, error) {
	nodes, err := tiq.Limit(1).All(setContextOp(ctx, tiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{toolinvocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tiq *ToolInvocationQuery) FirstX(ctx context.Context) *ToolInvocation {
	node, err := tiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ToolInvocation ID from the query.
// Returns a *NotFoundError when no ToolInvocation ID was found.
func (tiq *ToolInvocationQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tiq.Limit(1).IDs(setContextOp(ctx, tiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{toolinvocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tiq *ToolInvocationQuery) FirstIDX(ctx context.Context) string {
	id, err := tiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ToolInvocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ToolInvocation entity is found.
// Returns a *NotFoundError when no ToolInvocation entities are found.
func (tiq *ToolInvocationQuery) Only(ctx context.Context) (*ToolInvocation, error) {
	nodes, err := tiq.Limit(2).All(setContextOp(ctx, tiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{toolinvocation.Label}
	default:
		return nil, &NotSingularError{toolinvocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tiq *ToolInvocationQuery) OnlyX(ctx context.Context) *ToolInvocation {
	node, err := tiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ToolInvocation ID in the query.
// Returns a *NotSingularError when more than one ToolInvocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (tiq *ToolInvocationQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tiq.Limit(2).IDs(setContextOp(ctx, tiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{toolinvocation.Label}
	default:
		err = &NotSingularError{toolinvocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tiq *ToolInvocationQuery) OnlyIDX(ctx context.Context) string {
	id, err := tiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ToolInvocations.
func (tiq *ToolInvocationQuery) All(ctx context.Context) ([]*ToolInvocation, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryAll)
	if err := tiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ToolInvocation, *ToolInvocationQuery]()
	return withInterceptors[[]*ToolInvocation](ctx, tiq, qr, tiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tiq *ToolInvocationQuery) AllX(ctx context.Context) []*ToolInvocation {
	nodes, err := tiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ToolInvocation IDs.
func (tiq *ToolInvocationQuery) IDs(ctx context.Context) (ids []string, err error) {
	if tiq.ctx.Unique == nil && tiq.path != nil {
		tiq.Unique(true)
	}
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryIDs)
	if err = tiq.Select(toolinvocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tiq *ToolInvocationQuery) IDsX(ctx context.Context) []string {
	ids, err := tiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tiq *ToolInvocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryCount)
	if err := tiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tiq, querierCount[*ToolInvocationQuery](), tiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tiq *ToolInvocationQuery) CountX(ctx context.Context) int {
	count, err := tiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tiq *ToolInvocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tiq.ctx, ent.OpQueryExist)
	switch _, err := tiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tiq *ToolInvocationQuery) ExistX(ctx context.Context) bool {
	exist, err := tiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ToolInvocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tiq *ToolInvocationQuery) Clone() *ToolInvocationQuery {
	if tiq == nil {
		return nil
	}
	return &ToolInvocationQuery{
		config:     tiq.config,
		ctx:        tiq.ctx.Clone(),
		order:      append([]toolinvocation.OrderOption{}, tiq.order...),
		inters:     append([]Interceptor{}, tiq.inters...),
		predicates: append([]predicate.ToolInvocation{}, tiq.predicates...),
		withTask:   tiq.withTask.Clone(),
		// clone intermediate query.
		sql:  tiq.sql.Clone(),
		path: tiq.path,
	}
}

// WithTask tells the query-builder to eager-load the nodes that are connected to
// the "task" edge. The optional arguments are used to configure the query builder of the edge.
func (tiq *ToolInvocationQuery) WithTask(opts ...func(*AgentTaskQuery)) *ToolInvocationQuery {
	query := (&AgentTaskClient{config: tiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tiq.withTask = query
	return tiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ToolInvocation.Query().
//		GroupBy(toolinvocation.FieldTaskID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tiq *ToolInvocationQuery) GroupBy(field string, fields ...string) *ToolInvocationGroupBy {
	tiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ToolInvocationGroupBy{build: tiq}
	grbuild.flds = &tiq.ctx.Fields
	grbuild.label = toolinvocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TaskID string `json:"task_id,omitempty"`
//	}
//
//	client.ToolInvocation.Query().
//		Select(toolinvocation.FieldTaskID).
//		Scan(ctx, &v)
func (tiq *ToolInvocationQuery) Select(fields ...string) *ToolInvocationSelect {
	tiq.ctx.Fields = append(tiq.ctx.Fields, fields...)
	sbuild := &ToolInvocationSelect{ToolInvocationQuery: tiq}
	sbuild.label = toolinvocation.Label
	sbuild.flds, sbuild.scan = &tiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ToolInvocationSelect configured with the given aggregations.
func (tiq *ToolInvocationQuery) Aggregate(fns ...AggregateFunc) *ToolInvocationSelect {
	return tiq.Select().Aggregate(fns...)
}

func (tiq *ToolInvocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tiq); err != nil {
				return err
			}
		}
	}
	for _, f := range tiq.ctx.Fields {
		if !toolinvocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tiq.path != nil {
		prev, err := tiq.path(ctx)
		if err != nil {
			return err
		}
		tiq.sql = prev
	}
	return nil
}

func (tiq *ToolInvocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ToolInvocation, error) {
	var (
		nodes       = []*ToolInvocation{}
		_spec       = tiq.querySpec()
		loadedTypes = [1]bool{
			tiq.withTask != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ToolInvocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ToolInvocation{config: tiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tiq.withTask; query != nil {
		if err := tiq.loadTask(ctx, query, nodes, nil,
			func(n *ToolInvocation, e *AgentTask) { n.Edges.Task = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tiq *ToolInvocationQuery) loadTask(ctx context.Context, query *AgentTaskQuery, nodes []*ToolInvocation, init func(*ToolInvocation), assign func(*ToolInvocation, *AgentTask)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ToolInvocation)
	for i := range nodes {
		fk := nodes[i].TaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agenttask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tiq *ToolInvocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tiq.querySpec()
	_spec.Node.Columns = tiq.ctx.Fields
	if len(tiq.ctx.Fields) > 0 {
		_spec.Unique = tiq.ctx.Unique != nil && *tiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tiq.driver, _spec)
}

func (tiq *ToolInvocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(toolinvocation.Table, toolinvocation.Columns, sqlgraph.NewFieldSpec(toolinvocation.FieldID, field.TypeString))
	_spec.From = tiq.sql
	if unique := tiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tiq.path != nil {
		_spec.Unique = true
	}
	if fields := tiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, toolinvocation.FieldID)
		for i := range fields {
			if fields[i] != toolinvocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tiq.withTask != nil {
			_spec.Node.AddColumnOnce(toolinvocation.FieldTaskID)
		}
	}
	if ps := tiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tiq *ToolInvocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tiq.driver.Dialect())
	t1 := builder.Table(toolinvocation.Table)
	columns := tiq.ctx.Fields
	if len(columns) == 0 {
		columns = toolinvocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tiq.sql != nil {
		selector = tiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tiq.ctx.Unique != nil && *tiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tiq.predicates {
		p(selector)
	}
	for _, p := range tiq.order {
		p(selector)
	}
	if offset := tiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ToolInvocationGroupBy is the group-by builder for ToolInvocation entities.
type ToolInvocationGroupBy struct {
	selector
	build *ToolInvocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tigb *ToolInvocationGroupBy) Aggregate(fns ...AggregateFunc) *ToolInvocationGroupBy {
	tigb.fns = append(tigb.fns, fns...)
	return tigb
}

// Scan applies the selector query and scans the result into the given value.
func (tigb *ToolInvocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tigb.build.ctx, ent.OpQueryGroupBy)
	if err := tigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToolInvocationQuery, *ToolInvocationGroupBy](ctx, tigb.build, tigb, tigb.build.inters, v)
}

func (tigb *ToolInvocationGroupBy) sqlScan(ctx context.Context, root *ToolInvocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tigb.fns))
	for _, fn := range tigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tigb.flds)+len(tigb.fns))
		for _, f := range *tigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ToolInvocationSelect is the builder for selecting fields of ToolInvocation entities.
type ToolInvocationSelect struct {
	*ToolInvocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tis *ToolInvocationSelect) Aggregate(fns ...AggregateFunc) *ToolInvocationSelect {
	tis.fns = append(tis.fns, fns...)
	return tis
}

// Scan applies the selector query and scans the result into the given value.
func (tis *ToolInvocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tis.ctx, ent.OpQuerySelect)
	if err := tis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ToolInvocationQuery, *ToolInvocationSelect](ctx, tis.ToolInvocationQuery, tis, tis.inters, v)
}

func (tis *ToolInvocationSelect) sqlScan(ctx context.Context, root *ToolInvocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tis.fns))
	for _, fn := range tis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
