// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omniobserve/agentops/ent/agentevent"
	"github.com/plexusone/omniobserve/agentops/ent/agenthandoff"
	"github.com/plexusone/omniobserve/agentops/ent/agenttask"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
	"github.com/plexusone/omniobserve/agentops/ent/workflow"
)

// WorkflowUpdate is the builder for updating Workflow entities.
type WorkflowUpdate struct {
	config
	hooks    []Hook
	mutation *WorkflowMutation
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wu *WorkflowUpdate) Where(ps ...predicate.Workflow) *WorkflowUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetName sets the "name" field.
func (wu *WorkflowUpdate) SetName(s string) *WorkflowUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableName(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetStatus sets the "status" field.
func (wu *WorkflowUpdate) SetStatus(s string) *WorkflowUpdate {
	wu.mutation.SetStatus(s)
	return wu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableStatus(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetStatus(*s)
	}
	return wu
}

// SetTraceID sets the "trace_id" field.
func (wu *WorkflowUpdate) SetTraceID(s string) *WorkflowUpdate {
	wu.mutation.SetTraceID(s)
	return wu
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableTraceID(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetTraceID(*s)
	}
	return wu
}

// ClearTraceID clears the value of the "trace_id" field.
func (wu *WorkflowUpdate) ClearTraceID() *WorkflowUpdate {
	wu.mutation.ClearTraceID()
	return wu
}

// SetParentWorkflowID sets the "parent_workflow_id" field.
func (wu *WorkflowUpdate) SetParentWorkflowID(s string) *WorkflowUpdate {
	wu.mutation.SetParentWorkflowID(s)
	return wu
}

// SetNillableParentWorkflowID sets the "parent_workflow_id" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableParentWorkflowID(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetParentWorkflowID(*s)
	}
	return wu
}

// ClearParentWorkflowID clears the value of the "parent_workflow_id" field.
func (wu *WorkflowUpdate) ClearParentWorkflowID() *WorkflowUpdate {
	wu.mutation.ClearParentWorkflowID()
	return wu
}

// SetInitiator sets the "initiator" field.
func (wu *WorkflowUpdate) SetInitiator(s string) *WorkflowUpdate {
	wu.mutation.SetInitiator(s)
	return wu
}

// SetNillableInitiator sets the "initiator" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableInitiator(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetInitiator(*s)
	}
	return wu
}

// ClearInitiator clears the value of the "initiator" field.
func (wu *WorkflowUpdate) ClearInitiator() *WorkflowUpdate {
	wu.mutation.ClearInitiator()
	return wu
}

// SetInput sets the "input" field.
func (wu *WorkflowUpdate) SetInput(m map[string]interface{}) *WorkflowUpdate {
	wu.mutation.SetInput(m)
	return wu
}

// ClearInput clears the value of the "input" field.
func (wu *WorkflowUpdate) ClearInput() *WorkflowUpdate {
	wu.mutation.ClearInput()
	return wu
}

// SetOutput sets the "output" field.
func (wu *WorkflowUpdate) SetOutput(m map[string]interface{}) *WorkflowUpdate {
	wu.mutation.SetOutput(m)
	return wu
}

// ClearOutput clears the value of the "output" field.
func (wu *WorkflowUpdate) ClearOutput() *WorkflowUpdate {
	wu.mutation.ClearOutput()
	return wu
}

// SetMetadata sets the "metadata" field.
func (wu *WorkflowUpdate) SetMetadata(m map[string]interface{}) *WorkflowUpdate {
	wu.mutation.SetMetadata(m)
	return wu
}

// ClearMetadata clears the value of the "metadata" field.
func (wu *WorkflowUpdate) ClearMetadata() *WorkflowUpdate {
	wu.mutation.ClearMetadata()
	return wu
}

// SetTaskCount sets the "task_count" field.
func (wu *WorkflowUpdate) SetTaskCount(i int) *WorkflowUpdate {
	wu.mutation.ResetTaskCount()
	wu.mutation.SetTaskCount(i)
	return wu
}

// SetNillableTaskCount sets the "task_count" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableTaskCount(i *int) *WorkflowUpdate {
	if i != nil {
		wu.SetTaskCount(*i)
	}
	return wu
}

// AddTaskCount adds i to the "task_count" field.
func (wu *WorkflowUpdate) AddTaskCount(i int) *WorkflowUpdate {
	wu.mutation.AddTaskCount(i)
	return wu
}

// SetCompletedTaskCount sets the "completed_task_count" field.
func (wu *WorkflowUpdate) SetCompletedTaskCount(i int) *WorkflowUpdate {
	wu.mutation.ResetCompletedTaskCount()
	wu.mutation.SetCompletedTaskCount(i)
	return wu
}

// SetNillableCompletedTaskCount sets the "completed_task_count" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableCompletedTaskCount(i *int) *WorkflowUpdate {
	if i != nil {
		wu.SetCompletedTaskCount(*i)
	}
	return wu
}

// AddCompletedTaskCount adds i to the "completed_task_count" field.
func (wu *WorkflowUpdate) AddCompletedTaskCount(i int) *WorkflowUpdate {
	wu.mutation.AddCompletedTaskCount(i)
	return wu
}

// SetFailedTaskCount sets the "failed_task_count" field.
func (wu *WorkflowUpdate) SetFailedTaskCount(i int) *WorkflowUpdate {
	wu.mutation.ResetFailedTaskCount()
	wu.mutation.SetFailedTaskCount(i)
	return wu
}

// SetNillableFailedTaskCount sets the "failed_task_count" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableFailedTaskCount(i *int) *WorkflowUpdate {
	if i != nil {
		wu.SetFailedTaskCount(*i)
	}
	return wu
}

// AddFailedTaskCount adds i to the "failed_task_count" field.
func (wu *WorkflowUpdate) AddFailedTaskCount(i int) *WorkflowUpdate {
	wu.mutation.AddFailedTaskCount(i)
	return wu
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (wu *WorkflowUpdate) SetTotalCostUsd(f float64) *WorkflowUpdate {
	wu.mutation.ResetTotalCostUsd()
	wu.mutation.SetTotalCostUsd(f)
	return wu
}

// SetNillableTotalCostUsd sets the "total_cost_usd" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableTotalCostUsd(f *float64) *WorkflowUpdate {
	if f != nil {
		wu.SetTotalCostUsd(*f)
	}
	return wu
}

// AddTotalCostUsd adds f to the "total_cost_usd" field.
func (wu *WorkflowUpdate) AddTotalCostUsd(f float64) *WorkflowUpdate {
	wu.mutation.AddTotalCostUsd(f)
	return wu
}

// SetTotalTokens sets the "total_tokens" field.
func (wu *WorkflowUpdate) SetTotalTokens(i int) *WorkflowUpdate {
	wu.mutation.ResetTotalTokens()
	wu.mutation.SetTotalTokens(i)
	return wu
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableTotalTokens(i *int) *WorkflowUpdate {
	if i != nil {
		wu.SetTotalTokens(*i)
	}
	return wu
}

// AddTotalTokens adds i to the "total_tokens" field.
func (wu *WorkflowUpdate) AddTotalTokens(i int) *WorkflowUpdate {
	wu.mutation.AddTotalTokens(i)
	return wu
}

// SetDurationMs sets the "duration_ms" field.
func (wu *WorkflowUpdate) SetDurationMs(i int64) *WorkflowUpdate {
	wu.mutation.ResetDurationMs()
	wu.mutation.SetDurationMs(i)
	return wu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableDurationMs(i *int64) *WorkflowUpdate {
	if i != nil {
		wu.SetDurationMs(*i)
	}
	return wu
}

// AddDurationMs adds i to the "duration_ms" field.
func (wu *WorkflowUpdate) AddDurationMs(i int64) *WorkflowUpdate {
	wu.mutation.AddDurationMs(i)
	return wu
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (wu *WorkflowUpdate) ClearDurationMs() *WorkflowUpdate {
	wu.mutation.ClearDurationMs()
	return wu
}

// SetErrorMessage sets the "error_message" field.
func (wu *WorkflowUpdate) SetErrorMessage(s string) *WorkflowUpdate {
	wu.mutation.SetErrorMessage(s)
	return wu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableErrorMessage(s *string) *WorkflowUpdate {
	if s != nil {
		wu.SetErrorMessage(*s)
	}
	return wu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (wu *WorkflowUpdate) ClearErrorMessage() *WorkflowUpdate {
	wu.mutation.ClearErrorMessage()
	return wu
}

// SetEndedAt sets the "ended_at" field.
func (wu *WorkflowUpdate) SetEndedAt(t time.Time) *WorkflowUpdate {
	wu.mutation.SetEndedAt(t)
	return wu
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (wu *WorkflowUpdate) SetNillableEndedAt(t *time.Time) *WorkflowUpdate {
	if t != nil {
		wu.SetEndedAt(*t)
	}
	return wu
}

// ClearEndedAt clears the value of the "ended_at" field.
func (wu *WorkflowUpdate) ClearEndedAt() *WorkflowUpdate {
	wu.mutation.ClearEndedAt()
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WorkflowUpdate) SetUpdatedAt(t time.Time) *WorkflowUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// AddTaskIDs adds the "tasks" edge to the AgentTask entity by IDs.
func (wu *WorkflowUpdate) AddTaskIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.AddTaskIDs(ids...)
	return wu
}

// AddTasks adds the "tasks" edges to the AgentTask entity.
func (wu *WorkflowUpdate) AddTasks(a ...*AgentTask) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.AddTaskIDs(ids...)
}

// AddHandoffIDs adds the "handoffs" edge to the AgentHandoff entity by IDs.
func (wu *WorkflowUpdate) AddHandoffIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.AddHandoffIDs(ids...)
	return wu
}

// AddHandoffs adds the "handoffs" edges to the AgentHandoff entity.
func (wu *WorkflowUpdate) AddHandoffs(a ...*AgentHandoff) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.AddHandoffIDs(ids...)
}

// AddEventIDs adds the "events" edge to the AgentEvent entity by IDs.
func (wu *WorkflowUpdate) AddEventIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.AddEventIDs(ids...)
	return wu
}

// AddEvents adds the "events" edges to the AgentEvent entity.
func (wu *WorkflowUpdate) AddEvents(a ...*AgentEvent) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.AddEventIDs(ids...)
}

// Mutation returns the WorkflowMutation object of the builder.
func (wu *WorkflowUpdate) Mutation() *WorkflowMutation {
	return wu.mutation
}

// ClearTasks clears all "tasks" edges to the AgentTask entity.
func (wu *WorkflowUpdate) ClearTasks() *WorkflowUpdate {
	wu.mutation.ClearTasks()
	return wu
}

// RemoveTaskIDs removes the "tasks" edge to AgentTask entities by IDs.
func (wu *WorkflowUpdate) RemoveTaskIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.RemoveTaskIDs(ids...)
	return wu
}

// RemoveTasks removes "tasks" edges to AgentTask entities.
func (wu *WorkflowUpdate) RemoveTasks(a ...*AgentTask) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.RemoveTaskIDs(ids...)
}

// ClearHandoffs clears all "handoffs" edges to the AgentHandoff entity.
func (wu *WorkflowUpdate) ClearHandoffs() *WorkflowUpdate {
	wu.mutation.ClearHandoffs()
	return wu
}

// RemoveHandoffIDs removes the "handoffs" edge to AgentHandoff entities by IDs.
func (wu *WorkflowUpdate) RemoveHandoffIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.RemoveHandoffIDs(ids...)
	return wu
}

// RemoveHandoffs removes "handoffs" edges to AgentHandoff entities.
func (wu *WorkflowUpdate) RemoveHandoffs(a ...*AgentHandoff) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.RemoveHandoffIDs(ids...)
}

// ClearEvents clears all "events" edges to the AgentEvent entity.
func (wu *WorkflowUpdate) ClearEvents() *WorkflowUpdate {
	wu.mutation.ClearEvents()
	return wu
}

// RemoveEventIDs removes the "events" edge to AgentEvent entities by IDs.
func (wu *WorkflowUpdate) RemoveEventIDs(ids ...string) *WorkflowUpdate {
	wu.mutation.RemoveEventIDs(ids...)
	return wu
}

// RemoveEvents removes "events" edges to AgentEvent entities.
func (wu *WorkflowUpdate) RemoveEvents(a ...*AgentEvent) *WorkflowUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wu.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkflowUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkflowUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkflowUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkflowUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WorkflowUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *WorkflowUpdate) check() error {
	if v, ok := wu.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	return nil
}

func (wu *WorkflowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.Status(); ok {
		_spec.SetField(workflow.FieldStatus, field.TypeString, value)
	}
	if value, ok := wu.mutation.TraceID(); ok {
		_spec.SetField(workflow.FieldTraceID, field.TypeString, value)
	}
	if wu.mutation.TraceIDCleared() {
		_spec.ClearField(workflow.FieldTraceID, field.TypeString)
	}
	if value, ok := wu.mutation.ParentWorkflowID(); ok {
		_spec.SetField(workflow.FieldParentWorkflowID, field.TypeString, value)
	}
	if wu.mutation.ParentWorkflowIDCleared() {
		_spec.ClearField(workflow.FieldParentWorkflowID, field.TypeString)
	}
	if value, ok := wu.mutation.Initiator(); ok {
		_spec.SetField(workflow.FieldInitiator, field.TypeString, value)
	}
	if wu.mutation.InitiatorCleared() {
		_spec.ClearField(workflow.FieldInitiator, field.TypeString)
	}
	if value, ok := wu.mutation.Input(); ok {
		_spec.SetField(workflow.FieldInput, field.TypeJSON, value)
	}
	if wu.mutation.InputCleared() {
		_spec.ClearField(workflow.FieldInput, field.TypeJSON)
	}
	if value, ok := wu.mutation.Output(); ok {
		_spec.SetField(workflow.FieldOutput, field.TypeJSON, value)
	}
	if wu.mutation.OutputCleared() {
		_spec.ClearField(workflow.FieldOutput, field.TypeJSON)
	}
	if value, ok := wu.mutation.Metadata(); ok {
		_spec.SetField(workflow.FieldMetadata, field.TypeJSON, value)
	}
	if wu.mutation.MetadataCleared() {
		_spec.ClearField(workflow.FieldMetadata, field.TypeJSON)
	}
	if value, ok := wu.mutation.TaskCount(); ok {
		_spec.SetField(workflow.FieldTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedTaskCount(); ok {
		_spec.AddField(workflow.FieldTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.CompletedTaskCount(); ok {
		_spec.SetField(workflow.FieldCompletedTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedCompletedTaskCount(); ok {
		_spec.AddField(workflow.FieldCompletedTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.FailedTaskCount(); ok {
		_spec.SetField(workflow.FieldFailedTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedFailedTaskCount(); ok {
		_spec.AddField(workflow.FieldFailedTaskCount, field.TypeInt, value)
	}
	if value, ok := wu.mutation.TotalCostUsd(); ok {
		_spec.SetField(workflow.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := wu.mutation.AddedTotalCostUsd(); ok {
		_spec.AddField(workflow.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := wu.mutation.TotalTokens(); ok {
		_spec.SetField(workflow.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := wu.mutation.AddedTotalTokens(); ok {
		_spec.AddField(workflow.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := wu.mutation.DurationMs(); ok {
		_spec.SetField(workflow.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedDurationMs(); ok {
		_spec.AddField(workflow.FieldDurationMs, field.TypeInt64, value)
	}
	if wu.mutation.DurationMsCleared() {
		_spec.ClearField(workflow.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := wu.mutation.ErrorMessage(); ok {
		_spec.SetField(workflow.FieldErrorMessage, field.TypeString, value)
	}
	if wu.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflow.FieldErrorMessage, field.TypeString)
	}
	if value, ok := wu.mutation.EndedAt(); ok {
		_spec.SetField(workflow.FieldEndedAt, field.TypeTime, value)
	}
	if wu.mutation.EndedAtCleared() {
		_spec.ClearField(workflow.FieldEndedAt, field.TypeTime)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if wu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedTasksIDs(); len(nodes) > 0 && !wu.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.HandoffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedHandoffsIDs(); len(nodes) > 0 && !wu.mutation.HandoffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.HandoffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wu.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedEventsIDs(); len(nodes) > 0 && !wu.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkflowUpdateOne is the builder for updating a single Workflow entity.
type WorkflowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkflowMutation
}

// SetName sets the "name" field.
func (wuo *WorkflowUpdateOne) SetName(s string) *WorkflowUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableName(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetStatus sets the "status" field.
func (wuo *WorkflowUpdateOne) SetStatus(s string) *WorkflowUpdateOne {
	wuo.mutation.SetStatus(s)
	return wuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableStatus(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetStatus(*s)
	}
	return wuo
}

// SetTraceID sets the "trace_id" field.
func (wuo *WorkflowUpdateOne) SetTraceID(s string) *WorkflowUpdateOne {
	wuo.mutation.SetTraceID(s)
	return wuo
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableTraceID(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetTraceID(*s)
	}
	return wuo
}

// ClearTraceID clears the value of the "trace_id" field.
func (wuo *WorkflowUpdateOne) ClearTraceID() *WorkflowUpdateOne {
	wuo.mutation.ClearTraceID()
	return wuo
}

// SetParentWorkflowID sets the "parent_workflow_id" field.
func (wuo *WorkflowUpdateOne) SetParentWorkflowID(s string) *WorkflowUpdateOne {
	wuo.mutation.SetParentWorkflowID(s)
	return wuo
}

// SetNillableParentWorkflowID sets the "parent_workflow_id" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableParentWorkflowID(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetParentWorkflowID(*s)
	}
	return wuo
}

// ClearParentWorkflowID clears the value of the "parent_workflow_id" field.
func (wuo *WorkflowUpdateOne) ClearParentWorkflowID() *WorkflowUpdateOne {
	wuo.mutation.ClearParentWorkflowID()
	return wuo
}

// SetInitiator sets the "initiator" field.
func (wuo *WorkflowUpdateOne) SetInitiator(s string) *WorkflowUpdateOne {
	wuo.mutation.SetInitiator(s)
	return wuo
}

// SetNillableInitiator sets the "initiator" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableInitiator(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetInitiator(*s)
	}
	return wuo
}

// ClearInitiator clears the value of the "initiator" field.
func (wuo *WorkflowUpdateOne) ClearInitiator() *WorkflowUpdateOne {
	wuo.mutation.ClearInitiator()
	return wuo
}

// SetInput sets the "input" field.
func (wuo *WorkflowUpdateOne) SetInput(m map[string]interface{}) *WorkflowUpdateOne {
	wuo.mutation.SetInput(m)
	return wuo
}

// ClearInput clears the value of the "input" field.
func (wuo *WorkflowUpdateOne) ClearInput() *WorkflowUpdateOne {
	wuo.mutation.ClearInput()
	return wuo
}

// SetOutput sets the "output" field.
func (wuo *WorkflowUpdateOne) SetOutput(m map[string]interface{}) *WorkflowUpdateOne {
	wuo.mutation.SetOutput(m)
	return wuo
}

// ClearOutput clears the value of the "output" field.
func (wuo *WorkflowUpdateOne) ClearOutput() *WorkflowUpdateOne {
	wuo.mutation.ClearOutput()
	return wuo
}

// SetMetadata sets the "metadata" field.
func (wuo *WorkflowUpdateOne) SetMetadata(m map[string]interface{}) *WorkflowUpdateOne {
	wuo.mutation.SetMetadata(m)
	return wuo
}

// ClearMetadata clears the value of the "metadata" field.
func (wuo *WorkflowUpdateOne) ClearMetadata() *WorkflowUpdateOne {
	wuo.mutation.ClearMetadata()
	return wuo
}

// SetTaskCount sets the "task_count" field.
func (wuo *WorkflowUpdateOne) SetTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.ResetTaskCount()
	wuo.mutation.SetTaskCount(i)
	return wuo
}

// SetNillableTaskCount sets the "task_count" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableTaskCount(i *int) *WorkflowUpdateOne {
	if i != nil {
		wuo.SetTaskCount(*i)
	}
	return wuo
}

// AddTaskCount adds i to the "task_count" field.
func (wuo *WorkflowUpdateOne) AddTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.AddTaskCount(i)
	return wuo
}

// SetCompletedTaskCount sets the "completed_task_count" field.
func (wuo *WorkflowUpdateOne) SetCompletedTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.ResetCompletedTaskCount()
	wuo.mutation.SetCompletedTaskCount(i)
	return wuo
}

// SetNillableCompletedTaskCount sets the "completed_task_count" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableCompletedTaskCount(i *int) *WorkflowUpdateOne {
	if i != nil {
		wuo.SetCompletedTaskCount(*i)
	}
	return wuo
}

// AddCompletedTaskCount adds i to the "completed_task_count" field.
func (wuo *WorkflowUpdateOne) AddCompletedTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.AddCompletedTaskCount(i)
	return wuo
}

// SetFailedTaskCount sets the "failed_task_count" field.
func (wuo *WorkflowUpdateOne) SetFailedTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.ResetFailedTaskCount()
	wuo.mutation.SetFailedTaskCount(i)
	return wuo
}

// SetNillableFailedTaskCount sets the "failed_task_count" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableFailedTaskCount(i *int) *WorkflowUpdateOne {
	if i != nil {
		wuo.SetFailedTaskCount(*i)
	}
	return wuo
}

// AddFailedTaskCount adds i to the "failed_task_count" field.
func (wuo *WorkflowUpdateOne) AddFailedTaskCount(i int) *WorkflowUpdateOne {
	wuo.mutation.AddFailedTaskCount(i)
	return wuo
}

// SetTotalCostUsd sets the "total_cost_usd" field.
func (wuo *WorkflowUpdateOne) SetTotalCostUsd(f float64) *WorkflowUpdateOne {
	wuo.mutation.ResetTotalCostUsd()
	wuo.mutation.SetTotalCostUsd(f)
	return wuo
}

// SetNillableTotalCostUsd sets the "total_cost_usd" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableTotalCostUsd(f *float64) *WorkflowUpdateOne {
	if f != nil {
		wuo.SetTotalCostUsd(*f)
	}
	return wuo
}

// AddTotalCostUsd adds f to the "total_cost_usd" field.
func (wuo *WorkflowUpdateOne) AddTotalCostUsd(f float64) *WorkflowUpdateOne {
	wuo.mutation.AddTotalCostUsd(f)
	return wuo
}

// SetTotalTokens sets the "total_tokens" field.
func (wuo *WorkflowUpdateOne) SetTotalTokens(i int) *WorkflowUpdateOne {
	wuo.mutation.ResetTotalTokens()
	wuo.mutation.SetTotalTokens(i)
	return wuo
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableTotalTokens(i *int) *WorkflowUpdateOne {
	if i != nil {
		wuo.SetTotalTokens(*i)
	}
	return wuo
}

// AddTotalTokens adds i to the "total_tokens" field.
func (wuo *WorkflowUpdateOne) AddTotalTokens(i int) *WorkflowUpdateOne {
	wuo.mutation.AddTotalTokens(i)
	return wuo
}

// SetDurationMs sets the "duration_ms" field.
func (wuo *WorkflowUpdateOne) SetDurationMs(i int64) *WorkflowUpdateOne {
	wuo.mutation.ResetDurationMs()
	wuo.mutation.SetDurationMs(i)
	return wuo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableDurationMs(i *int64) *WorkflowUpdateOne {
	if i != nil {
		wuo.SetDurationMs(*i)
	}
	return wuo
}

// AddDurationMs adds i to the "duration_ms" field.
func (wuo *WorkflowUpdateOne) AddDurationMs(i int64) *WorkflowUpdateOne {
	wuo.mutation.AddDurationMs(i)
	return wuo
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (wuo *WorkflowUpdateOne) ClearDurationMs() *WorkflowUpdateOne {
	wuo.mutation.ClearDurationMs()
	return wuo
}

// SetErrorMessage sets the "error_message" field.
func (wuo *WorkflowUpdateOne) SetErrorMessage(s string) *WorkflowUpdateOne {
	wuo.mutation.SetErrorMessage(s)
	return wuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableErrorMessage(s *string) *WorkflowUpdateOne {
	if s != nil {
		wuo.SetErrorMessage(*s)
	}
	return wuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (wuo *WorkflowUpdateOne) ClearErrorMessage() *WorkflowUpdateOne {
	wuo.mutation.ClearErrorMessage()
	return wuo
}

// SetEndedAt sets the "ended_at" field.
func (wuo *WorkflowUpdateOne) SetEndedAt(t time.Time) *WorkflowUpdateOne {
	wuo.mutation.SetEndedAt(t)
	return wuo
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (wuo *WorkflowUpdateOne) SetNillableEndedAt(t *time.Time) *WorkflowUpdateOne {
	if t != nil {
		wuo.SetEndedAt(*t)
	}
	return wuo
}

// ClearEndedAt clears the value of the "ended_at" field.
func (wuo *WorkflowUpdateOne) ClearEndedAt() *WorkflowUpdateOne {
	wuo.mutation.ClearEndedAt()
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WorkflowUpdateOne) SetUpdatedAt(t time.Time) *WorkflowUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// AddTaskIDs adds the "tasks" edge to the AgentTask entity by IDs.
func (wuo *WorkflowUpdateOne) AddTaskIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.AddTaskIDs(ids...)
	return wuo
}

// AddTasks adds the "tasks" edges to the AgentTask entity.
func (wuo *WorkflowUpdateOne) AddTasks(a ...*AgentTask) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.AddTaskIDs(ids...)
}

// AddHandoffIDs adds the "handoffs" edge to the AgentHandoff entity by IDs.
func (wuo *WorkflowUpdateOne) AddHandoffIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.AddHandoffIDs(ids...)
	return wuo
}

// AddHandoffs adds the "handoffs" edges to the AgentHandoff entity.
func (wuo *WorkflowUpdateOne) AddHandoffs(a ...*AgentHandoff) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.AddHandoffIDs(ids...)
}

// AddEventIDs adds the "events" edge to the AgentEvent entity by IDs.
func (wuo *WorkflowUpdateOne) AddEventIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.AddEventIDs(ids...)
	return wuo
}

// AddEvents adds the "events" edges to the AgentEvent entity.
func (wuo *WorkflowUpdateOne) AddEvents(a ...*AgentEvent) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.AddEventIDs(ids...)
}

// Mutation returns the WorkflowMutation object of the builder.
func (wuo *WorkflowUpdateOne) Mutation() *WorkflowMutation {
	return wuo.mutation
}

// ClearTasks clears all "tasks" edges to the AgentTask entity.
func (wuo *WorkflowUpdateOne) ClearTasks() *WorkflowUpdateOne {
	wuo.mutation.ClearTasks()
	return wuo
}

// RemoveTaskIDs removes the "tasks" edge to AgentTask entities by IDs.
func (wuo *WorkflowUpdateOne) RemoveTaskIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.RemoveTaskIDs(ids...)
	return wuo
}

// RemoveTasks removes "tasks" edges to AgentTask entities.
func (wuo *WorkflowUpdateOne) RemoveTasks(a ...*AgentTask) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.RemoveTaskIDs(ids...)
}

// ClearHandoffs clears all "handoffs" edges to the AgentHandoff entity.
func (wuo *WorkflowUpdateOne) ClearHandoffs() *WorkflowUpdateOne {
	wuo.mutation.ClearHandoffs()
	return wuo
}

// RemoveHandoffIDs removes the "handoffs" edge to AgentHandoff entities by IDs.
func (wuo *WorkflowUpdateOne) RemoveHandoffIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.RemoveHandoffIDs(ids...)
	return wuo
}

// RemoveHandoffs removes "handoffs" edges to AgentHandoff entities.
func (wuo *WorkflowUpdateOne) RemoveHandoffs(a ...*AgentHandoff) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.RemoveHandoffIDs(ids...)
}

// ClearEvents clears all "events" edges to the AgentEvent entity.
func (wuo *WorkflowUpdateOne) ClearEvents() *WorkflowUpdateOne {
	wuo.mutation.ClearEvents()
	return wuo
}

// RemoveEventIDs removes the "events" edge to AgentEvent entities by IDs.
func (wuo *WorkflowUpdateOne) RemoveEventIDs(ids ...string) *WorkflowUpdateOne {
	wuo.mutation.RemoveEventIDs(ids...)
	return wuo
}

// RemoveEvents removes "events" edges to AgentEvent entities.
func (wuo *WorkflowUpdateOne) RemoveEvents(a ...*AgentEvent) *WorkflowUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return wuo.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the WorkflowUpdate builder.
func (wuo *WorkflowUpdateOne) Where(ps ...predicate.Workflow) *WorkflowUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkflowUpdateOne) Select(field string, fields ...string) *WorkflowUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workflow entity.
func (wuo *WorkflowUpdateOne) Save(ctx context.Context) (*Workflow, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) SaveX(ctx context.Context) *Workflow {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkflowUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkflowUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WorkflowUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		v := workflow.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *WorkflowUpdateOne) check() error {
	if v, ok := wuo.mutation.Name(); ok {
		if err := workflow.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workflow.name": %w`, err)}
		}
	}
	return nil
}

func (wuo *WorkflowUpdateOne) sqlSave(ctx context.Context) (_node *Workflow, err error) {
	if err := wuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflow.Table, workflow.Columns, sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workflow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflow.FieldID)
		for _, f := range fields {
			if !workflow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workflow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workflow.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Status(); ok {
		_spec.SetField(workflow.FieldStatus, field.TypeString, value)
	}
	if value, ok := wuo.mutation.TraceID(); ok {
		_spec.SetField(workflow.FieldTraceID, field.TypeString, value)
	}
	if wuo.mutation.TraceIDCleared() {
		_spec.ClearField(workflow.FieldTraceID, field.TypeString)
	}
	if value, ok := wuo.mutation.ParentWorkflowID(); ok {
		_spec.SetField(workflow.FieldParentWorkflowID, field.TypeString, value)
	}
	if wuo.mutation.ParentWorkflowIDCleared() {
		_spec.ClearField(workflow.FieldParentWorkflowID, field.TypeString)
	}
	if value, ok := wuo.mutation.Initiator(); ok {
		_spec.SetField(workflow.FieldInitiator, field.TypeString, value)
	}
	if wuo.mutation.InitiatorCleared() {
		_spec.ClearField(workflow.FieldInitiator, field.TypeString)
	}
	if value, ok := wuo.mutation.Input(); ok {
		_spec.SetField(workflow.FieldInput, field.TypeJSON, value)
	}
	if wuo.mutation.InputCleared() {
		_spec.ClearField(workflow.FieldInput, field.TypeJSON)
	}
	if value, ok := wuo.mutation.Output(); ok {
		_spec.SetField(workflow.FieldOutput, field.TypeJSON, value)
	}
	if wuo.mutation.OutputCleared() {
		_spec.ClearField(workflow.FieldOutput, field.TypeJSON)
	}
	if value, ok := wuo.mutation.Metadata(); ok {
		_spec.SetField(workflow.FieldMetadata, field.TypeJSON, value)
	}
	if wuo.mutation.MetadataCleared() {
		_spec.ClearField(workflow.FieldMetadata, field.TypeJSON)
	}
	if value, ok := wuo.mutation.TaskCount(); ok {
		_spec.SetField(workflow.FieldTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedTaskCount(); ok {
		_spec.AddField(workflow.FieldTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.CompletedTaskCount(); ok {
		_spec.SetField(workflow.FieldCompletedTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedCompletedTaskCount(); ok {
		_spec.AddField(workflow.FieldCompletedTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.FailedTaskCount(); ok {
		_spec.SetField(workflow.FieldFailedTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedFailedTaskCount(); ok {
		_spec.AddField(workflow.FieldFailedTaskCount, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.TotalCostUsd(); ok {
		_spec.SetField(workflow.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := wuo.mutation.AddedTotalCostUsd(); ok {
		_spec.AddField(workflow.FieldTotalCostUsd, field.TypeFloat64, value)
	}
	if value, ok := wuo.mutation.TotalTokens(); ok {
		_spec.SetField(workflow.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.AddedTotalTokens(); ok {
		_spec.AddField(workflow.FieldTotalTokens, field.TypeInt, value)
	}
	if value, ok := wuo.mutation.DurationMs(); ok {
		_spec.SetField(workflow.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedDurationMs(); ok {
		_spec.AddField(workflow.FieldDurationMs, field.TypeInt64, value)
	}
	if wuo.mutation.DurationMsCleared() {
		_spec.ClearField(workflow.FieldDurationMs, field.TypeInt64)
	}
	if value, ok := wuo.mutation.ErrorMessage(); ok {
		_spec.SetField(workflow.FieldErrorMessage, field.TypeString, value)
	}
	if wuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(workflow.FieldErrorMessage, field.TypeString)
	}
	if value, ok := wuo.mutation.EndedAt(); ok {
		_spec.SetField(workflow.FieldEndedAt, field.TypeTime, value)
	}
	if wuo.mutation.EndedAtCleared() {
		_spec.ClearField(workflow.FieldEndedAt, field.TypeTime)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workflow.FieldUpdatedAt, field.TypeTime, value)
	}
	if wuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !wuo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.TasksTable,
			Columns: []string{workflow.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.HandoffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedHandoffsIDs(); len(nodes) > 0 && !wuo.mutation.HandoffsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.HandoffsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.HandoffsTable,
			Columns: []string{workflow.HandoffsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenthandoff.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if wuo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedEventsIDs(); len(nodes) > 0 && !wuo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflow.EventsTable,
			Columns: []string{workflow.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workflow{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
