// Code generated by ent, DO NOT EDIT.

package agentevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldID, id))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldEventType, v))
}

// EventCategory applies equality check predicate on the "event_category" field. It's identical to EventCategoryEQ.
func EventCategory(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldEventCategory, v))
}

// WorkflowID applies equality check predicate on the "workflow_id" field. It's identical to WorkflowIDEQ.
func WorkflowID(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldWorkflowID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTaskID, v))
}

// AgentID applies equality check predicate on the "agent_id" field. It's identical to AgentIDEQ.
func AgentID(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldAgentID, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTraceID, v))
}

// SpanID applies equality check predicate on the "span_id" field. It's identical to SpanIDEQ.
func SpanID(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSpanID, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSeverity, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSource, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldVersion, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTimestamp, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldEventType, v))
}

// EventCategoryEQ applies the EQ predicate on the "event_category" field.
func EventCategoryEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldEventCategory, v))
}

// EventCategoryNEQ applies the NEQ predicate on the "event_category" field.
func EventCategoryNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldEventCategory, v))
}

// EventCategoryIn applies the In predicate on the "event_category" field.
func EventCategoryIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldEventCategory, vs...))
}

// EventCategoryNotIn applies the NotIn predicate on the "event_category" field.
func EventCategoryNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldEventCategory, vs...))
}

// EventCategoryGT applies the GT predicate on the "event_category" field.
func EventCategoryGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldEventCategory, v))
}

// EventCategoryGTE applies the GTE predicate on the "event_category" field.
func EventCategoryGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldEventCategory, v))
}

// EventCategoryLT applies the LT predicate on the "event_category" field.
func EventCategoryLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldEventCategory, v))
}

// EventCategoryLTE applies the LTE predicate on the "event_category" field.
func EventCategoryLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldEventCategory, v))
}

// EventCategoryContains applies the Contains predicate on the "event_category" field.
func EventCategoryContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldEventCategory, v))
}

// EventCategoryHasPrefix applies the HasPrefix predicate on the "event_category" field.
func EventCategoryHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldEventCategory, v))
}

// EventCategoryHasSuffix applies the HasSuffix predicate on the "event_category" field.
func EventCategoryHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldEventCategory, v))
}

// EventCategoryEqualFold applies the EqualFold predicate on the "event_category" field.
func EventCategoryEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldEventCategory, v))
}

// EventCategoryContainsFold applies the ContainsFold predicate on the "event_category" field.
func EventCategoryContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldEventCategory, v))
}

// WorkflowIDEQ applies the EQ predicate on the "workflow_id" field.
func WorkflowIDEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldWorkflowID, v))
}

// WorkflowIDNEQ applies the NEQ predicate on the "workflow_id" field.
func WorkflowIDNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldWorkflowID, v))
}

// WorkflowIDIn applies the In predicate on the "workflow_id" field.
func WorkflowIDIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldWorkflowID, vs...))
}

// WorkflowIDNotIn applies the NotIn predicate on the "workflow_id" field.
func WorkflowIDNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldWorkflowID, vs...))
}

// WorkflowIDGT applies the GT predicate on the "workflow_id" field.
func WorkflowIDGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldWorkflowID, v))
}

// WorkflowIDGTE applies the GTE predicate on the "workflow_id" field.
func WorkflowIDGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldWorkflowID, v))
}

// WorkflowIDLT applies the LT predicate on the "workflow_id" field.
func WorkflowIDLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldWorkflowID, v))
}

// WorkflowIDLTE applies the LTE predicate on the "workflow_id" field.
func WorkflowIDLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldWorkflowID, v))
}

// WorkflowIDContains applies the Contains predicate on the "workflow_id" field.
func WorkflowIDContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldWorkflowID, v))
}

// WorkflowIDHasPrefix applies the HasPrefix predicate on the "workflow_id" field.
func WorkflowIDHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldWorkflowID, v))
}

// WorkflowIDHasSuffix applies the HasSuffix predicate on the "workflow_id" field.
func WorkflowIDHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldWorkflowID, v))
}

// WorkflowIDIsNil applies the IsNil predicate on the "workflow_id" field.
func WorkflowIDIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldWorkflowID))
}

// WorkflowIDNotNil applies the NotNil predicate on the "workflow_id" field.
func WorkflowIDNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldWorkflowID))
}

// WorkflowIDEqualFold applies the EqualFold predicate on the "workflow_id" field.
func WorkflowIDEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldWorkflowID, v))
}

// WorkflowIDContainsFold applies the ContainsFold predicate on the "workflow_id" field.
func WorkflowIDContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldWorkflowID, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldTaskID))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldTaskID, v))
}

// AgentIDEQ applies the EQ predicate on the "agent_id" field.
func AgentIDEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldAgentID, v))
}

// AgentIDNEQ applies the NEQ predicate on the "agent_id" field.
func AgentIDNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldAgentID, v))
}

// AgentIDIn applies the In predicate on the "agent_id" field.
func AgentIDIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldAgentID, vs...))
}

// AgentIDNotIn applies the NotIn predicate on the "agent_id" field.
func AgentIDNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldAgentID, vs...))
}

// AgentIDGT applies the GT predicate on the "agent_id" field.
func AgentIDGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldAgentID, v))
}

// AgentIDGTE applies the GTE predicate on the "agent_id" field.
func AgentIDGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldAgentID, v))
}

// AgentIDLT applies the LT predicate on the "agent_id" field.
func AgentIDLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldAgentID, v))
}

// AgentIDLTE applies the LTE predicate on the "agent_id" field.
func AgentIDLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldAgentID, v))
}

// AgentIDContains applies the Contains predicate on the "agent_id" field.
func AgentIDContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldAgentID, v))
}

// AgentIDHasPrefix applies the HasPrefix predicate on the "agent_id" field.
func AgentIDHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldAgentID, v))
}

// AgentIDHasSuffix applies the HasSuffix predicate on the "agent_id" field.
func AgentIDHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldAgentID, v))
}

// AgentIDIsNil applies the IsNil predicate on the "agent_id" field.
func AgentIDIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldAgentID))
}

// AgentIDNotNil applies the NotNil predicate on the "agent_id" field.
func AgentIDNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldAgentID))
}

// AgentIDEqualFold applies the EqualFold predicate on the "agent_id" field.
func AgentIDEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldAgentID, v))
}

// AgentIDContainsFold applies the ContainsFold predicate on the "agent_id" field.
func AgentIDContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldAgentID, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDIsNil applies the IsNil predicate on the "trace_id" field.
func TraceIDIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldTraceID))
}

// TraceIDNotNil applies the NotNil predicate on the "trace_id" field.
func TraceIDNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldTraceID))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldTraceID, v))
}

// SpanIDEQ applies the EQ predicate on the "span_id" field.
func SpanIDEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSpanID, v))
}

// SpanIDNEQ applies the NEQ predicate on the "span_id" field.
func SpanIDNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldSpanID, v))
}

// SpanIDIn applies the In predicate on the "span_id" field.
func SpanIDIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldSpanID, vs...))
}

// SpanIDNotIn applies the NotIn predicate on the "span_id" field.
func SpanIDNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldSpanID, vs...))
}

// SpanIDGT applies the GT predicate on the "span_id" field.
func SpanIDGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldSpanID, v))
}

// SpanIDGTE applies the GTE predicate on the "span_id" field.
func SpanIDGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldSpanID, v))
}

// SpanIDLT applies the LT predicate on the "span_id" field.
func SpanIDLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldSpanID, v))
}

// SpanIDLTE applies the LTE predicate on the "span_id" field.
func SpanIDLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldSpanID, v))
}

// SpanIDContains applies the Contains predicate on the "span_id" field.
func SpanIDContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldSpanID, v))
}

// SpanIDHasPrefix applies the HasPrefix predicate on the "span_id" field.
func SpanIDHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldSpanID, v))
}

// SpanIDHasSuffix applies the HasSuffix predicate on the "span_id" field.
func SpanIDHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldSpanID, v))
}

// SpanIDIsNil applies the IsNil predicate on the "span_id" field.
func SpanIDIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldSpanID))
}

// SpanIDNotNil applies the NotNil predicate on the "span_id" field.
func SpanIDNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldSpanID))
}

// SpanIDEqualFold applies the EqualFold predicate on the "span_id" field.
func SpanIDEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldSpanID, v))
}

// SpanIDContainsFold applies the ContainsFold predicate on the "span_id" field.
func SpanIDContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldSpanID, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldData))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldMetadata))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldTags))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotNull(FieldSource))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldSource, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldContainsFold(FieldVersion, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldTimestamp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AgentEvent {
	return predicate.AgentEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasWorkflow applies the HasEdge predicate on the "workflow" edge.
func HasWorkflow() predicate.AgentEvent {
	return predicate.AgentEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkflowTable, WorkflowColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkflowWith applies the HasEdge predicate on the "workflow" edge with a given conditions (other predicates).
func HasWorkflowWith(preds ...predicate.Workflow) predicate.AgentEvent {
	return predicate.AgentEvent(func(s *sql.Selector) {
		step := newWorkflowStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.AgentEvent {
	return predicate.AgentEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.AgentTask) predicate.AgentEvent {
	return predicate.AgentEvent(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentEvent) predicate.AgentEvent {
	return predicate.AgentEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentEvent) predicate.AgentEvent {
	return predicate.AgentEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentEvent) predicate.AgentEvent {
	return predicate.AgentEvent(sql.NotPredicates(p))
}
