// Code generated by ent, DO NOT EDIT.

package workflow

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/plexusone/omniobserve/agentops/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldStatus, v))
}

// TraceID applies equality check predicate on the "trace_id" field. It's identical to TraceIDEQ.
func TraceID(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTraceID, v))
}

// ParentWorkflowID applies equality check predicate on the "parent_workflow_id" field. It's identical to ParentWorkflowIDEQ.
func ParentWorkflowID(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldParentWorkflowID, v))
}

// Initiator applies equality check predicate on the "initiator" field. It's identical to InitiatorEQ.
func Initiator(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldInitiator, v))
}

// TaskCount applies equality check predicate on the "task_count" field. It's identical to TaskCountEQ.
func TaskCount(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTaskCount, v))
}

// CompletedTaskCount applies equality check predicate on the "completed_task_count" field. It's identical to CompletedTaskCountEQ.
func CompletedTaskCount(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldCompletedTaskCount, v))
}

// FailedTaskCount applies equality check predicate on the "failed_task_count" field. It's identical to FailedTaskCountEQ.
func FailedTaskCount(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldFailedTaskCount, v))
}

// TotalCostUsd applies equality check predicate on the "total_cost_usd" field. It's identical to TotalCostUsdEQ.
func TotalCostUsd(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTotalCostUsd, v))
}

// TotalTokens applies equality check predicate on the "total_tokens" field. It's identical to TotalTokensEQ.
func TotalTokens(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTotalTokens, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldEndedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldStatus, v))
}

// TraceIDEQ applies the EQ predicate on the "trace_id" field.
func TraceIDEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTraceID, v))
}

// TraceIDNEQ applies the NEQ predicate on the "trace_id" field.
func TraceIDNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldTraceID, v))
}

// TraceIDIn applies the In predicate on the "trace_id" field.
func TraceIDIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldTraceID, vs...))
}

// TraceIDNotIn applies the NotIn predicate on the "trace_id" field.
func TraceIDNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldTraceID, vs...))
}

// TraceIDGT applies the GT predicate on the "trace_id" field.
func TraceIDGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldTraceID, v))
}

// TraceIDGTE applies the GTE predicate on the "trace_id" field.
func TraceIDGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldTraceID, v))
}

// TraceIDLT applies the LT predicate on the "trace_id" field.
func TraceIDLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldTraceID, v))
}

// TraceIDLTE applies the LTE predicate on the "trace_id" field.
func TraceIDLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldTraceID, v))
}

// TraceIDContains applies the Contains predicate on the "trace_id" field.
func TraceIDContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldTraceID, v))
}

// TraceIDHasPrefix applies the HasPrefix predicate on the "trace_id" field.
func TraceIDHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldTraceID, v))
}

// TraceIDHasSuffix applies the HasSuffix predicate on the "trace_id" field.
func TraceIDHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldTraceID, v))
}

// TraceIDIsNil applies the IsNil predicate on the "trace_id" field.
func TraceIDIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldTraceID))
}

// TraceIDNotNil applies the NotNil predicate on the "trace_id" field.
func TraceIDNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldTraceID))
}

// TraceIDEqualFold applies the EqualFold predicate on the "trace_id" field.
func TraceIDEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldTraceID, v))
}

// TraceIDContainsFold applies the ContainsFold predicate on the "trace_id" field.
func TraceIDContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldTraceID, v))
}

// ParentWorkflowIDEQ applies the EQ predicate on the "parent_workflow_id" field.
func ParentWorkflowIDEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldParentWorkflowID, v))
}

// ParentWorkflowIDNEQ applies the NEQ predicate on the "parent_workflow_id" field.
func ParentWorkflowIDNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldParentWorkflowID, v))
}

// ParentWorkflowIDIn applies the In predicate on the "parent_workflow_id" field.
func ParentWorkflowIDIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldParentWorkflowID, vs...))
}

// ParentWorkflowIDNotIn applies the NotIn predicate on the "parent_workflow_id" field.
func ParentWorkflowIDNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldParentWorkflowID, vs...))
}

// ParentWorkflowIDGT applies the GT predicate on the "parent_workflow_id" field.
func ParentWorkflowIDGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldParentWorkflowID, v))
}

// ParentWorkflowIDGTE applies the GTE predicate on the "parent_workflow_id" field.
func ParentWorkflowIDGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldParentWorkflowID, v))
}

// ParentWorkflowIDLT applies the LT predicate on the "parent_workflow_id" field.
func ParentWorkflowIDLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldParentWorkflowID, v))
}

// ParentWorkflowIDLTE applies the LTE predicate on the "parent_workflow_id" field.
func ParentWorkflowIDLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldParentWorkflowID, v))
}

// ParentWorkflowIDContains applies the Contains predicate on the "parent_workflow_id" field.
func ParentWorkflowIDContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldParentWorkflowID, v))
}

// ParentWorkflowIDHasPrefix applies the HasPrefix predicate on the "parent_workflow_id" field.
func ParentWorkflowIDHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldParentWorkflowID, v))
}

// ParentWorkflowIDHasSuffix applies the HasSuffix predicate on the "parent_workflow_id" field.
func ParentWorkflowIDHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldParentWorkflowID, v))
}

// ParentWorkflowIDIsNil applies the IsNil predicate on the "parent_workflow_id" field.
func ParentWorkflowIDIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldParentWorkflowID))
}

// ParentWorkflowIDNotNil applies the NotNil predicate on the "parent_workflow_id" field.
func ParentWorkflowIDNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldParentWorkflowID))
}

// ParentWorkflowIDEqualFold applies the EqualFold predicate on the "parent_workflow_id" field.
func ParentWorkflowIDEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldParentWorkflowID, v))
}

// ParentWorkflowIDContainsFold applies the ContainsFold predicate on the "parent_workflow_id" field.
func ParentWorkflowIDContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldParentWorkflowID, v))
}

// InitiatorEQ applies the EQ predicate on the "initiator" field.
func InitiatorEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldInitiator, v))
}

// InitiatorNEQ applies the NEQ predicate on the "initiator" field.
func InitiatorNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldInitiator, v))
}

// InitiatorIn applies the In predicate on the "initiator" field.
func InitiatorIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldInitiator, vs...))
}

// InitiatorNotIn applies the NotIn predicate on the "initiator" field.
func InitiatorNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldInitiator, vs...))
}

// InitiatorGT applies the GT predicate on the "initiator" field.
func InitiatorGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldInitiator, v))
}

// InitiatorGTE applies the GTE predicate on the "initiator" field.
func InitiatorGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldInitiator, v))
}

// InitiatorLT applies the LT predicate on the "initiator" field.
func InitiatorLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldInitiator, v))
}

// InitiatorLTE applies the LTE predicate on the "initiator" field.
func InitiatorLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldInitiator, v))
}

// InitiatorContains applies the Contains predicate on the "initiator" field.
func InitiatorContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldInitiator, v))
}

// InitiatorHasPrefix applies the HasPrefix predicate on the "initiator" field.
func InitiatorHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldInitiator, v))
}

// InitiatorHasSuffix applies the HasSuffix predicate on the "initiator" field.
func InitiatorHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldInitiator, v))
}

// InitiatorIsNil applies the IsNil predicate on the "initiator" field.
func InitiatorIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldInitiator))
}

// InitiatorNotNil applies the NotNil predicate on the "initiator" field.
func InitiatorNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldInitiator))
}

// InitiatorEqualFold applies the EqualFold predicate on the "initiator" field.
func InitiatorEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldInitiator, v))
}

// InitiatorContainsFold applies the ContainsFold predicate on the "initiator" field.
func InitiatorContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldInitiator, v))
}

// InputIsNil applies the IsNil predicate on the "input" field.
func InputIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldInput))
}

// InputNotNil applies the NotNil predicate on the "input" field.
func InputNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldInput))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldOutput))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldMetadata))
}

// TaskCountEQ applies the EQ predicate on the "task_count" field.
func TaskCountEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTaskCount, v))
}

// TaskCountNEQ applies the NEQ predicate on the "task_count" field.
func TaskCountNEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldTaskCount, v))
}

// TaskCountIn applies the In predicate on the "task_count" field.
func TaskCountIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldTaskCount, vs...))
}

// TaskCountNotIn applies the NotIn predicate on the "task_count" field.
func TaskCountNotIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldTaskCount, vs...))
}

// TaskCountGT applies the GT predicate on the "task_count" field.
func TaskCountGT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldTaskCount, v))
}

// TaskCountGTE applies the GTE predicate on the "task_count" field.
func TaskCountGTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldTaskCount, v))
}

// TaskCountLT applies the LT predicate on the "task_count" field.
func TaskCountLT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldTaskCount, v))
}

// TaskCountLTE applies the LTE predicate on the "task_count" field.
func TaskCountLTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldTaskCount, v))
}

// CompletedTaskCountEQ applies the EQ predicate on the "completed_task_count" field.
func CompletedTaskCountEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldCompletedTaskCount, v))
}

// CompletedTaskCountNEQ applies the NEQ predicate on the "completed_task_count" field.
func CompletedTaskCountNEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldCompletedTaskCount, v))
}

// CompletedTaskCountIn applies the In predicate on the "completed_task_count" field.
func CompletedTaskCountIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldCompletedTaskCount, vs...))
}

// CompletedTaskCountNotIn applies the NotIn predicate on the "completed_task_count" field.
func CompletedTaskCountNotIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldCompletedTaskCount, vs...))
}

// CompletedTaskCountGT applies the GT predicate on the "completed_task_count" field.
func CompletedTaskCountGT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldCompletedTaskCount, v))
}

// CompletedTaskCountGTE applies the GTE predicate on the "completed_task_count" field.
func CompletedTaskCountGTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldCompletedTaskCount, v))
}

// CompletedTaskCountLT applies the LT predicate on the "completed_task_count" field.
func CompletedTaskCountLT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldCompletedTaskCount, v))
}

// CompletedTaskCountLTE applies the LTE predicate on the "completed_task_count" field.
func CompletedTaskCountLTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldCompletedTaskCount, v))
}

// FailedTaskCountEQ applies the EQ predicate on the "failed_task_count" field.
func FailedTaskCountEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldFailedTaskCount, v))
}

// FailedTaskCountNEQ applies the NEQ predicate on the "failed_task_count" field.
func FailedTaskCountNEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldFailedTaskCount, v))
}

// FailedTaskCountIn applies the In predicate on the "failed_task_count" field.
func FailedTaskCountIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldFailedTaskCount, vs...))
}

// FailedTaskCountNotIn applies the NotIn predicate on the "failed_task_count" field.
func FailedTaskCountNotIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldFailedTaskCount, vs...))
}

// FailedTaskCountGT applies the GT predicate on the "failed_task_count" field.
func FailedTaskCountGT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldFailedTaskCount, v))
}

// FailedTaskCountGTE applies the GTE predicate on the "failed_task_count" field.
func FailedTaskCountGTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldFailedTaskCount, v))
}

// FailedTaskCountLT applies the LT predicate on the "failed_task_count" field.
func FailedTaskCountLT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldFailedTaskCount, v))
}

// FailedTaskCountLTE applies the LTE predicate on the "failed_task_count" field.
func FailedTaskCountLTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldFailedTaskCount, v))
}

// TotalCostUsdEQ applies the EQ predicate on the "total_cost_usd" field.
func TotalCostUsdEQ(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTotalCostUsd, v))
}

// TotalCostUsdNEQ applies the NEQ predicate on the "total_cost_usd" field.
func TotalCostUsdNEQ(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldTotalCostUsd, v))
}

// TotalCostUsdIn applies the In predicate on the "total_cost_usd" field.
func TotalCostUsdIn(vs ...float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldTotalCostUsd, vs...))
}

// TotalCostUsdNotIn applies the NotIn predicate on the "total_cost_usd" field.
func TotalCostUsdNotIn(vs ...float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldTotalCostUsd, vs...))
}

// TotalCostUsdGT applies the GT predicate on the "total_cost_usd" field.
func TotalCostUsdGT(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldTotalCostUsd, v))
}

// TotalCostUsdGTE applies the GTE predicate on the "total_cost_usd" field.
func TotalCostUsdGTE(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldTotalCostUsd, v))
}

// TotalCostUsdLT applies the LT predicate on the "total_cost_usd" field.
func TotalCostUsdLT(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldTotalCostUsd, v))
}

// TotalCostUsdLTE applies the LTE predicate on the "total_cost_usd" field.
func TotalCostUsdLTE(v float64) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldTotalCostUsd, v))
}

// TotalTokensEQ applies the EQ predicate on the "total_tokens" field.
func TotalTokensEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldTotalTokens, v))
}

// TotalTokensNEQ applies the NEQ predicate on the "total_tokens" field.
func TotalTokensNEQ(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldTotalTokens, v))
}

// TotalTokensIn applies the In predicate on the "total_tokens" field.
func TotalTokensIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldTotalTokens, vs...))
}

// TotalTokensNotIn applies the NotIn predicate on the "total_tokens" field.
func TotalTokensNotIn(vs ...int) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldTotalTokens, vs...))
}

// TotalTokensGT applies the GT predicate on the "total_tokens" field.
func TotalTokensGT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldTotalTokens, v))
}

// TotalTokensGTE applies the GTE predicate on the "total_tokens" field.
func TotalTokensGTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldTotalTokens, v))
}

// TotalTokensLT applies the LT predicate on the "total_tokens" field.
func TotalTokensLT(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldTotalTokens, v))
}

// TotalTokensLTE applies the LTE predicate on the "total_tokens" field.
func TotalTokensLTE(v int) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldTotalTokens, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Workflow {
	return predicate.Workflow(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.Workflow {
	return predicate.Workflow(sql.FieldNotNull(FieldEndedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Workflow {
	return predicate.Workflow(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.AgentTask) predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHandoffs applies the HasEdge predicate on the "handoffs" edge.
func HasHandoffs() predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HandoffsTable, HandoffsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHandoffsWith applies the HasEdge predicate on the "handoffs" edge with a given conditions (other predicates).
func HasHandoffsWith(preds ...predicate.AgentHandoff) predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := newHandoffsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.AgentEvent) predicate.Workflow {
	return predicate.Workflow(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workflow) predicate.Workflow {
	return predicate.Workflow(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workflow) predicate.Workflow {
	return predicate.Workflow(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workflow) predicate.Workflow {
	return predicate.Workflow(sql.NotPredicates(p))
}
